### ISSUE TITLE
Readme needs to avoid use of language like "Sketchy code"

### ISSUE THREAD

**Issue by emabrey** [tenacityteam/tenacity-legacy#10]
In the US there are [laws against disparagement of trademarks](https://en.wikipedia.org/wiki/Lanham_Act), and the `README.md` in this repository seems, in my opinion, to be skirting or over the line in that regard. In addition to modifying the fork to avoid all unauthorized usage of the Audacity mark, this fork also needs to avoid disparaging the Audacity mark so none of the contributors get theoretically sued by the legal department over at Muse. I was considering going ahead and modifying it myself, but this issue seems to be one that needs to also be done in conjunction with #5. 

BLOCKED BY #5.

**Comment by ghost** [comment]
This is important IMO. I doubt they'd be friendly to forks, so it's important to be defensive and not provide them with opportunities to persecute these efforts.

**Comment by Maverynthia** [comment]
"Removed code with unclear intentions/purpose" would probably be a better legal way to say "sketchy code"

**Comment by rubyFeedback** [comment]
> I doubt they'd be friendly to forks

GPLv2 or later allows forks. Being "friendly" or "hostile" is entirely irrelevant in regards to the validity of doing a fork, provided the specified licence is adhered to.

Just to clarify: I have nothing against a more specified, accurate README. It just should not come down to "assumed friendliness or hostility" as that is highly subjective to an emotional analysis, but simply to verifiable claims.

**Comment by ghost** [comment]
@rubyFeedback I used "not friendly" in the sense that MuseGroup people could try to attack popular fork(s) with whatever legal weaknesses they can find. They've ~~done that~~ acted similarly before already, with MuseScore https://github.com/Xmader/musescore-downloader/issues/5

**Comment by ghost** [comment]
"Removed unwanted code in order to reduce potential attack surface"

Any unnecessary code in an application is a security issue.

And thanks for starting this.

**Comment by cookiengineer** [comment]
Thank you very much for the Pull Request. So I guess this task is done? :100:

**Comment by RoaddogLabs** [comment]
You aren't in violation of Lantham over using the term “sketchy code”.  That only applies directly to the mark and even then you wouldn’t be.  If you were to state you thought someone’s code was sketchy it’s an opinion not a disparagement of the mark.  Regardless it's an un artful term and replacing it is a good idea.  It’s not going to get you sued though.
