### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by labanmne** [tenacityteam/tenacity-legacy#106]
![issue](https://static.wikia.nocookie.net/simpsons/images/b/bb/Sneed%27s_feed_and_seed.png/revision/latest?cb=20200117163843)

I've been looking at this pic for 2 hours, but I just can't get it, what's so funny about it?

**Comment by emabrey** [comment]
Replace `eed` with `uck`.

**Comment by Kill-Animals** [comment]
> Replace `eed` with `uck`.
Reported. 
Enjoy you're ban.
