### ISSUE TITLE
Weird error message, need help?

### ISSUE THREAD

**Issue by labanmne** [tenacityteam/tenacity-legacy#115]
So I fixed the mp3 bug, but when I tried to save the project, I got this:
```
You Will Never Ever Be a Woman. 
You Must Live the Rest of Your Days Entirely as a Man, and You Will Only Grow More Masculine with Each Passing Year. 
There Is No Way Out.
```

Uhhh, can some dev from this fork explain this?

**Comment by festadurador** [comment]
If you apply the Redpill patch (available at sneedacity.org) everything should work normally.

**Comment by labanmne** [comment]
> If you apply the Redpill patch (available at sneedacity.org) everything should work normally.

Thanks, it worked!

**Comment by caughtquick** [comment]
> So I fixed the mp3 bug, but when I tried to save the project, I got this:
> 
> ```
> 
> You Will Never Ever Be a Woman. 
> 
> You Must Live the Rest of Your Days Entirely as a Man, and You Will Only Grow More Masculine with Each Passing Year. 
> 
> There Is No Way Out.
> 
> ```
> 
> 
> 
> Uhhh, can some dev from this fork explain this?

So you are being transphobic and promoting another fork of audacity on the repo of another fork then get mad when people call sneedacity not serious.

**Comment by labanmne** [comment]
> > So I fixed the mp3 bug, but when I tried to save the project, I got this:
> > ```
> > 
> > You Will Never Ever Be a Woman. 
> > 
> > You Must Live the Rest of Your Days Entirely as a Man, and You Will Only Grow More Masculine with Each Passing Year. 
> > 
> > There Is No Way Out.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Uhhh, can some dev from this fork explain this?
> 
> So you are being transphobic and promoting another fork of audacity on the repo of another fork then get mad when people call sneedacity not serious.

Excuse me? Have you tried reproducing the issue? Ripp the mp3 I did, and try to save the project. Devs of this fork must have included it. How DARE you call me transphobic, when I'm dating a sissy!? I demand a 500 word formal apology from you or I will be getting in touch with local authorities. I am NOT joking!
