### ISSUE TITLE
Is there any release package

### ISSUE THREAD

**Issue by yejkk** [tenacityteam/tenacity-legacy#116]
I can try to compile it in mac and Linux but I don't like or I think no need to compile it on other platforms.

Is there any plan to release version？

**Comment by caughtquick** [comment]
> I can try to compile it in mac and Linux but I don't like or I think no need to compile it on other platforms.
> 
> 
> 
> Is there any plan to release version？ 

I'm thinking about how I would be able to package the software for this. I'm thinking for now we will release a pkgbuild to the aur, I'll see if I can maintain a package in the void repos and release a flatpak to flathub. Maybe also create an appimage for a portable binary but I'm not sure.

**Comment by LukeHuckman** [comment]
Just wanted to let you guys know that I've published a PKGBUILD to the AUR:
https://aur.archlinux.org/packages/tenacity-git/
If anyone wants to co-maintain it, just let me know.

**Comment by Lvaskz** [comment]
For appimage packaging, you  can use appimagecrafter , see:
https://github.com/AppImageCrafters/appimage-builder

**Comment by Lvaskz** [comment]
https://appimagecrafters.github.io/

**Comment by n0toose** [comment]
See #393.
