### ISSUE TITLE
Icon and Graphics Ideas

### ISSUE THREAD

**Issue by doctormo** [tenacityteam/tenacity-legacy#12]
I'm putting this here so it's visible and available to the new project:

![audacious-fork](https://user-images.githubusercontent.com/589384/124461763-04f92300-dd5f-11eb-96a6-a68959b9314a.png)
[unbranded_sound_program.zip](https://github.com/cookiengineer/audacity/files/6763729/unbranded_sound_program.zip)

This image comes from your friendly Inkscape project. Forking is hard, but it is possible. Good luck.

**Comment by 2075** [comment]
great graphics! kudos

**Comment by abrolag** [comment]
Like the graphics, but Audacious is the name of a simple Audio Player, so best to keep away from that.

If renaming the project how about:
AudioCity

Close enough to be recognisable and clear of any copyright issues.

**Comment by DragShot** [comment]
> Like the graphics, but Audacious is the name of a simple Audio Player, so best to keep away from that.
> 
> If renaming the project how about:
> AudioCity
> 
> Close enough to be recognisable and clear of any copyright issues.

We could go on further with this and call it **AudioCT**.

**Comment by doctormo** [comment]
This thread is just for the graphic, it makes no name suggestion (audacious fork is just a pun). There is another issue that tracks all the name suggestions.

**Comment by dotjax** [comment]
I'd recommend modifying the suggested graphic to reflect the final name of the fork. For example, AudioBakery seems to be winning and if that is decided to be the new name, the graphic should probably mimic that. Either way, it looks cool.

**Comment by emabrey** [comment]
Please vote for name suggestion on #33  because posts made on #12 or #5 are not being considered currently, as the vote has already begun. We are voting on this until Sunday (2021-07-10 24:00:00 CEST).

**Comment by ThePip** [comment]
![image](https://user-images.githubusercontent.com/86794807/124542189-363b2700-de23-11eb-9ec5-7d9c6d52b376.png)

**Comment by ThePip** [comment]
![image](https://user-images.githubusercontent.com/86794807/124548685-57554500-de2e-11eb-8be3-7c6e7bf623e0.png)

**Comment by ThePip** [comment]
![image](https://user-images.githubusercontent.com/86794807/124550152-8967a680-de30-11eb-967a-5b60c449c9d2.png)
Note : these are mock ups of the most voted for ideas (obviously my idea hasnt been voted for yet, but that is the first one I posted either way since I had made the design already) and they are in no way final, they can certainly be changed

**Comment by ThePip** [comment]
![image](https://user-images.githubusercontent.com/86794807/124551564-9f766680-de32-11eb-8c00-7c6646ba4667.png)

**Comment by abrolag** [comment]
On Mon, 05 Jul 2021 21:27:31 -0700
ThePip ***@***.***> wrote:

>![image](https://user-images.githubusercontent.com/86794807/124542189-363b2700-de23-11eb-9ec5-7d9c6d52b376.png)
>
>
Not really attracted to any of them, but of the bunch Audacium is better than
the others. The name shouldn't be aimed at us, but at ordinary less-techie
people. The name should be memorable, easy to say and attractive.

Just my 2d (UK old money)

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by enslaved2die** [comment]
Audacium is the plural auf Audacia (latin for audacity (; ), I think this sounds way better and more similar to Audacity and its way more memorable.
If you want you can even say it with a english tongue and not a latin one :)

Edit: I also tried to create a new logo, I think we should clearly distant the new one from the old one, similar what Libre Office did
![image](https://user-images.githubusercontent.com/25615199/124595788-bda78b00-de61-11eb-93eb-2b0951442fde.png)

**Comment by peepo5** [comment]
> Audacium is the plural auf Audacia (latin for audacity (; ), I think this sounds way better and more similar to Audacity and its way more memorable.
> If you want you can even say it with a english tongue and not a latin one :)
> 
> Edit: I also tried to create a new logo, I think we should clearly distant the new one from the old one, similar what Libre Office did
> ![image](https://user-images.githubusercontent.com/25615199/124595788-bda78b00-de61-11eb-93eb-2b0951442fde.png)

Could you do this in Audacium? Looks great

**Comment by peepo5** [comment]
![image](https://user-images.githubusercontent.com/72892531/124641990-33721d80-de87-11eb-84c3-c993699aad1c.png)
![image](https://user-images.githubusercontent.com/72892531/124642026-3f5ddf80-de87-11eb-9c25-e6f0a1376e25.png)

I need some opinions, does this look :hankey: or alright for now?
I will attach files if it is usable.

**Comment by peepo5** [comment]
@EricBright Can this be pinned? :pray::cat:

**Comment by abrolag** [comment]
A suggestion, turn the fork into a tuning fork :)

**Comment by gitressa** [comment]
I like the fork. Soundfork?

**Comment by ChameleonScales** [comment]
My advice:
Unless whatever comes out of this is temporary until a 1.0 release or the like, let's not brand it like it's a fork.
Do you consider LibreOffice a fork of OpenOffice to this day?
This project may very well become the main one and if so, its branding will stick through time. Give this project its very own, independent and long-lasting branding.
If you're confident about going forward with this project, don't rush the branding and if possible ask a talented logo and mascot designer for help. Much preferably someone who's adamant about FOSS.
There are amazing Inkscape, Krita and Blender artists on their respective communities.
Great help may come all by itself but maybe a little call on a graphics community website could give it a good push.

**Comment by peepo5** [comment]
it was meant to be a temporary design :sob: 

Anyways I think Audacium is a good name (its the highest voted too)

**Comment by ChameleonScales** [comment]
I thought of it right after I posted, and was actually editing my post. Yes, I imagine a temporary branding might be a good idea to quickly get the original trademark off the skin of this project, and then a longer branding process can begin. In which case, a fork works fine.

**Comment by j0lol** [comment]
looks like the name has been finalised! new wordmark designs should probably be done with the new name

**Comment by EricBright** [comment]
@peepopoggers thank you for reaching out! I’m not moderating this project anymore. You might want to ping other moderators at this time. :)

**Comment by l0go** [comment]
I made these two, I would like constructive feedback and I will try to put them into a final version.
![image](https://user-images.githubusercontent.com/24994565/124674138-2dc90780-de88-11eb-82c7-7de97ab61c92.png)
![image](https://user-images.githubusercontent.com/24994565/124674397-a62fc880-de88-11eb-8c53-9496c031e459.png)

**Comment by peepo5** [comment]
> I made these two, I would like constructive feedback and I will try to put them into a final version.

Not bad! The logo looks pretty good. I feel the font could be a slight bit more bold and could also be a bit less tacky (lines arent connecting on y) but overall looks nice

**Comment by peepo5** [comment]
> @peepopoggers thank you for reaching out! I’m not moderating this project anymore. You might want to ping other moderators at this time. :)

Thanks for the short run anyways :)

**Comment by l0go** [comment]
> > I made these two, I would like constructive feedback and I will try to put them into a final version.
> 
> Not bad! The logo looks pretty good. I feel the font could be a slight bit more bold and could also be a bit less tacky (lines arent connecting on y) but overall looks nice

Alignment was a bit poor I agree. I'll work on that.

**Comment by l0go** [comment]
![image](https://user-images.githubusercontent.com/24994565/124675519-d0828580-de8a-11eb-8381-dd31035c9188.png)
@peepopoggers Do you prefer this?

**Comment by l0go** [comment]
![image](https://user-images.githubusercontent.com/24994565/124685404-3842cb80-de9f-11eb-9b10-0607034c860c.png)
I removed the gap on the Y, I like it a bit better now

**Comment by enslaved2die** [comment]
![image](https://user-images.githubusercontent.com/25615199/124752488-353fed80-df28-11eb-99e2-dd1e1d431eb6.png)
changed the name of my idea.

**Comment by enslaved2die** [comment]
> ![image](https://user-images.githubusercontent.com/24994565/124685404-3842cb80-de9f-11eb-9b10-0607034c860c.png)
> I removed the gap on the Y, I like it a bit better now

I like the idea but I think the sine curve shouldnt have these sharp angles in the inner part
![image](https://user-images.githubusercontent.com/25615199/124752889-b39c8f80-df28-11eb-88f5-4eb442e55c34.png)
Try changing the outline from middle alligned to outside alligned.

**Comment by l0go** [comment]
> Try changing the outline from middle alligned to outside alligned.

What do you mean by that? @enslaved2die

**Comment by weiameili** [comment]
> ![image](https://user-images.githubusercontent.com/25615199/124752488-353fed80-df28-11eb-99e2-dd1e1d431eb6.png)
> changed the name of my idea.

Love this. Just one thing, the "TY" in Tenacity are a bit too close.

**Comment by enslaved2die** [comment]
> > Try changing the outline from middle alligned to outside alligned.
> 
> What do you mean by that? @enslaved2die
@logo4poop

ignore that, doenst work like what i imagined, but still I dont think these sharp angles are good for a sine wave.
I think it can work if each hill and valley of the wave are seperate shapes, than you can say that the outline should be outside of the path (dont know which programm you use, but every vector programm has this option).
You already have the line so you can hide the shape bottom line
Something like this: 
![image](https://user-images.githubusercontent.com/25615199/124800116-90d4a000-df55-11eb-80b0-5676519355af.png)
repeat it for the valleys and youre good to go :)

I hope that makes it clear :D

**Comment by l0go** [comment]
> > > Try changing the outline from middle alligned to outside alligned.
> > 
> > 
> > What do you mean by that? @enslaved2die
> > @logo4poop
> 
> ignore that, doenst work like what i imagined, but still I dont think these sharp angles are good for a sine wave.
> I think it can work if each hill and valley of the wave are seperate shapes, than you can say that the outline should be outside of the path (dont know which programm you use, but every vector programm has this option).
> You already have the line so you can hide the shape bottom line
> Something like this:
> ![image](https://user-images.githubusercontent.com/25615199/124800116-90d4a000-df55-11eb-80b0-5676519355af.png)
> repeat it for the valleys and youre good to go :)
> 
> I hope that makes it clear :D

Thanks,
I am currently using Inkscape. Currently each of the hills are separate and are shaped like the image below similar to your example.
![image](https://user-images.githubusercontent.com/24994565/124801000-50a8f980-df24-11eb-8f76-3db1a5d7af06.png)

**Comment by enslaved2die** [comment]
@logo4poop I see. If these are shapes with a outline or shape with a fill.
you need a closed path with a outline and thany you should set the outline to outside instead of the default middle position.
In the picture it looks like you "expanded" your path to be a full shape, so the outline was converted to be a new path. Right?

Middle:
![image](https://user-images.githubusercontent.com/25615199/124801777-83201a00-df57-11eb-8bc3-91dbcad99039.png)
Outside:
![image](https://user-images.githubusercontent.com/25615199/124801820-90d59f80-df57-11eb-8861-737a34c6ea89.png)

The thickness of the outline is colliding with itself so this is why you get these sharp corners

**Comment by enslaved2die** [comment]
> Love this. Just one thing, the "TY" in Tenacity are a bit too close.

I agree.
Im not happy with the font.

First solution, get rid of the ugly small gap:
![image](https://user-images.githubusercontent.com/25615199/124802436-40ab0d00-df58-11eb-8a81-6570d44e9ec0.png)

Second solution, increase the gap (not my favourite it feels weird:
![image](https://user-images.githubusercontent.com/25615199/124802551-633d2600-df58-11eb-8224-4a16f94ddd2c.png)

Third soluton: Find a new font :D

But its nice here, were openly discussing a new logo and improving each others ideas

**Comment by KalitoWolf** [comment]
Here's my more modern take on the logo:

<img width="640" alt="tenacity" src="https://user-images.githubusercontent.com/29496004/124803405-5a991f80-df59-11eb-9415-1346a623290a.png">

**Comment by enslaved2die** [comment]
> Here's my more modern take on the logo:
> 
> <img alt="tenacity" width="640" src="https://user-images.githubusercontent.com/29496004/124803405-5a991f80-df59-11eb-9415-1346a623290a.png">

beautiful font, which one is it? 
I think the stem of the T inside the headphones can loose a few pounds to normalise the line thickness of the logo a bit. But overall, nice one.

I would say decrease the roundness of the logo to be already in line with the apple mac os big sur icon guidelines ^^

**Comment by zadcha** [comment]
Unfortunally, TENA is "Intimates Overnight Underwear" brand...

:\

**Comment by j0lol** [comment]
but the name is tenacity, not tena

**Comment by ghost** [comment]
> ![image](https://user-images.githubusercontent.com/72892531/124641990-33721d80-de87-11eb-84c3-c993699aad1c.png)
> ![image](https://user-images.githubusercontent.com/72892531/124642026-3f5ddf80-de87-11eb-9c25-e6f0a1376e25.png)
> 
> I need some opinions, does this look 💩 or alright for now?
> I will attach files if it is usable.

the Audio Spectrum reminds me somehow of "SS"

Not bad I like it, but the fork well.. nah.. and the Audio Spectrum should be redesigned if you ask me.

**Comment by akleja** [comment]
Here is my (initial) attempt:
It is inspired by square waves, spectrograms and skylines
![tenacity2_alt2](https://user-images.githubusercontent.com/49785979/124846227-a7e8b180-df98-11eb-9427-25d7c27f76a0.png)

**Comment by ajayyy** [comment]
Replying on issues is not very good, so let's move these to a discussion. Then, we can have proper threaded replies: https://github.com/tenacityteam/tenacity/discussions/148
