### ISSUE TITLE
Add Toolbar Edit Mode

### ISSUE THREAD

**Issue by abb128** [tenacityteam/tenacity-legacy#122]
Currently, the UI looks very cluttered. There is a lot of visual information to take in. As a first step to reduce the visual clutter, I think it might be a good idea to add a toggleable toolbar edit mode.

![image](https://user-images.githubusercontent.com/65567823/124729067-cd35db00-df18-11eb-8702-3477f9b332ae.png)

Disabling edit mode would hide these grabbers that appear to the left of every toolbar, and also the resizers that appear to the right of some toolbars:
![image](https://user-images.githubusercontent.com/65567823/124729290-f9e9f280-df18-11eb-8cd4-ccd0cbb37ce8.png)

On undocked toolbars, the grabbers should continue to appear because there is otherwise no way to drag the windows around. However, maybe docking them back to the main window should be prevented if edit mode is not enabled?

I think most people aren't customizing their toolbar layout while actively editing audio, so being able to hide these would not only make the UI look nicer, but also eliminate the chance of accidentally messing up the toolbar layout with a misclick.

And if some people are customizing their toolbar layout while actively editing audio, then they can just leave edit mode enabled.

**Comment by peepo5** [comment]
I agree with this one. Maybe View>Toggle Editable Toolbar

**Comment by fitojb** [comment]
As a further enhancement, I suggest renaming the “Edit mode” option to “Lock toolbars”, which is much more straight-forward.
