### ISSUE TITLE
Manage localization with Weblate

### ISSUE THREAD

**Issue by fitojb** [tenacityteam/tenacity-legacy#125]
To ease the updating of translations, I suggest using Weblate, either its SaaS ("Hosted") instance or a dedicated server install.

**Comment by peepo5** [comment]
I have seen this used in other projects before, what language options does tenacity have currently?

**Comment by emabrey** [comment]
I have created the Weblate project here:

https://hosted.weblate.org/projects/tenacity/

I am still in the process of setting everything up though.

**Comment by emabrey** [comment]
Currently weblate is processing everything in.

New link is https://hosted.weblate.org/projects/tenacity/tenacity.

I need to make sure that the changes I've made to enable weblate aren't causing any issues, but once I do, I plan to make a PR and merge the changes into master and point weblate to a permanent weblate-branch that we can use to have translations written into the repo. That way a mistake on weblate doesn't instantly pwn the master branch, we still have to manually bring in the changes to the master from the weblate branch.

I am also working on getting weblate out of the libre trial period and getting the project approved for a permanent gratis license for weblate.

**Comment by DimitarSamarov07** [comment]
Maybe mark this as resolved?
