### ISSUE TITLE
Remove "audacity" from CMake option names

### ISSUE THREAD

**Issue by Be-ing** [tenacityteam/tenacity-legacy#127]
The CMake scripts prefix build options with `audacity_`. I don't think this prefixing is necessary at all. If others disagree, then it should be replaced with the new project name.

**Comment by Conan-Kudo** [comment]
Yeah, dropping the project name prefix makes sense. It's not something I typically see in CMake projects unless they're intended to be nested in other projects (which Tenacity is not).
