### ISSUE TITLE
tenacityaudio.org is hard to read ( Dark on Dark )

### ISSUE THREAD

**Issue by JYamihud** [tenacityteam/tenacity-legacy#135]
The site is hard to read. The text is dark on a dark background. Using GNU IceCat browser.

**Comment by RoaddogLabs** [comment]
Safari on Monterey beta and Big Sur appears readable with no dark mode.

**Comment by fossdd** [comment]
> The site is hard to read. The test is dark on a dark background. Using GNU IceCat browser.

Can you show a Screenshot?

On mine browsers (qutebrowser (Blink), epiphany (WebKit), librewolf (Gecko)) and all is dark on white

**Comment by BeetMacol** [comment]
It's dark on white on Firefox. Check if you were using any additional extensions that could modify the looks of the website.

**Comment by JYamihud** [comment]
![image](https://user-images.githubusercontent.com/27649397/124812960-f54f2980-df6c-11eb-9983-9e4afc1c0654.png)

**Comment by JYamihud** [comment]
Maybe adding a white background could solve it?

**Comment by BeetMacol** [comment]
Oh, I see now, the website has no background color and your browser uses the gray color by default (most browsers use white instead).  
Also it is worth to note that the trend this days is to create dark themed websites, and I would love a light on dark one for tenacity.

**Comment by nbsp** [comment]
> Oh, I see now, the website has no background color and your browser uses the gray color by default (most browsers use white instead).

That's probably the problem. I'll add a manual background.

> Also it is worth to note that the trend this days is to create dark themed websites, and I would love a light on dark one for tenacity.

Dark Reader seems to handle the website fine, for now.

**Comment by nbsp** [comment]
Should be updated now.

**Comment by JYamihud** [comment]
works fine
