### ISSUE TITLE
Is support for ASIO compile still included in this build going forward?

### ISSUE THREAD

**Issue by HalfNote5** [tenacityteam/tenacity-legacy#14]
The question is pretty much in the title. You'll be continuing ASIO build support in the code going forward, right? 

Thanks! = )

**Comment by emabrey** [comment]
There are currently no plans to drop ASIO support to my knowledge, but I believe we aren't in a position yet to make definitive statement about that. I would personally **not** want to drop support for any feature unless it was somehow unavoidable. I know ASIO is the primary low-latency option and as a result I would personally consider it a very high priority, but I can't make an ongoing commitment for the project by myself. We need to get a more stable system for managing the project setup before it would be appropriate to definitely answer your question yes or no. However, if somehow ASIO support is broken at any point, definitely submit an issue and it will be investigated as a potential bug.

**Comment by HalfNote5** [comment]
Glad to hear it. We use Audacity in our studio a lot due to the ease with which you can trim very long audio files (highlight. Hit delete. Yay!) and spot-treat audio without a lot of hoopla (highlight. Click effect. Yay!)   Not a lot of other DAWs are anywhere near this fast. 

ASIO provides the very important function of letting us record more than 2 channels at once. Most of the time we're capturing a minimum of 3. Usually 5.

**Comment by Be-ing** [comment]
I have a pending PR rewriting PortAudio's CMake build system which adds an option to automatically download the ASIO SDK, making it easy to build: https://github.com/PortAudio/portaudio/pull/461

**Comment by HalfNote5** [comment]
> 
> 
> I have a pending PR rewriting PortAudio's CMake build system which adds an option to automatically download the ASIO SDK, making it easy to build: [PortAudio/portaudio#461](https://github.com/PortAudio/portaudio/pull/461)

NICE! That'll make life easy! I'll keep an eye on it.

**Comment by Be-ing** [comment]
@HalfNote5 if you could test my upstream PortAudio PR on Windows, make sure it builds, and make sure it links with another program (not Audacity or Tenacity because of #96) such as Mixxx, that would help move it along.

**Comment by HumbleDeer** [comment]
> Glad to hear it. We use Audacity in our studio a lot due to the ease with which you can trim very long audio files (highlight. Hit delete. Yay!) and spot-treat audio without a lot of hoopla (highlight. Click effect. Yay!) Not a lot of other DAWs are anywhere near this fast.
> 
> ASIO provides the very important function of letting us record more than 2 channels at once. Most of the time we're capturing a minimum of 3. Usually 5.

I use it for this exact purposes in my mastering studio too. But lately WASAPI with a switch has been doing well too!
