### ISSUE TITLE
Source code for website missing

### ISSUE THREAD

**Issue by falkTX** [tenacityteam/tenacity-legacy#140]
Just a reminder that we need to publish the website source code.

I wanted to suggest some changes (adaptive css for dark/light mode) but there is no place to send patches to right now.

Please keep this ticket open until there is a public issue tracker (either here on github or sr.ht) of the website where we can track and submit changes.
Thanks

**Comment by HumbleDeer** [comment]
+1 for this.
I'd like to contribute to some style stuff myself. Tenacity deserves a unique look!

**Comment by Sciss** [comment]
I assume it's a generated static site - then probably a good place would be a separate repository under the organisation? e.g. tenacityteam/tenacityaudio.org

**Comment by unbeatable-101** [comment]
> I assume it's a generated static site - then probably a good place would be a separate repository under the organisation? e.g. tenacityteam/tenacityaudio.org

I agree

Also the [repo](https://git.sr.ht/~tenacity/tenacity) listed on the site is out of date.

**Comment by BeetMacol** [comment]
Yeah I was looking for the source code too. Currently the website is most likely a single HTML file with no more than 50 lines and it would be cool to be able to help expand it.  
In my opinion moving to a Node.js framework may be a unavoidable at some point and if we want a bigger modern website for the project, doing it as early as now (when there's not much to port) is not a bad idea in my opinion. I suggest Nuxt.js/Vue.

**Comment by falkTX** [comment]
I would be against that. Simple files are easy to code and maintain and host.
We do not need fanciness for the website, it just has to be an entry point with various links, what else is needed anyway?
Maybe 1 or 2 screenshots, but even those can be made to "zoom in" without any JS like it is for now.

**Comment by HumbleDeer** [comment]
The build process is all handled by GitHub, so that's another plus.

**Comment by BeetMacol** [comment]
> We do not need fanciness for the website, it just has to be an entry point with various links, what else is needed anyway?

Change logs, releases, announcements, links, some about/information pages, screenshots are stuff that may be needed if the project is going to get serious.

**Comment by falkTX** [comment]
Sure, but that doesnt require a nodejs framework.
Creating raw HTML for posts and news sucks, so maybe something in between can be used (markdown to html site content generator, for example)

**Comment by Semisol** [comment]
> Sure, but that doesnt require a nodejs framework.
> Creating raw HTML for posts and news sucks, so maybe something in between can be used (markdown to html site content generator, for example)

Jekyll or [Hugo](https://gohugo.io) can be used.

**Comment by nbsp** [comment]
The code for the website, and the website itself, are [hosted on sourcehut](https://git.sr.ht/~tenacity/tenacityaudio.org), as per our agreement with Drew. mirroring the repo to GitHub would make sense, maybe, but not for issue management or PRs.

(patches welcome on tenacity-dev)

As for the design: worse is better IMHO.

**Comment by falkTX** [comment]
You cannot disable PRs on GitHub though, so this will make it a bit weird if we go that route for the website...

**Comment by Songtech-0912** [comment]
While the website sources are (yet) to be available, why don't we collab on a Figma artboard? I'm a web designer and I think we can first settle the design in Figma (a web based UI design app) before we do any sort of actual coding.

**Comment by falkTX** [comment]
please not figma, that is a privacy nightmare like I have never seen one.
their privacy policy is a list of tracking methods.

**Comment by Songtech-0912** [comment]
@falkTX I understand your concerns. I am using a FOSS "fork" of Figma without tracking, and I can send the designs to everyone as SVGs so that we don't have to deal with those issues.

**Comment by falkTX** [comment]
Well in any case the website source has been published.
it lives at https://git.sr.ht/~tenacity/tenacityaudio.org

Feel free to open a separate ticket for other matters.

Depending on the outcome of #155 we will either make srht repo main and one in GH a mirror, or vice-versa or something else..
I will wait for a decision there before opening any needed tickets regarding mirroring.
