### ISSUE TITLE
Rewriting the AboutDialog to fit the new project.

### ISSUE THREAD

**Issue by ThatVillagerGuy** [tenacityteam/tenacity-legacy#141]
**Is your feature request related to a problem? Please describe.**
Right now the Tenacity AboutDialog is still the old Audacity one, it needs to be changed for rebranding.

**Describe the solution you'd like**
The AboutDialog should be reworked to fit the Tenacity project, with new content and links.

I have already started working on this and just want to have this out there, so we don't have multiple people working on the same thing at the same time again.

**Comment by fossdd** [comment]
Yes, good point!

**Comment by n0toose** [comment]
Resolved.
