### ISSUE TITLE
Add matrix link to tenacityaudio.org

### ISSUE THREAD

**Issue by unbeatable-101** [tenacityteam/tenacity-legacy#146]
```html
<p>
            <a href="https://git.sr.ht/~tenacity/tenacity">Repository</a> ·
            <a href="https://sr.ht/~tenacity/tenacity/lists">Mailing lists</a> ·
            <a href="https://web.libera.chat/gamja/?channels=tenacity">IRC</a> ·
            <a href="https://matrix.to/#/#tenacity:libera.chat">Matrix</a> ·
            <a href="https://git.sr.ht/~tenacity/tenacity/refs">Releases</a>
</p>
```

With the source not on github yet I’ll just put this here.

**Comment by fossdd** [comment]
Yes, a Matrix Link would nice. The team publishes soon their source code for the website and you can contribute with Pull Requests. (#140)

A GitHub link is, i guess, not planned cause sourcehut should be the primary platform.

**Comment by Semisol** [comment]
Sourcehut migration is currently not 100% decided on, so you know.

**Comment by fossdd** [comment]
> Sourcehut migration is currently not 100% decided on, so you know.

Yes, sure.

**Comment by nbsp** [comment]
The Matrix link is a bridge to IRC. I think it'd be weird to link it alongside the IRC link, seeing as it's the same channel, but adding a paragraph linking to mailing lists/IRC/Matrix would be fine.

**Comment by nbsp** [comment]
Closing as it's been added; please see the `tenacity-dev` mailing list.
