### ISSUE TITLE
CMake version?

### ISSUE THREAD

**Issue by Sciss** [tenacityteam/tenacity-legacy#15]
Hi there. build instructions say CMake 3.16 is needed, and that on Linux you'll most likely have it via package manager. Now I'm on Debian stable (Buster), and I get this:

> CMake 3.15 or higher is required.  You are running version 3.13.4

So first, should be clarified whether 3.15 (script) or 3.16 (readme) is needed. And any ideas how I install the newer version on Debian 10? (Yes, Debian 11 is soon released, so...). Thanks

**Comment by Sciss** [comment]
Ok, `CMakeLists.txt` explains:

```
# If you want built-in precompiled header support
# then make sure you have cmake 3.16 or higher.
```

So I guess the readme is ok. Still wonder what's the easiest to get a newer CMake version than I have.

**Comment by MarkaPola** [comment]
Have a look at [CMake download](https://cmake.org/download/).

**Comment by Sciss** [comment]
Thanks. I tried with the latest stable. The installation process is very user unfriendly AKA not documented. So here is how I managed:

Download and extract `cmake-3.20.5-linux-x86_64.tar.gz`. Then:

```

sudo apt remove cmake

sudo cp -rT ~/Downloads/cmake-3.20.5-linux-x86_64/bin/ /usr/local/bin/
sudo cp -r ~/Downloads/cmake-3.20.5-linux-x86_64/share /usr/local/
sudo mkdir /usr/local/doc
sudo cp -rT ~/Downloads/cmake-3.20.5-linux-x86_64/doc /usr/local/doc/
sudo cp -rT ~/Downloads/cmake-3.20.5-linux-x86_64/man/man1 /usr/local/man/man1/
sudo cp -rT ~/Downloads/cmake-3.20.5-linux-x86_64/man/man7 /usr/local/man/man7/
```
