### ISSUE TITLE
Add donation link(s)

### ISSUE THREAD

**Issue by ghost** [tenacityteam/tenacity-legacy#154]
**Is your feature request related to a problem? Please describe.**
The problem is #99 - I would like to help with that issue not becoming a win for haters, and the simplest way I can think of is to buy the rest of the team a coffee.

**Describe the solution you'd like**
I don't care, whatever fits you best.

**Describe alternatives you've considered**
Team-based systems such as opencollective.com seem like the fairest long-term approach, but I have no real preferences.

**Comment by fossdd** [comment]
Duplicate of https://github.com/tenacityteam/tenacity/issues/67. But thanks that so many people want to donate tenacity. The trolls have become less.

**Comment by Semisol** [comment]
We are planning this, check out #67 for details. Thanks for your interest.

**Comment by ghost** [comment]
I'll close this then as it's a dupe.

**Comment by emabrey** [comment]
I have setup an Open Source Collective based donation option. You can donate using the Github Sponsors feature and the money will be placed into the control of the Fiscal Host, which is the Open Source Collective. All expenditures will be public and require approval, that way donators know that their donations are being used appropriately.

The Open Source Collective for Tenacity is located [here](https://opencollective.com/tenacity).
Donations can be submitted there directly, or alternatively, you can [use the GitHub sponsors feature](https://github.com/sponsors/tenacityteam).

Some of our developers are also independently offering donation options that DO NOT go to the project, but rather directly to the individual, myself included. I want to clarify that if you donate via our individual profile pages ([mine](https://github.com/sponsors/emabrey), for example) that DOES NOT GO TO THE PROJECT. There is nothing untoward about offering individual donation options, of course, but I do not want there to be any confusion.
