### ISSUE TITLE
Add hiDPI support for Windows build

### ISSUE THREAD

**Issue by NotAProton** [tenacityteam/tenacity-legacy#168]
- [x] I have read the specified guidelines for issues

**Describe the bug**
Main window is low DPI and blurry.

**To Reproduce**
1) Install Tenacity or pre-fork 
2) Run
3) Window is blurry

**Expected behavior**
UI should be scaled to match DPI of monitor

**Additional information (please complete the following information):**
 - OS:  Windows 10
 - Version: Latest (3.0.2)

**Additional context**
It is an old upstream problem, [this forum post](https://forum.audacityteam.org/viewtopic.php?t=102856) has the solution which can be applied as a post-install script in the existing Windows Inno Setup.

**Comment by caughtquick** [comment]
Could you post an image showing how exactly it is blurry?

**Comment by NotAProton** [comment]
![image](https://user-images.githubusercontent.com/81463636/124967704-58f75680-e042-11eb-89b2-4938bcd25586.png)

![image](https://user-images.githubusercontent.com/81463636/124967755-657baf00-e042-11eb-96ac-38a04c10c700.png)
Look how clear the title bar is

**Comment by emabrey** [comment]
Instead of using the windows override, why don't we just enable DPI support using the windows DLL? 

https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows
https://docs.microsoft.com/en-us/windows/win32/hidpi/dpi-awareness-context

**Comment by NotAProton** [comment]
[docs.wxwidgets.org/trunk/overview_high_dpi.html](https://docs.wxwidgets.org/trunk/overview_high_dpi.html)
[docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests)
[docs.microsoft.com/en-us/windows/win32/sbscs/manifest-file-schema](https://docs.microsoft.com/en-us/windows/win32/sbscs/manifest-file-schema)

I think what we need to do is add
` <ElementType name="dpiAware" />  `
 ` <ElementType name="dpiAwareness" />`
to https://github.com/tenacityteam/tenacity/blob/master/win/Tenacity.exe.manifest

**Comment by fossdd** [comment]
> I think what we need to do is add
> `<ElementType name="dpiAware" /> `
> ` <ElementType name="dpiAwareness" />`
> to https://github.com/tenacityteam/tenacity/blob/master/win/Tenacity.exe.manifest

No, i guess that's the specification for the manifest. I try to open a PR.

**Comment by Semisol** [comment]
Unpinned, PR was merged
