### ISSUE TITLE
conan uses an audacity repository

### ISSUE THREAD

**Issue by adrianheine** [tenacityteam/tenacity-legacy#169]
conan currently uses an audacity repository:

https://github.com/tenacityteam/tenacity/blob/098a0225e1aff0c12958ccd5f960cb8925e58c5b/cmake-proxies/cmake-modules/AudacityDependencies.cmake#L4-L7

Tenacity should not depend on audacity infrastructure.

**Comment by RoaddogLabs** [comment]
See #69

**Comment by emabrey** [comment]
Thank you, I agree. I'm going to close as a duplicate though to keep things clean on the issues page. Please join the discussion over at #69
