### ISSUE TITLE
Unable to complete installation on Linux

### ISSUE THREAD

**Issue by lucyferu** [tenacityteam/tenacity-legacy#172]
**Describe the bug**
When reaching the last step for building Tenacity
`sudo make install`
I encounter this error
`make: *** No rule to make target 'install'. Stop.`

**To Reproduce**
1. Go to '[Building Tenacity page](https://github.com/tenacityteam/tenacity/blob/master/BUILDING.md)'
2. Follow the steps for  'Linux'

**Expected behavior**
I guess Tenacity should install?

**Additional information (please complete the following information):**
 -   Kernel: 5.4.0-72-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 
  Desktop: MATE 1.24.0 Distro: Linux Mint 20.1 Ulyssa 
  base: Ubuntu 20.04 focal

**Comment by falkTX** [comment]
on a similar topic, you should not be installing tenacity since the original audacity builds several libraries which are required for use. installing those libraries can create conflicts with the rest of the system, so it is best used locally and not system-wide at this point.

**Comment by lucyferu** [comment]
> on a similar topic, you should not be installing tenacity since the original audacity builds several libraries which are required for use. installing those libraries can create conflicts with the rest of the system, so it is best used locally and not system-wide at this point.

So, should I uninstall audacity first in order to avoid the conflict?

**Comment by falkTX** [comment]
That is not what I mean. It is likely the best to not install tenacity right now.
Build it and run the binaries from the build dir, but dont try to install it system-wide.

**Comment by lucyferu** [comment]
> That is not what I mean. It is likely the best to not install tenacity right now.
> Build it and tun the binaries from the build dir, but dont try to install it system-wide.

Ah, ok, fair enough.
I'll build and wait then. 😛
