### ISSUE TITLE
Create wikipedia page 

### ISSUE THREAD

**Issue by leshinskii** [tenacityteam/tenacity-legacy#185]
I propose to create a Wikipedia page for Tenacity so that everyone quickly learns about the new fork and attracts more people to develop it.

**Comment by Semisol** [comment]
We are not well established and don't think need that much attention currently.

**Comment by leshinskii** [comment]
possibly
then it's for the future

**Comment by Semisol** [comment]
I consider this invalid due to it being not a bug or feature request.

**Comment by fossdd** [comment]
Also it isn't a good feeling if you do a wikipedia artcile for yourself. So maybe should that other people do.

**Comment by fitojb** [comment]
https://en.wikipedia.org/wiki/Wikipedia:Conflict_of_interest

**Comment by fossdd** [comment]
Ah yes, that exactly that what I want to describe.

**Comment by TollyH** [comment]
Also worth noting: https://en.wikipedia.org/wiki/Wikipedia:Notability_(software)
