### ISSUE TITLE
Team/ organization members

### ISSUE THREAD

**Issue by domsson** [tenacityteam/tenacity-legacy#19]
(not sure this is the right place - if not, please let me know where this should go)

I think it is the right approach to have a GitHub team/organization for this project. However, I have one question and one suggestion:

 - Question: what will be the process to select the members?
 - Suggestion: offer the original members of the Audacity project to become members of this fork.

**Comment by cookiengineer** [comment]
After the vote for the project name has ended, I'll create the GitHub organization for this project and move the repository there. Then we have to decide for a lot of organizational things; like

- a code of conduct (which I'm in favor of)
- organizational structure
- how to vote on membership (trust through accepted pull requests, maybe?)

... among other things like website, potential (re-)design, etc.

As this repository is only two days old, we still need some time to organize ourselves, so please bear with me here.

I also would offer the original members of the Audacity project membership (I'm in favor when that's being decided or voted upon), but I would rather be cautious about giving Muse Group members unrestricted access. I'm not sure whether a democratic approach can work here as this fork is very new.

But given that a lot of the previous developers gave away their rights in favor of Muse Group's policy choices... I'm not sure what to do here.

Maybe the Code of Conduct should also include Ethical Values like Respect for Privacy and Self-Determination etc?

**Comment by AnErrupTion** [comment]
I'm willing to be a maintainer of the project, mostly full time.

**Comment by Sciss** [comment]
CoC example: https://scala-lang.org/conduct/ (at the end is a list of sources from which it was inspired, including popular ones like  [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct/))

**Comment by EchedelleLR** [comment]
Hi @cookiengineer I take this issue as a question to know how the discussions will be hold.

The Audacium fork from @AnErrupTion uses Discord mainly which is bridged to a Matrix room.

However, I am telling you this because I consider that the promotion and use of nonFree software is not the way to go, and more existing viable replacements such as Matrix itself to which a Space or Community could be created with rooms, not promoting nonFree platforms.

Telling this, I understand that using GitHub is also an issue in this topic which I would prefer to touch when things are set as I could still understand it given the current situation of Audacity.

**Comment by ajayyy** [comment]
@EchedeyLR That has already been discussed in https://github.com/cookiengineer/audacity/issues/7#issuecomment-873775452

**Comment by EchedelleLR** [comment]
@ajayyy Thank you for pointing me to it and sorry for not searching deep enough, making you lose a bit of time with it.

Edited because of your reaction: I was reading all of this in mobile and didn't scroll enough to see the issue with the title focused on it.

**Comment by doctormo** [comment]
I'm willing to host a BigBlueButton video chat for people to join, if you'd like to talk about the issues of governance. I can share my experience as a member of the inkscape board, and can give you pointers to the SFC or other resources if you're interested. Let me know.

**Comment by caughtquick** [comment]
We could host a website on vercel?   It's FOSS and free with more free features for open source projects. Could definitely be a viable option if we don't want to selfhost the website

**Comment by BenBE** [comment]
> I'm willing to host a BigBlueButton video chat for people to join, if you'd like to talk about the issues of governance. I can share my experience as a member of the inkscape board, and can give you pointers to the SFC or other resources if you're interested. Let me know.

To cut it short: BBB is a tire fire:
See https://github.com/bigbluebutton/bigbluebutton/issues/8861 for details if you like …

For the actual topic: I think developers who signed off their rights to Muse Group should not be allowed into the core team. As goes for members of Muse Group or their associates.

Apart from these restrictions: Everyone with a continuous, solid activity helping the project (be it gardening the tracker, reviewing PRs, writing code, …) should be able to join the core team *on invitation from the core developers*. Such proposals should be made public and be open for the community to object on important grounds (final decision lies with the core dev team).

Regarding a code of conduct: Better walk the walk than talk the talk. My personal opinion on CoCs is that they are regularly abused against minorities or people that raise uncomfortable topics and discussions. You still can usually do the same things you can do with a CoC even without one, but having one becomes a liability as it forces you to apply its rules even in situations when it will hurt the project. Think **REALLY** careful about having a CoC.

Last but not least: I'm in favour of having a contribution guide document detailing core (ethical) values that every contributor is required to adhere to. Also having a CLA (I know this is kinda burnt term right now) doesn't hurt, as it allows for a simplified representation in copyright matters of contributors. Have a look at e.g. the CLA by the OpenSSL foundation for details.

**Comment by EchedelleLR** [comment]
To be taken into account:
- https://drewdevault.com/2018/10/05/Dont-sign-a-CLA.html
- https://drewdevault.com/2021/04/12/DCO.html

**Comment by Sciss** [comment]
BBB works in a browser, I don't see why installation problems on Debian speak against it? Or do I understand something wrong?'

I think almost all larger civilised projects have a CoC by now, for good reasons. It's a clear signal that certain behaviour is not tolerated, and an invitation to contributors who would not feel welcome in a project that says moderation is hands-off.

I wouldn't necessary be against a CLA. I use one for all my personal projects, simply to avoid that I run into legal problems with my projects in the future. I acknowledge that there are good arguments against using a CLA.

**Comment by Be-ing** [comment]
> For the actual topic: I think developers who signed off their rights to Muse Group should not be allowed into the core team. As goes for members of Muse Group or their associates.

I agree.

> Everyone with a continuous, solid activity helping the project (be it gardening the tracker, reviewing PRs, writing code, …) should be able to join the core team on invitation from the core developers.

Yes, calling people team members before anyone has done anything for the project is premature. I also think discussing formal organization is premature at this point.

> My personal opinion on CoCs is that they are regularly abused against minorities or people that raise uncomfortable topics and discussions.

My personal opinion is that merely having a code of conduct is an effective way to proactively repel people that would be harmful to the community.

**Comment by BenBE** [comment]
> BBB works in a browser, I don't see why installation problems on Debian speak against it? Or do I understand something wrong?'

It's codebase is a mess (much more so than even the one in this fork is). Even so far even that several Debian developers gave up trying to package it after receiving quite hostile comments from the current maintainers. BBB in its current governance is not a FLOSS project you should be advocating for. Also they are rewriting configurations on the system so much that it breaks any attempts to get those under control or even have a sane point of control over your system. 

> I think almost all larger civilised projects have a CoC by now, for good reasons. It's a clear signal that certain behaviour is not tolerated, and an invitation to contributors who would not feel welcome in a project that says moderation is hands-off.

It's actually a minority of projects. And not having a CoC doesn't mean Robert's Rules or netiquette does not apply to your project. Not having a CoC is just a less formal way of showing the way out to people who misbehave.

**Comment by emabrey** [comment]
> But given that a lot of the previous developers gave away their rights in favor of Muse Group's policy choices... I'm not sure what to do here.
> 
> Maybe the Code of Conduct should also include Ethical Values like Respect for Privacy and Self-Determination etc?

I think we can offer non-employee contributor status/org access. But there is a lot of risk associated with giving employees access, not to mention to issues of license and code ownership. What happens if a hypothetical contributor from Muse Group makes a real quick commit to master (no PR) to merge a license change or something from the audacity/audacity repo?

As far as contributors to Audacity who are at arms-length from the employment issue, there seems to me to be obvious reason why they can't be allowed a chance to acquire trust. Otherwise, we run the risk of cutting off a valuable source of people who are enthusiastic about open-source contributions to a software niche like this one. A lack of contributors can kill a project fast, so if we are going to have a non-permissive approach it needs to be as light as possible. I think perhaps a policy to block PRs which appear to violate license provisions or the trademark law is the best we could do without having a CLA, which of course we aren't going to have. Ultimately, if we do outright ban it, we need to make sure we can support the needed reasonable number of contributors.

**Comment by doctormo** [comment]
I mostly disagree with BenBE. Not about BigBlueButton, I don't package it, I just use it and it's very solid once installed from my experience. But the bit about codes of conduct. They're pretty much vital to creating an authoritative source, they don't just say what isn't allowed, they also say what the procedure is for grievances. This project will likely get big, and it'll need a set of rules that say how people with upset feelings can bring their problems up to the right people in the right way.

**Comment by Sciss** [comment]
> What happens if a hypothetical contributor from Muse Group makes a real quick commit to master (no PR) to merge a license change or something from the audacity/audacity repo?

Well, that could always be undone? Probably it's wise to say that all changes should go through a PR, and that there should always be a second pair of eyes - ideally making a review, or for more trivial commits just giving thumbs up, before anything is merged.

**Comment by BenBE** [comment]
> I mostly disagree with BenBE. Not about BigBlueButton, I don't package it, I just use it and it's very solid once installed from my experience.

From a UX base BBB is fine (but I still prefer Jitsi Meet), but from the admin side. You simply don't want a mess of various scripts fighting over what ends up in your system config as BBB does (apart from the vendoring stuff). But that's OT here.

> But the bit about codes of conduct. They're pretty much vital to creating an authoritative source, they don't just say what isn't allowed, they also say what the procedure is for grievances. This project will likely get big, and it'll need a set of rules that say how people with upset feelings can bring their problems up to the right people in the right way.

I'm not generally agains having a CoC, just cautioning that you should live one first and just have the CoC based on what the lived rules in the community are anyway. A CoC doesn't have any bite when most of the community ignore it; it's simply not enforceable. When the community agrees on not tolerating trolls it just doesn't need to be written: It just takes a set of moderators that enforce this and a community keeping their back. What a CoC can be helpful at is bringing people up to speed on the unwritten rules in the community, but that's usually something that can be addressed in the contribution guidelines too (yes: writing issues is a FLOSS contribution too).

**Comment by Semisol** [comment]
I could preferably allow access to my Jitsi Meet instance if needed.

**Comment by abrolag** [comment]
I'm heavily involved with a soft-synth but would like to help where I can. Reasonably OK C, and so-so C++
Probably best at cleanups and housekeeping.

**Comment by ghost** [comment]
>  codes of conduct. They're pretty much vital

Remember before anybody used these when everything was just fine? It's still just fine.

**Comment by falkTX** [comment]
> > codes of conduct. They're pretty much vital
> 
> Remember before anybody used these when everything was just fine? It's still just fine.

I remember my friends telling me they hated the toxic attitude in IT fields and gave up on one of their passions because of it. You just had to be a little different to not be welcome anymore.

**Comment by ghost** [comment]
> You just had to be a little different to not be welcome anymore.

Like people who don't want a CoC

**Comment by falkTX** [comment]
> > You just had to be a little different to not be welcome anymore.
> 
> Like people who don't want a CoC

Have to wonder why... :thinking: 

The CoC is not for you, is for others.

**Comment by awslabspl** [comment]
Im also willing to be maintaner.

**Comment by ghost** [comment]
> The CoC is not for you, is for others.

Because only they should be welcome?

**Comment by BenBE** [comment]
Paper is patient. So is a CoC. You can have the 10 Commandments and still initiate a genocide.
If a community is toxic this doesn't magically change just because they have a CoC.

I think the more constructive way forward here is write a note in the contribution guidelines, of what you expect people interacting with the community to do. And when those expectations become elaborate enough to warrant their own document, then so be it.

Let's start with the following contribution guidelines:
```
Be excellent to each other. No trolling. No harassing.
```
See? Done.

**Comment by fossdd** [comment]
I would also help this project by maintain it. And I have a question: Who are the current organisation members? It's difficult to see who of the project is can be trusted and who probably wants to troll us. Of course I respect the privacy and if someone doesn't want to be shown as member I can understand it. But yeah as user it's difficult.

**Comment by Semisol** [comment]
> I would also like to help this project by "co-maintain" the project. And I have a question: Who are the current organisation members? It's difficult to see who of the project is can be trusted and who probably wants to troll us. Of course I respect the privacy and if someone doesn't want to be shown as member I can understand it. But yeah as user it's difficult.

There are 2-5 admins.

**Comment by caughtquick** [comment]
> I would also like to help this project by "co-maintain" the project. And I have a question: Who are the current organisation members? It's difficult to see who of the project is can be trusted and who probably wants to troll us. Of course I respect the privacy and if someone doesn't want to be shown as member I can understand it. But yeah as user it's difficult.

That's the decision of each maintainer, hopefully soon everyone is comfortable being public

**Comment by bl-ue** [comment]
For reference, the current maintainers (or at least, people with write access to this repo) are:

- @SFR-git
- @Sciss
- @Semisol
- @ajayyy
- @caughtquick
- @cookiengineer
- @emabrey
- @falkTX
- @panos

Cool, the community is already growing! I'd love to seem more.

**Comment by fossdd** [comment]
Can you remove that please? The members want to be anonymous and doesn't regonised directly.

**Comment by bl-ue** [comment]
Oh, I'm very sorry about that...

I just deleted the entire comment for now.

**Comment by bl-ue** [comment]
It's farely trivial to determine everyone who has write access to a repository though, so if it's very critical to you to keep it a secret, I'd recommend not being a part of it at all... 😖

**Comment by Semisol** [comment]
> It's farely trivial to determine everyone who has write access to a repository though, so if it's very critical to you to keep it a secret, I'd recommend not being a part of it at all... 😖

Well we know it is easy but some people might not want to be shown on a public list.

**Comment by awslabspl** [comment]
> Well we know it is easy but some people might not want to be shown on a public list.

Im not sure if this can be done. GH keeps contributors list public AFAIK.......

**Comment by Semisol** [comment]
> > Well we know it is easy but some people might not want to be shown on a public list.
> 
> Im not sure if this can be done. GH keeps contributors list public AFAIK.......

Contributors != repo access

**Comment by awslabspl** [comment]
> Contributors != repo access

yes and no. Depends on the scope of definitions.

**Comment by fossdd** [comment]
> > Contributors != repo access
> 
> yes and no. Depends on the scope of definitions.

We mean github's git contributors list: https://github.com/tenacityteam/tenacity/graphs/contributors

**Comment by Pythone** [comment]
# I am willing to maintain this project.
## we all depend on this fork.
### Why I qualify: I am ready to learn + I have art skills. I could help make new themes, prioritize which features we need to currently work on, plus I want to help remove telemetry. I am co-leader of the OpenSuspect art team. I will dedicate myself to this project

**Comment by emabrey** [comment]
I am willing to be the maintainer if the rest of the community/contributors support that idea.

**Comment by DimitarSamarov07** [comment]
I am willing to help with translations and translation management and be a maintainer if you and the rest of the community support this idea. I have quite a lot of experience with weblate, both from a management and translator perspective. I can help correct the outdated strings in English and replace all the Audacity mentions as needed. Aside from that I have quite a lot of experience with coding and handling issues and pull requests. Currently working on translating all the strings to my native language(Bulgarian).

**Comment by falkTX** [comment]
I am seeing myself in a more of a "consultant" type of thing, surely willing to help.

**Comment by Sciss** [comment]
Dito. I'm happy to help and advise, but cannot promise how much time I can devote. I'm experienced in audio programming, and I can read C, C++ more or less, but I write close to no C, so will probably not contribute much code.

**Comment by Be-ing** [comment]
I'm happy to help get this project off the ground but I don't anticipate doing any major feature development myself.

**Comment by Semisol** [comment]
> Dito. I'm happy to help and advise, but cannot promise how much time I can devote. I'm experienced in audio programming, and I can read C, C++ more or less, but I write close to no C, so will probably not contribute much code.

No worries, you don't have to devote too much. Every contribution big and small counts.

Also for the people who want to be maintainer: You can open a PR/issue right now if you want to contribute! I will obviously contact people that are interested here, but you need to participate first ;)

**Comment by Pythone** [comment]
> # I am willing to maintain this project.
> ## we all depend on this fork.
> ### Why I qualify: I am ready to learn + I have art skills. I could help make new themes, prioritize which features we need to currently work on, plus I want to help remove telemetry. I am co-leader of the OpenSuspect art team. I will dedicate myself to this project

My goals right now:
- redesign the main theme
- be at peace with other forks (friends, not enemies)
- Make a website different from SourceHut's
- pick or design a good logo
- make it look more professional
I respect your decision and I will honor it.

**Comment by Pythone** [comment]
# I just want to assist any way I can

**Comment by Be-ing** [comment]
@Pythone making a distinctive and nice looking design for Tenacity would be a great contribution!

**Comment by Pythone** [comment]
good

**Comment by Pythone** [comment]
new idea:
- Now working on haiku port
-

**Comment by n0toose** [comment]
People who make a couple of contributions and participate in the community get invited to the organization and start off as people that can triage issues (as in approve/request changes in pull requests or close them) and get write access afterwards. However, some people accept different roles instead, such as moderating our issues or controlling other repositories in our organization.

You can find out more about the way we are internally structured [in the Teams section](https://github.com/orgs/tenacityteam/teams), although a considerable amount of participants has refrained from making their affiliation with Tenacity either because of the drama that surrounded the project in the past or because they don't want to take the responsibility of doing so without engaging themselves further.
