### ISSUE TITLE
Debian 10 build results in SegFault (AppImage or flatpak might help in the future)

### ISSUE THREAD

**Issue by RoyShapiro** [tenacityteam/tenacity-legacy#199]
- [x] I have read the specified guidelines for issues

**Describe the bug**
Building on Debian 10 Buster succeeds (provided cmake is updated to 3.15.2), but running results in a segfault.

**To Reproduce**
1. Go to https://github.com/tenacityteam/tenacity/blob/master/BUILDING.md and follow the instructions for building on Debian Linux until error regarding cmake version installed in encountered (3.13 vs a minimum of 3.15).
2. Update cmake manually to 3.15, following, for example, this guide: https://linuxhint.com/install-cmake-on-debian-10/
3. Verify that cmake is properly updated by running `cmake --version`.
4. Continue following build instructions until build is successful (albeit with a lot of deprecation warnings in the later half (after it searches for dependencies at about 60%).
5. Go to bin/Debug and run ./audacity as instructions direct.
6. Receive the following output (the app logo shows up and disappears during the process):
```ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
Expression 'alsa_snd_pcm_hw_params_set_buffer_size_near( pcm, hwParams, &alsaBufferFrames )' failed in '/home/roy/tenacity/tenacity/lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 923
Expression 'alsa_snd_pcm_hw_params_set_buffer_size_near( pcm, hwParams, &alsaBufferFrames )' failed in '/home/roy/tenacity/tenacity/lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 923
Expression 'alsa_snd_pcm_hw_params_set_buffer_size_near( pcm, hwParams, &alsaBufferFrames )' failed in '/home/toy/tenacity/tenacity/lib-src/portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c', line: 923
Cannot connect to server socket err = No such file or folder
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or folder
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_a52.c:823:(_snd_pcm_a52_open) a52 is only for playback
Segmentation fault
```

**Expected behavior**
Application starting and working properly.

**Screenshots**
None as the program doesn't launch after producing aforementioned output.

**Additional information (please complete the following information):**
 - OS: Debian 10 Buster (fully updated)
 - Version: current git master (c3eaa8650d4d7800e6f92e50836add5acf16304f)
 - USB Sound card: Focusrite Scarlett 2i2

**Additional context**
I do understand that Debian Stable is a very stale system and likely doesn't support a few required features, and Debian Testing is likely to produce better results. A flatpak or AppImage of the program are likely to resolve the issue by providing all required libraries.

**Comment by caughtquick** [comment]
I'm guessing this is due to the fact that tenacity is based on a newer audacity version than Debian supports and it doesn't support the libraries. We are in contact with the Debian maintainers (#90). A Flatpak and Appimage are both in the works. Since Debian is a slow moving distribution I doubt it will be work till the next Debian stable release. I'm also seeing if I can tackle a Docker container.

**Comment by Sciss** [comment]
Seems the same environment (Debian 10) and problem (same build operations and console output) as #17 - I'm closing it as duplicate.
