### ISSUE TITLE
Remove lib dirs and use submodules

### ISSUE THREAD

**Issue by nbsp** [tenacityteam/tenacity-legacy#200]
- [x] I have read the specified guidelines for issues

**Is your feature request related to a problem? Please describe.**
Audacity/Tenacity's `lib-src/` and `libraries/` are filled with outdated external libraries which for some reason are part of the repository.

**Describe the solution you'd like**
Following discussion on IRC, we should remove all of the libraries and instead use [git submodules](https://git-scm.com/docs/git-submodule).

**Additional context**
Also looping in @imachug.
This could, *and probably will*, break compatibilty with Audacity, but it's a necessary change.

**Comment by purplesyringa** [comment]
There are also many patches. Some are outdated and some were never reported to upstream, so we'll probably have to do that if we don't want to maintain lots of forks.

**Comment by nbsp** [comment]
Another thing we could do is export the patches as `.patch` files, store them in a `lib-patches/` directory, then automate `git am`ing them as part of a Makefile.

Still janky, but _less so_.

**Comment by fossdd** [comment]
> Another thing we could do is export the patches as `.patch` files, store them in a `lib-patches/` directory, then automate `git am`ing them as part of a Makefile.

Then we still have to maintain these patches, if the upstream changes a file we patch. That could be much..

**Comment by Be-ing** [comment]
Git submodules are annoying to work with and don't really solve the problem. Using a package manager is a much better solution: #177.

**Comment by purplesyringa** [comment]
By the way it would be great if you all joined #tenacity on IRC or some other group, because only now I find out that two groups of developers were working on the same problem without knowing about each other's work.

**Comment by Be-ing** [comment]
Fixed in #228
