### ISSUE TITLE
Publish 

### ISSUE THREAD

**Issue by hypermug1** [tenacityteam/tenacity-legacy#202]
- [x ] I have read the specified guidelines for issues

**Is your feature request related to a problem? Please describe.**
A current problem is that there is no download of the program. It requires building from source code. Less experienced users may not be able to do that.

**Describe the solution you'd like**
Place .exe, .AppImage, etc, in the Releases section

**Comment by nbsp** [comment]
There aren't any downloads because there's no release as of yet.

This is also not a bug or feature request: please read the guidelines.
