### ISSUE TITLE
"""edit""" of my response in #155 to be clear

### ISSUE THREAD

**Issue by kubo6472** [tenacityteam/tenacity-legacy#204]
can't edit so number 1 for me in #155

**Comment by Semisol** [comment]
Sorry, the counting has started and editing is not possible.

**Comment by kubo6472** [comment]
Is it clear then from my response that I posted in the main thread?

**Comment by Semisol** [comment]
Wdym? Your edits have not been counted, as the votes counted were at the time of the conversation being locked.

**Comment by kubo6472** [comment]
https://github.com/tenacityteam/tenacity/issues/155#issuecomment-877632085

If this wasn't counted as 1 then nvm. I didn't know at what exact time you started counting the votes, so your notice to clearly post a number hasn't got to me yet.

**Comment by Semisol** [comment]
I only counted explicit choices so it wasn't. Anyways if you have any more concerns reach me on Libera (Semisol) or Matrix (`@semisol:semisol.dev`)

**Comment by kubo6472** [comment]
> I only counted explicit choices so it wasn't. Anyways if you have any more concerns reach me on Libera (Semisol) or Matrix (`@semisol:semisol.dev`)

Aight, thank you
