### ISSUE TITLE
Privacy is not the only issue, let's address all of them

### ISSUE THREAD

**Issue by JYamihud** [tenacityteam/tenacity-legacy#208]
### Discussed in https://github.com/tenacityteam/tenacity/discussions/207

<div type='discussions-op-text'>

<sup>Originally posted by **JYamihud** July 10, 2021</sup>
Surveillance as in Telemetry that MuseGroup try to push on us, not realizing that people will f**k them and go, is a very big issue. Since the Snowden revelations it's a very strong argument of the Free Software. But it's not the only malware. And I don't want my Tenacity, where I gonna edit my songs and vocal recording to have any malware at all.

Malware types ( with links ):

 - [Addictions](https://www.gnu.org/proprietary/proprietary-addictions.html)
 - [Back Doors](https://www.gnu.org/proprietary/proprietary-back-doors.html)
 - [Censorship](https://www.gnu.org/proprietary/proprietary-censorship.html)
 - [Coverups](https://www.gnu.org/proprietary/proprietary-coverups.html)
 - [Deception](https://www.gnu.org/proprietary/proprietary-deception.html)
 - [Digital Restrictions Management](https://www.gnu.org/proprietary/proprietary-drm.html)
 - [Fraud](https://www.gnu.org/proprietary/proprietary-fraud.html)
 - [Incompatibility](https://www.gnu.org/proprietary/proprietary-incompatibility.html)
 - [Insecurity](https://www.gnu.org/proprietary/proprietary-insecurity.html)
 - [Interference](https://www.gnu.org/proprietary/proprietary-interference.html)
 - [Manipulation](https://www.gnu.org/proprietary/proprietary-manipulation.html)
 - [Obsolescence](https://www.gnu.org/proprietary/proprietary-obsolescence.html)
 - [Sabotage](https://www.gnu.org/proprietary/proprietary-sabotage.html)
 - [Subscriptions](https://www.gnu.org/proprietary/proprietary-subscriptions.html)
 - [Surveillance](https://www.gnu.org/proprietary/proprietary-surveillance.html)
 - [Tethers](https://www.gnu.org/proprietary/proprietary-tethers.html)

I excluded [Jails](https://www.gnu.org/proprietary/proprietary-jails.html) and [Tyrants](https://www.gnu.org/proprietary/proprietary-tyrants.html) since it's about hardware and Operating Systems and not about software on those systems. 

I suggest that we make a "Privacy Policy" of our own. But naming it something like "User Respect Policy". And stating in details how we are going to avoid all of the malware listed above.

Thoughts? </div>

**Comment by Sciss** [comment]
Please do not open an issue that is identical to the (broad) discussion. If individual approaches come out of the discussion, they can be tackled as focused issues.
