### ISSUE TITLE
Request for new logo

### ISSUE THREAD

**Issue by echometerain** [tenacityteam/tenacity-legacy#221]
The audacity logo is still used which has outdated design and a generic font. Request for the logo to be changed to something more modern and to replace "Audacity" with "Tenacity" in the splash. The audacity logo from the Papirus icon pack is a great place to start, however it would probably need to be modified to fit the color palette to whatever gets decided in https://github.com/tenacityteam/tenacity/issues/29

**Comment by bl-ue** [comment]
#149

**Comment by n0toose** [comment]
Currently being worked on.

**Comment by Pythone** [comment]
we already have a logo

**Comment by Semisol** [comment]
please do not necropost on old issues.
9 days ago we didn't have one. @Pythone
