### ISSUE TITLE
Update splash screen and icons

### ISSUE THREAD

**Issue by ghost** [tenacityteam/tenacity-legacy#223]
- [x] I have read the specified guidelines for issues

**Is your feature request related to a problem? Please describe.**
When I launched this app, I couldn't tell if it was Audacity or Tenacity.

**Describe the solution you'd like**
I would like it if the splash screen read "tenacity" and not audacity.

**Describe alternatives you've considered**
Replace text on splash screen with "tenacity".

**Additional context**
I am not asking you to rebrand, just change the splash screen, perhaps into [something like this](https://imgur.com/a/h2zyfF2).

**Comment by alkaris2** [comment]
Perhaps a more cleaner logo, drop the white background and have full image transparency, but full logo redesign wouldn't be such a bad idea, and a perfect opportunity for a complete redesign.

**Comment by unbeatable-101** [comment]
#149

**Comment by fossdd** [comment]
The files containing the Splash Screen images are actually here: [images/AudacityLogoWithName.xpm] and the dark one: [images/DarkAudacityLogoWithName.xpm].

It uses the old [X PixMap] format. So that is might a bit difficult.

[images/AudacityLogoWithName.xpm]: https://github.com/tenacityteam/tenacity/blob/master/images/AudacityLogoWithName.xpm
[images/DarkAudacityLogoWithName.xpm]: https://github.com/tenacityteam/tenacity/blob/master/images/DarkAudacityLogoWithName.xpm
[X PixMap]: https://en.wikipedia.org/wiki/X_PixMap

**Comment by ghost** [comment]
Proposal to replace images/AudacityLogoWithName.xpm with [this](https://pipe.miroware.io/60bd25ecab37f801c2e559a3/Tenacity/AudacityLogoWithName.xpm), and images/DarkAudacityLogoWithName.xpm with [this](https://pipe.miroware.io/60bd25ecab37f801c2e559a3/Tenacity/DarkAudacityLogoWithName.xpm) until y'all can decide which of the actually good logos (see #149) to run with.

**Comment by fossdd** [comment]
> Proposal to replace images/AudacityLogoWithName.xpm with [this](https://pipe.miroware.io/60bd25ecab37f801c2e559a3/Tenacity/AudacityLogoWithName.xpm), and images/DarkAudacityLogoWithName.xpm with [this](https://pipe.miroware.io/60bd25ecab37f801c2e559a3/Tenacity/DarkAudacityLogoWithName.xpm) until y'all can decide which of the actually good logos (see #149) to run with.

I think we should first wait unitl there is a logo in #149 and then change it directly. Yours is a bit basic and doesn't look nice.

I guess we should maybe re-design the Splash Screen as it become very old and there are other programs that makes it much better (for example GIMP or Krita).

If someone makes a patch with it, please rename the xpm files to tenacity and also rename here some urls and messages: https://github.com/tenacityteam/tenacity/blob/master/src/SplashDialog.cpp

**Comment by ghost** [comment]
I think I was just so tired of there being no original branding that I thought if I made the worst temporary measure possible, everyone would start working on a better one just so they could change it. This method actually has worked in the past.

**Comment by emabrey** [comment]
> 
> 
> Proposal to replace images/AudacityLogoWithName.xpm with [this](https://pipe.miroware.io/60bd25ecab37f801c2e559a3/Tenacity/AudacityLogoWithName.xpm), and images/DarkAudacityLogoWithName.xpm with [this](https://pipe.miroware.io/60bd25ecab37f801c2e559a3/Tenacity/DarkAudacityLogoWithName.xpm) until y'all can decide which of the actually good logos (see #149) to run with.

https://www.youtube.com/watch?v=YcR9k8o4I0w

**Comment by fossdd** [comment]
I work on that. I'll also direct update the icons.

**Comment by CHJ85** [comment]
I like the new logo and icon by @akleja and @Sosasees.
Looks great.

**Comment by RoaddogLabs** [comment]
The logo and icons look good.  Well done.

**Comment by fossdd** [comment]
Yup, added a PR for this: #303
