### ISSUE TITLE
Update README.txt

### ISSUE THREAD

**Issue by JPcode05** [tenacityteam/tenacity-legacy#23]
While I notice README.md is being constantly updated, Audacity also has README.txt, which no one really focuses on, and needs to be updated to match README.md. It's confusing, I know; there are two README files.

P.S. Now I know that GitHub always defaults to the Markdown version instead of the plaintext version (with a .txt, at least).

**Comment by Sciss** [comment]
I would delete it, why would you want to maintain two competing READMEs?

**Comment by JPcode05** [comment]
> I would delete it, why would you want to maintain two competing READMEs?

I can do it! The .txt looks up-to-date, containing a 2021 copyright date. All someone has to do is convert Markdown into plaintext. I prefer being able to read the document in a terminal without any formatting issues. Maybe let's have a vote.

* Like (+1) if you want to keep two READMEs (so we can read the plaintext inside a terminal).
* Dislike (-1) if you want to get rid of one and keep the other.

**Comment by cookiengineer** [comment]
I also think the README.txt seems unnecessarily redundant. The purpose of the readme seems to be that you can run the `AppRun.sh` file (the entry point for the AppImage?) with a `--readme` flag, which seems to be a bit pointless in my opinion.

**Comment by Sciss** [comment]
To be safe that extra information in `README.txt` could just be merged into `README.md`. I would opt to keep the markdown, that's still very much readable in a terminal without mark-up highlight.

**Comment by emabrey** [comment]
Why can't you read the markdown format in a terminal? I just literally opened it in `ed` on a WSL2 instance and it worked fine. You can also literally just `cat` it out. On Windows you can use `notepad /W "README.md"` or `type README.md` (from within the cmd.exe prompt or a Powershell prompt). Are you typing `README.md` and letting the default file association handler open it?

**Comment by JPcode05** [comment]
> To be safe that extra information in `README.txt` could just be merged into `README.md`. I would opt to keep the markdown, that's still very much readable in a terminal without mark-up highlight.

> Why can't you read the markdown format in a terminal? I just literally opened it in `ed` on a WSL2 instance and it worked fine. You can also literally just `cat` it out. On Windows you can use `notepad /W "README.md"` or `type README.md`.

But what about **bolds**, _italics_, `preformatting` and more? It'll just show the raw formatting of the text, which kinda looks distracting to me, because I do want to see the plaintext when I `cat` it out.

P.S. Don't forget to go vote!

**Comment by Sciss** [comment]
Yeah, I guess it's up to personal taste. I completely read `**bold**` and `*italics*` fine in plain text with the asterisks. __Edit:__ Would this work for you?

```
pandoc --to=plain README.md
```

**Comment by emabrey** [comment]
> I do want to see the plaintext when I `cat` it out.
>
Ah, I thought you meant you literally couldn't get a terminal to open it, but you could get it opened under a different file name. It seems that adding additional maintenance on an ongoing basis for a user first-look item like a README is just asking for more opportunities for typos and also for things like being out of sync. If we are going to have one at all we should setup some kind of  
tool that automatically runs and generates the `.txt` from the `.md` by removing the markup. There is an easy way to do it even: using Github Actions, [`setup-node`](https://github.com/actions/setup-node) action template and the [`remove-markdown`](https://github.com/stiang/remove-markdown) node.js module.

**Comment by JPcode05** [comment]
> Yeah, I guess it's up to personal taste. I completely read `**bold**` and `*italics*` fine in plain text with the asterisks. **Edit:** Would this work for you?
> 
> ```
> pandoc --to=plain README.md
> ```

**Yes, that would work for me!**

I just thought of [man pages](https://en.wikipedia.org/wiki/Man_page) and thought that our fork should have a man page, as I use man pages as a simple way to see the manual for a program.

So all we have to do is:
1. Merge README.txt into README.md
2. Use Pandoc or whatever to convert the Markdown format into plaintext.
3. Use the plaintext in `AppRun.sh --readme` as well as the man page.

Before I close this issue, how do I commit to this repository?

**Comment by zeGolem** [comment]
> Before I close this issue, how do I commit to this repository?

You need to fork it, make the changes in your fork, and open a pull request to merge the changes

**Comment by JPcode05** [comment]
> > Before I close this issue, how do I commit to this repository?
> 
> You need to fork it, make the changes in your fork, and open a pull request to merge the changes

How do I sync my fork?

**Comment by emabrey** [comment]
> pandoc

I think using a CI approach and having it generated on Github Actions is best, though we probably could use either the node module or this external tool. I would prefer the node module, as it allows us to add so much more extensibility should we wish to generate different formats in the future or make additional checks for typos or something like that. Otherwise, just running pandoc on it manually and committing the change means we rely on any PR for either README format to have been manually run through pandoc. It also means we need a tool for the reverse in order to automate the pandoc tool approach, because what if someone edits `README.txt` and doesn't manually edit `README.md`, how are they going to have a tool figure out the places it should put formatting? Making the `README.txt` a VCS generated file means it happens automatically, so long as we just block PRs that change `README.txt` standalone.

**Comment by emabrey** [comment]
Pandoc is supported via Github Actions to be clear. https://pandoc.org/installing.html#github-actions

**Comment by JPcode05** [comment]
I created a pull request, which gets rid of INSTALL and README.txt.

> Pandoc is supported via Github Actions to be clear. https://pandoc.org/installing.html#github-actions

We will use Pandoc to convert any Markdown to plaintext if we need to.
