### ISSUE TITLE
Reinstate locales (zh_TW, ca_ES@valencia, and others)

### ISSUE THREAD

**Issue by Artoria2e5** [tenacityteam/tenacity-legacy#230]
- [x] I have read the specified guidelines for issues

**Describe the bug**
Commit 8d3f9f0be6eb8d15de7c809768783d9ed9796128, introduced by PR #175, has caused a number of significantly different languages to be merged into the same. This is *very* wrong and must be fixed by:
* Restoring the files
* Adding the languages to weblate

Every single language removed is arguably a political bomb:
* zh_CN and zh_TW aren't even written with the same script, so they look *very different* from the first glance. And it's not like the two political entities -- or peoples for that matter -- are friendly with each other!
* ca_ES\@valencia has a separate community. https://sourceware.org/bugzilla/show_bug.cgi?id=2522
* eu_ES might be fine. I don't know much about that.
* sr_RS and sr_RS\@Latin nominatively differ only in the writing system, but the translations look different so I can't exactly recommend programmatic conversion. I don't want to start World War I or the Yugoslav Wars again -- a local speaker should handle this.
* pt_PT and pt_BR have separate communities. I do not know much about the two, but just imagine I suddenly started spelling every "er" with a "re" and talking about "crisps".

**To Reproduce**
I do not believe the change has been made into any releases yet. And don't make it into any release.

Next time you do touch i18n, consider looking at the file history and at-ing some past translators to help.

**Comment by n0toose** [comment]
Yeah, has to be just an accident. Locales represent dialects, after all. We did not remove all of those files consciously (nor did we think that Brazilian Portuguese was the same as European Portuguese) or check them individually, I'm assuming we just tried to import them straight to Weblate and they got removed from the project during importation. We did not mean to make an implicit political statement, or whatever.

(P.S. Sorry if this frustrated anyone. Questions are welcome, but let's please not cause an unnecessary diplomatic disaster, it's really not that deep in the context of a FLOSS audio editor.)

**Comment by n0toose** [comment]
Either way, we'll try to fix this. Let any of us know if you need anything else.

**Comment by emabrey** [comment]
I was literally already planning to do this today but I had internet issues. I needed to remove the files temporarily. They are still in the git history so we haven't lost the translations. It was just due to the Weblate import. It was NOT a political statement and if anyone though it was I apologize. I knew that these were different and it was not an oversight or a misunderstanding of the differences in the locales. I was actually worried that this exact issue might be brought up but I figured the ease of assisting the Weblate import was worth the temporary reduction. It will not make it to release without ALL the translations present. Once again, sorry for any confusion.

**Comment by emabrey** [comment]
So `eu_ES` seems like it is the same thing as `eu`. Basque is from Spain and France, but I can't find a France specific `eu` locale. 
![image](https://user-images.githubusercontent.com/3370875/125509577-8eaffa29-584a-4bd4-9d05-772090a0dffd.png)
https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=eu
Unless someone else has some input, I think we can leave it just as `eu`.

I've replaced `zh_CN` and `zh_TW` with `zh` (an alias of `zh_hans` A/K/A `Chinese (Simplified)`) and `zh_hant` (A/K/A `Chinese (Traditional)`). Technically `zh_hant` covers Hong Kong AND Taiwan, which seems like it would be more inclusive. Additionally, Weblate does not currently support `zh_TW` or `zh_CN`, and as far as I can tell `Chinese (Traditional)` and `Chinese (Traditional) - Taiwan` are only an important distinction if we plan to add support for `Chinese (Traditional) - Hong Kong`. If someone has some objection to how I've handled this then let me know, but I think that I've solved the removal problem.

I've fixed the Serbian locales (latin and non-latin) and the Portuguese locales (Brazil and Portugal) to be back to normal.

**Comment by alvinhochun** [comment]
> I've replaced `zh_CN` and `zh_TW` with `zh` (an alias of `zh_hans` A/K/A `Chinese (Simplified)`) and `zh_hant` (A/K/A `Chinese (Traditional)`). Technically `zh_hant` covers Hong Kong AND Taiwan, which seems like it would be more inclusive. Additionally, Weblate does not currently support `zh_TW` or `zh_CN`, and as far as I can tell `Chinese (Traditional)` and `Chinese (Traditional) - Taiwan` are only an important distinction if we plan to add support for `Chinese (Traditional) - Hong Kong`.

While it is somewhat true in some way, I'd be inclined to keep them as `zh_CN` and `zh_TW`, *especially if* you are actually using Unix (actually glibc) locale identifiers in the format of `language[_territory][@modifier]`, which by the way is *not* BCP47. I don't believe `zh_hant` is a valid locale identifier in glibc.

On GNU/Linux, practically, any users Hong Kong and Macau (yes, this place exists too) who wish to use a Traditional Chinese user interface would have set `zh_TW` as (one of) the UI language(s) in the `LANGUAGE` environment variable.

On Windows or macOS, the application should somehow automatically choose `zh_TW` as the default when the user is using a Traditional Chinese system UI.

**Comment by emabrey** [comment]
I mean I can ask Weblate to add `zh` country locales, but currently they don't support them.
