### ISSUE TITLE
Add support for XDG directories

### ISSUE THREAD

**Issue by fogti** [tenacityteam/tenacity-legacy#231]
e.g. port/rebase and merge, optionally behind a configure flag: https://github.com/audacity/audacity/pull/831
- [X] I have read the specified guidelines for issues

**Is your feature request related to a problem? Please describe.**
The PR noted above seems to be included in multiple Audacity distribution packages. Porting it would make packaging faster and easier.

**Describe the solution you'd like**
e.g. port/rebase and merge, optionally behind a configure flag.

**Describe alternatives you've considered**
Not rebasing+merging it. This would probably winder adoption in multiple distributions.

**Additional context**
Debian and Nixpkgs seem to use the above mentioned PR (via including the associated patch).

**Comment by Be-ing** [comment]
> optionally behind a configure flag

Please let's not do this. Write some migration code to move or copy the old data to the new location.

**Comment by serebit** [comment]
Hey, that's my PR! I considered rebasing and submitting it here, actually. I give full rights for anyone to do it themselves if they want.

**Comment by serebit** [comment]
What that PR does (if I remember correctly) is check for an existing ~/.audacity_data folder, and use that if it exists. If that folder doesn't exist, it uses the proper XDG dirs. If you're adapting it for Tenacity, it should probably just default to the XDG dirs.

**Comment by n0toose** [comment]
> Hey, that's my PR! I considered rebasing and submitting it here, actually. I give full rights for anyone to do it themselves if they want.

hey, thank you for your generosity! :)

(but yeah, this won't work here, because of our DCO, you sort of have to sign that before we can do anything with it.)

**Comment by serebit** [comment]
Ah. Well that's a bit of a pisser, isn't it? Guess I'll just have to port it over myself and attach a signoff, then. I'll get around to it.

**Comment by n0toose** [comment]
> Guess I'll just have to port it over myself and attach a signoff, then.

You could also just sign it off (it's just a mechanism we've put in place in order to prevent similar governance failures), but we are very held up at the moment, so I'm not sure when any of us would be able to address this. Either way, we'd be thankful.

**Comment by nbsp** [comment]
@serebit: Could you port the PR over to here? As panos said, we need to have you sign it off.

> If you're adapting it for Tenacity, it should probably just default to the XDG dirs.

Agree.

**Comment by serebit** [comment]
Well I can't port it myself for at least another week, but I can sign off the commit on the Audacity side if any others wish to port it from there.

**Comment by nbsp** [comment]
That should work. Thanks!

**Comment by serebit** [comment]
Done. Have at it!
