### ISSUE TITLE
[Blog / News] Could the tenacity team consider a policy in regards to telling users about any news every now and then regarding tenacity?

### ISSUE THREAD

**Issue by rubyFeedback** [tenacityteam/tenacity-legacy#242]
Would it be possible for tenacity to make something like 3-months updates or anything like that?

Such as the more important things that were worked on during that time. I assume tenacity will be
the main contender to audacity and not long ago I read that it is planned to integrate well into
pipewire (which hopefully will eventually manage to coordinate the disparate projects in
regards to e. g. ALSA, jackaudio, pulseaudio and so forth).

Talking about what is new every now and then would be quite important IMO because that way
people who are not part of the dev team know what is going on. I know that pipewire itself
is also going under heavy changes. We have some very good multimedia-related projects
such as ffmpeg and mpv, so it would be great if pipewire and tenacity (e. g. with the spirit
in mind of oldschool audacity) could be in-the-mix as well. In particular recording audio 
via audacity was quite convenient.

PS: I tried to file this under discussions actually, but when I tried to "select" it as "Idea" in the
dropdown box, nothing happens, so I assume my browser isn't recognized properly by
github (palemoon browser). I did not want to use another browser to suggest this, but the
pre-determined templates did not allow for alternatives (since, as I wrote, the discussion
section has this drop down box which does not change when I use palemoon. I have had
issues with github and palemoon before and github always claims it is not a supported
browser... the browser monopolification continues ... :( most other javascript stuff works
fine though).

**Comment by Be-ing** [comment]
It is way too soon to discuss this.

**Comment by NotAProton** [comment]
we are thinking of embedding the latest tenacity-announce mail on the tenacityaudio site

**Comment by nbsp** [comment]
Please consider subscribing to the [`tenacity-announce`](https://lists.sr.ht/~tenacity/tenacity-announce) mailing list, a low-volume mailing list for announcements.
