### ISSUE TITLE
Configuring Tenacity with CMake failed due to either pthread or conan 

### ISSUE THREAD

**Issue by nowhere-girl** [tenacityteam/tenacity-legacy#247]
**Describe the bug**
Encountered '`Conan install failed='1'`' during configuration in CMake. I have conan installed both with pip and pip3. My python version is 3.9 (screenshot attached). I doubt the problem was conan, inside my CMake error log (log attached below using Gist), I think the problem was pthread (?). I came across what could be [the same issues in Tenacity here](https://github.com/tenacityteam/tenacity/issues/39), however there's still no solution to the question. 

**To Reproduce**
1. Download the latest repository.
2. Extract and configure it with CMake

**Screenshots**
![error](https://user-images.githubusercontent.com/62411431/125400565-3ff0fb80-e3dc-11eb-99df-91fe7082738b.jpg)

![Screenshot from 2021-07-13 13-12-53](https://user-images.githubusercontent.com/62411431/125400438-1506a780-e3dc-11eb-9a4d-5d04110fc9c4.png)

**Additional information (please complete the following information):**
 - OS: Ubuntu 20.04
 - CMake Version : 3.16
 - CMake Error log : https://gist.github.com/nowhere-girl/32d37d4044272b60e8ff86c4efa34971

**Additional context**
I read in several solutions online to put these 2 lines inside CMakeLists.txt :
```
set( CMAKE_CXX_FLAGS -pthread )
find_package(Threads)
```
I've put these lines, but errors I've encountered before and after adding these lines were the same.

**Comment by Be-ing** [comment]
Could you test #228?

**Comment by nowhere-girl** [comment]
> Could you test #228?

Thank you. I tried to read it and get overwhelmed. Anyway, I think I got the problem, it is fixed now. In the errors I've mentioned previously, aside from pthread errors in CMakeError log and conan installation failed, there's some other errors that I missed related to expat before conan error messages :

```
expat/2.2.9@audacity/stable: 

WARN: wxwidgets/3.1.3.1-audacity: requirement expat/2.2.9 overridden by your conanfile to expat/2.2.9@audacity/stable 
expat/2.2.9@audacity/stable: WARN: Package binary is corrupted, removing: 30eae4e50fefe0f7b788ed8928ac248681ea6af0
expat/2.2.9@audacity/stable: ERROR: Package '30eae4e50fefe0f7b788ed8928ac248681ea6af0' build failed
expat/2.2.9@audacity/stable: WARN: Build folder /home/raisa/.conan/data/expat/2.2.9/audacity/stable/build/30eae4e50fefe0f7b788ed8928ac248681ea6af0
ERROR: expat/2.2.9@audacity/stable: Error in build() method, line 96
	self._build_autotools()
while calling '_build_autotools', line 82
	autotools = self._configure_autotools()
while calling '_configure_autotools', line 77
	self._autotools.configure(args=args, configure_dir=self._source_subfolder)
	ConanException: Error 1 while executing source_subfolder/configure '--disable-static' '--enable-shared' '--prefix=/home/raisa/.conan/data/expat/2.2.9/audacity/stable/package/30eae4e50fefe0f7b788ed8928ac248681ea6af0' '--bindir=${prefix}/bin
' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share' 

CMake Error at cmake-proxies/cmake-modules/conan.cmake:631 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:233 (conan_cmake_install)
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:254 (_conan_install)
  CMakeLists.txt:475 (resolve_conan_dependencies)
```

I navigated to my cmake parameter, and find "`use_expat`" , I changed the value from local to system.
![expat](https://user-images.githubusercontent.com/62411431/125522117-f26ef376-f3d9-420b-a54c-4f7cff8f6ec1.jpg)

It fixed my problem, I was able to configure and generate successfully. Now I have a fully working Tenacity in my system, however I seem to be missing "Vocal Removal and Isolation" from the Effect menu, it is disabled by default and I can't seen to enable it even after restarting the program, is this normal in this version release ? 
Anyway, my issue is fixed as of now so I'm closing this thread.
