### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by SnowmanKing** [tenacityteam/tenacity-legacy#26]
I think it would be helpful to have a discord server for this audacity fork. Very much in favor of the fork and I think that a discord server would help with discussions and all.

**Comment by JPcode05** [comment]
I would not suggest a Discord server, considering that Discord is proprietary and we also have Matrix and Libera Chat.

**Comment by ajayyy** [comment]
Duplicate of https://github.com/cookiengineer/audacity/issues/7

**Comment by AnErrupTion** [comment]
https://discord.gg/jQrv5rmzsK
https://matrix.to/#/#audacityfork:semisol.dev

**Comment by abb128** [comment]
This entire fork was started because of Audacity's telemetry and spying. I don't see the logic in using a proprietary chat platform that has telemetry and spying.

**Comment by AnErrupTion** [comment]
There's still the Matrix room

**Comment by dotjax** [comment]
Discord should not be used. It is properietary and their ToS does not respect the user's freedom/privacy. We should stay on Matrix and Libera Chat (is there even a room for it?).

**Comment by dotjax** [comment]
> There's still the Matrix room

It'd make more sense to have the official fork only use something like Matrix/Libera Chat. Perhaps an unofficial chat in Discord is something you can run? This whole mess started because of spyware-like practices and Discord is not know for following the FOSS philosophy.

**Comment by AnErrupTion** [comment]
Yeah, that's why now I plan to only say the Matrix room, not the Discord server.

**Comment by SnowmanKing** [comment]
Yes, I agree with using something like the matrix, but I think having a discord is nice on the side for people who don't have matrix and to have an unofficial chat is true.

**Comment by SnowmanKing** [comment]
What one Matrix are we all sticking with? I just don't want there to be like 20 of them lol

**Comment by AnErrupTion** [comment]
I don't know, mine is already bridged so maybe bridge the other?

**Comment by JPcode05** [comment]
@AnErrupTion @SnowmanKing Maybe the Discord server should just be unofficial. Only officially use Matrix and IRC.

> It'd make more sense to have the official fork only use something like Matrix/Libera Chat. Perhaps an unofficial chat in Discord is something you can run? This whole mess started because of spyware-like practices and Discord is not know for following the FOSS philosophy.

**Comment by AnErrupTion** [comment]
Yeah I don't see any problems wtih that

**Comment by dotjax** [comment]
> @AnErrupTion @SnowmanKing Maybe the Discord server should just be unofficial. Only officially use Matrix and IRC.
> 
> > It'd make more sense to have the official fork only use something like Matrix/Libera Chat. Perhaps an unofficial chat in Discord is something you can run? This whole mess started because of spyware-like practices and Discord is not know for following the FOSS philosophy.

Yeah, that's what I was getting at. Official chat platforms should remain strictly FOSS.

**Comment by ajayyy** [comment]
The current non-bridged IRC/Matrix room is https://matrix.to/#/#audiofork:libera.chat, as shown in the previous thread. A new one might have to be made though as I don't think anyone has op in the channel.

**Comment by AnErrupTion** [comment]
It's relatively inactive though, mine is more active, just sayin' xD

**Comment by panos** [comment]
Really hoping that the target room is not bridged with two separate homeservers right now. This will cause a huge mess moderation-wise and as far as organizing the room is concerned, it's better to just announce an address on your homeserver. :V

**Comment by panos** [comment]
Organizing rooms that we will have to ditch shortly afterwards is not a good idea, in my honest opinion. As soon as we get one room, it would be a good idea to give the maintainer some room to decide what's going to happen next, considering that right now he's being bombarded with all sorts of Issues and well-intending people taking a lot of arbitrary decisions could potentially make things worse on that front.

**Comment by ajayyy** [comment]
@panos Matrix rooms are not hosted on one homeserver. The names are just redirects to the matrix room ID. They can be removed and added.

**Comment by panos** [comment]
Yeah, I'm familiar with Matrix, I just wasn't sure whether this was an alias/published address or a whole new room.

**Comment by User-green** [comment]
#### Dupe to #7
Please, go there, not here.

**Comment by LockBitSupp** [comment]
Discord should not be used. It is properietary and their ToS does not respect the user's freedom/privacy. We should stay on Matrix and Libera Chat (is there even a room for it?).

**Comment by User-green** [comment]
> Discord should not be used. It is properietary and their ToS does not respect the user's freedom/privacy. We should stay on Matrix and Libera Chat (is there even a room for it?).

This been said already.
Please, go to the #7 for this.

**Comment by emabrey** [comment]
Closed as duplicate of #7.
