### ISSUE TITLE
On Windows GitHub Actions build, all plugins are disabled and cannot be enabled

### ISSUE THREAD

**Issue by nyanpasu64** [tenacityteam/tenacity-legacy#271]
- [x] I have read the specified guidelines for issues

**Describe the bug**
On a clean Windows 10 machine without Audacity previously installed, when I download and extract the Win64 build from GitHub Actions, the menus are missing most actions, and all plugins are disabled and cannot be reenabled.

**To Reproduce**
1. Download https://github.com/tenacityteam/tenacity/suites/3241483574/artifacts/75246671.
2. Extract and run the program.
3. Click on the Generate, Effect, or Analyze menus.

All plugins are missing.

If I open a menu then click Add / Remove Plugins, then try enabling plugins, pressing OK does not enable the plugins, and they again appear as disabled when I reopen Add / Remove Plugins.

**Expected behavior**
All plugins are present.

**Screenshots**

![ARKQhJh8QG](https://user-images.githubusercontent.com/913957/125711270-b56e7b37-30f1-40ef-b5c6-43f061ef0068.png)

![firefox_zVqDQUabhN](https://user-images.githubusercontent.com/913957/125711275-8903e695-5cd1-442e-b21d-b319fd2a2590.png)

**Additional information (please complete the following information):**
 - OS: Windows 10
 - Version: Audacity_Windows_64bit_1031847544_7a55a0b.zip

**Additional context**
When building Tenacity myself on Linux, I've noticed in some cases that when swapping between Flatpak Audacity and self-built Tenacity, I would get duplicate plugin warnings and disabled plugins I couldn't enable. Renaming ~/.audacity-data/ and allowing it to be recreated would reset the settings and fix the issue when it happened.

**Comment by emabrey** [comment]
I wasn't able to repro this on `audacity-win-3.0.4-alpha+9238df3-32bit`:

![image](https://user-images.githubusercontent.com/3370875/125727252-3d1f44d8-c847-474b-9f2c-184a95959e15.png)

I also couldn't repro it on `audacity-win-3.0.4-alpha+9238df3-64bit`:
![image](https://user-images.githubusercontent.com/3370875/125727405-41203afa-2f52-46a7-a505-1fe5c0003299.png)

To make sure it wasn't recently fixed, I also checked your version `audacity-win-3.0.4-alpha+7a55a0b-64bit`, and I also couldn't repro:
![image](https://user-images.githubusercontent.com/3370875/125727592-b9dc0b78-09aa-40ca-a813-87e546584595.png)

I notice you have the `Disabled` radio-button selected. Can you select the `All` radio-button and provide a screenshot of the entire plugin list?

**Comment by nyanpasu64** [comment]
The bug only happens when I remove `%userprofile%\AppData\Roaming\audacity`, then launch Tenacity to create the folder, before launching properly installed Audacity to create the folder.

This is the contents of "All". Enabled and New are empty.

![fx18k8hAjT](https://user-images.githubusercontent.com/913957/125732223-44f74434-0ba5-4aa8-b704-9c1640e32440.png)

**Comment by nyanpasu64** [comment]
I think it's the same issue as #283.
