### ISSUE TITLE
Many translatable strings have the wrong project name hardcoded

### ISSUE THREAD

**Issue by fitojb** [tenacityteam/tenacity-legacy#275]
In LibreOffice, we use a variable, %PRODUCTNAME, that is replaced in runtime. Please do something similar comprehensively.

**Comment by emabrey** [comment]
There are over 4000 strings so it's a WIP currently. I was looking into fixing the fact that the key names are used as the English locale first, and then once the English locale is properly editable on Weblate like every other locale, we can just fix the key names without worrying about them needing to be user-facing. It will probably take a fair bit of work to transition this properly unfortunately, but better late then never.

**Comment by emabrey** [comment]
Now that I have an English PO file this will be an easier fix. You can monitor my progress here if you'd like: https://github.com/tenacityteam/tenacity/pull/276
