### ISSUE TITLE
The license link in the contributing.md does not exist.

### ISSUE THREAD

**Issue by waleed177** [tenacityteam/tenacity-legacy#280]
- [x] I have read the specified guidelines for issues

**Describe the bug**
The license link in the contributing.md does not exist.

**To Reproduce**
1. Goto https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin
2. Click on License in the text "Tenacity is an open source project licensed under the GNU General Public license, version 2 or later (see LICENSE)."
3. Doesn't exist.

**Expected behavior**
Should go to https://github.com/tenacityteam/tenacity/blob/master/LICENSE.txt

**Comment by nm17** [comment]
I think you should open a PR for this

**Comment by nbsp** [comment]
Sent a [patch](https://lists.sr.ht/~tenacity/tenacity-dev/patches/23860) for that, closing.
