### ISSUE TITLE
Plugins are unable to load on certain OS

### ISSUE THREAD

**Issue by nm17** [tenacityteam/tenacity-legacy#283]
- [x] I have read the specified guidelines for issues

**Describe the bug**
Plugins are not loaded properly. Upon closer inspection, the issue may lie in the function `NyquistEffectsModule::AutoRegisterPlugins`. PluginManager's mPlugins seems to already have a lot of plugins already present in it at the time of calling `NyquistEffectsModule::AutoRegisterPlugins`.
A good explaination is provided here:
![nyquist-1](https://user-images.githubusercontent.com/23419131/125912998-5e596be5-ffa9-497e-99b5-61f377c6cb65.png)

**To Reproduce**
Clone at the commit af2b77bf47d5ba604e9b0cd6331d0016824cc93f and compile it using CMake (I used CLion IDE, which handles CMake a bit different than vanilla `cmake` CLI tool, but it seems to be happening with the regular CMake as well).
Also a similar issue is present (for me at least) at https://github.com/nm17/tenacity-snap/issues/1 , but it's in a snap package, which might be inconvenient to debug. 

**Expected behavior**
Run tenacity normally, without any bugs with the plugins.

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]: Ubuntu 21.04 amd64
 - Version [e.g. 2.5.1]: af2b77bf47d5ba604e9b0cd6331d0016824cc93f
 - Sound Device [e.g. Windows WASAPI, USB Sound card]: Embedded sound card

**Additional information**
[CMakeCache.txt](https://github.com/tenacityteam/tenacity/files/6829037/CMakeCache.txt)

**Comment by nm17** [comment]
Forcefully setting `isValid` and `isEnabled` to true seems to show all the plugins, but none of them can be used. No new logs available.

![image](https://user-images.githubusercontent.com/23419131/125920155-eab051eb-8dc3-4631-9d4e-29b33d309ab0.png)

**Comment by nm17** [comment]
`ModuleManager::IsPluginValid` is trying to set `isValid` to `false`

**Comment by nm17** [comment]
### Notice how `asd` is NULL
![image](https://user-images.githubusercontent.com/23419131/125922470-512c8987-97be-46c5-a639-527812966576.png)
### Possible culprit (investigate mDynModules and find out why `PluginDescriptor::GetInstance` returns nullptr) (Might be a problem with ModuleMap using unique_ptr or something idk)
![image](https://user-images.githubusercontent.com/23419131/125924002-a4833e15-26e6-440d-9a07-e901dba54395.png)

**Comment by Kelp-Forest** [comment]
I have a problem with no effects showing up if pluginregistry.cfg is deleted before starting.  Trying to enable even builtins is non functional.
If the config file exists and was created using a (much) ealier version of audacity then the plugins exist in the menu and are functional.  They do seem to insist on you making a selection first though,

From what I saw for Amplify effect:

ProviderID=Module__The Audacity Team_Builtin Effects_
vs
ProviderID=Generic__The Audacity Team_Builtin Effects_

was significant.  I saw some comments that some of these types of strings are significant for config compatibility.  I did not verify the exact part of the code that was actually causing the value to change or how the changed value was causing a failure, as I had a release build. It did seem (only) a little strange the providerid string was significant and that it wasn't more obvious how it was being matched.  The strings seem to be built from parts and matched in parts. 

It could be some sort of oversight due to the memory of the config files vs autoregistration, otherwise it is a incomplete change to the codebase.  I think I downloaded on the 13th.

**Comment by nm17** [comment]
If anyone is having trouble reproducing this issue, just try to create a VM with a clean Ubuntu Desktop (21.04 should do it) and build Tenacity like always.

**Comment by nyanpasu64** [comment]
I think #271 is the same issue as this.

> When building Tenacity myself on Linux, I've noticed in some cases that when swapping between Flatpak Audacity and self-built Tenacity, I would get duplicate plugin warnings and disabled plugins I couldn't enable. Renaming ~/.audacity-data/ and allowing it to be recreated would reset the settings and fix the issue when it happened.

> The bug only happens when I remove `%userprofile%\AppData\Roaming\audacity`, then launch Tenacity to create the folder, before launching properly installed Audacity to create the folder.

I found that renaming pluginregistry.cfg and launching Tenacity is sufficient to cause this bug.

**Comment by n0toose** [comment]
A temporary workaround for Linux users using a version of Tenacity that they built themselves seems to be installing Audacity on the same system.

**Comment by nm17** [comment]
> A temporary workaround for Linux users using a version of Tenacity that they built themselves seems to be installing Audacity on the same system.

And making sure that they delete .audacity-data before starting regular Audacity and trying to start tenacity again

**Comment by nm17** [comment]
Replacing Generic__ to Module__ in the cfg (also in the base64 strings) seems to fix the problem

**Comment by nm17** [comment]
First bad commit https://github.com/tenacityteam/tenacity/commit/02b61532fe1d5de459de705ccfe81e3c8d7cda89

### Git Bisect log
```
# bad: [af2b77bf47d5ba604e9b0cd6331d0016824cc93f] Merge pull request #164 from abb128/master
# good: [8aca9d02de3c69f718dd12822edb5393c58d29bf] Add the first Conan-based dependecies
git bisect start 'master' '8aca9d02'
# good: [c8e0bf343dbecbb1e1d181ceef124705bdc72079] Fixes the libmad disabled by mistake
git bisect good c8e0bf343dbecbb1e1d181ceef124705bdc72079
# bad: [179b36d0dccc1303da8cbd7198d5149de17a971f] Merge branch 'master' into emabrey-readme-patch-1
git bisect bad 179b36d0dccc1303da8cbd7198d5149de17a971f
# good: [710ec976ff19b2f1f2f8148aeba8831f48566043] Move class PluginRegistrationDialog to a header file
git bisect good 710ec976ff19b2f1f2f8148aeba8831f48566043
# bad: [8271f4ddf845e56ed734a2057c16f68d18b10686] Merge pull request #1 from zeGolem/better-explainations
git bisect bad 8271f4ddf845e56ed734a2057c16f68d18b10686
# bad: [132f04d27215eb7d3ec7100e448d02af796c9106] ManualPageID is a new type; rewrite HelpSystem::ShowHelp and its uses
git bisect bad 132f04d27215eb7d3ec7100e448d02af796c9106
# bad: [d5a22dfb15f2396d650c38701bd804cb7390f798] Eliminate last use of PluginManager by ModuleManager, breaking cycle
git bisect bad d5a22dfb15f2396d650c38701bd804cb7390f798
# good: [2e7f7114d27dba8ed3b1473f892cfb2bfbbf15c0] ModuleManager defines the ID strings for modules, not PluginManager
git bisect good 2e7f7114d27dba8ed3b1473f892cfb2bfbbf15c0
# bad: [02b61532fe1d5de459de705ccfe81e3c8d7cda89] ModuleManager doesn't use PluginManager to initialize providers
git bisect bad 02b61532fe1d5de459de705ccfe81e3c8d7cda89
# first bad commit: [02b61532fe1d5de459de705ccfe81e3c8d7cda89] ModuleManager doesn't use PluginManager to initialize providers
```

**Comment by nyanpasu64** [comment]
I think 02b61532fe1d5de459de705ccfe81e3c8d7cda89 is a commit written by upstream Audacity, so it will affect Audacity too.

I think Tenacity forked off Audacity during the middle of a [plugin management refactor](https://github.com/audacity/audacity/issues/1180) (along with a [planning thread](https://github.com/audacity/audacity/issues/999)), and the current state is broken. I didn't test Audacity master to see if that's broken too (in which case the issue can be reported upstream too). Do you prefer to revert the changes we have so far, or pull in upstream commits if/when they fix the problem?

**Comment by nm17** [comment]
@nyanpasu64 lets decide on that later tomorrow, I think it's better for everyone that way. Maybe we can do a vote for that too.

**Comment by Kelp-Forest** [comment]
As for the workaround that suggests using a config file built from an unaffected version of audacity, note that, at least on windows, there are absolute file paths in the file.  (There is a general issue of a user using multiple versions of audacity.  This also affects testing.)
