### ISSUE TITLE
Use commit hashes in versions

### ISSUE THREAD

**Issue by n0toose** [tenacityteam/tenacity-legacy#291]
- [x] I have read the specified guidelines for issues

**Is your feature request related to a problem? Please describe.**

Tenacity recently removed dates from versions in order to make builds more reproducible. See fbaa87b5110ef2029b10f6d4525d13cf24a0c49d, but the version is very vague now.

**Describe the solution you'd like**
It was discussed that we should use commit hashes instead.

**Additional context**
See https://github.com/tenacityteam/tenacity/pull/224

**Comment by Be-ing** [comment]
Note that [short hashes are not reproducible](https://reproducible-builds.org/docs/version-information/).

**Comment by YellowAfterlife** [comment]
HaxeDevelop does it this way:
![image](https://user-images.githubusercontent.com/731492/126647495-335ad662-e025-4a0d-a93a-e360ba3227db.png)
The branchname#hash is an anchor and clicking it navigates to GitHub page for the (full) commit hash.

Simply grabbing `__DATE__` in a separate little file that gets its own `.obj` might also suffice for purposes of cache.

**Comment by n0toose** [comment]
Also worth considering:

https://github.com/tenacityteam/tenacity/blob/bb95f80a704601001cbc6cee413ce2ff46dee982/src/AboutDialog.cpp#L60-L64

Problem with `__DATE__`'s is that it reduces reproducibility.

**Comment by nbsp** [comment]
Would using the output of `git describe` work? This is its format:

```
<latest tag>-<# of commits since tag>-g<short HEAD hash>
Audacity-2.4.1-1734-ga30f84e44

**Comment by nbsp** [comment]
Or, as Reproducible Builds suggests, `git describe --abbrev=5`.
