### ISSUE TITLE
Possible trademark issue

### ISSUE THREAD

**Issue by EricBright** [tenacityteam/tenacity-legacy#3]
**Audacity name and logo are registered trademarks of Muse Group now**
Since the original logo, name, and other trademarks are now registered under Muse Group (MuseCY SM Ltd. to be more precise) (see https://en.wikipedia.org/wiki/Audacity_%28audio_editor%29#Audacity_trademarks for more information), it would be prudent to start thinking of a new **brand identity** for this project that is not going to collide with Muse Group’s assets.

**Choose a new brand identity**
If the trademark is indeed an issue, then everything that refers to Audacity’s trademarks needs to be properly expunged from this fork. I suggest we choose a new name, a new logo, and the replacement of every mention of Audacity in the PR materials in the early stages of this project (until we gradually remove them from the code). The sooner it happens the better, since it can cause serious issues down the road.

**Alternative ideas**
We might want to seek the legal advice of a lawyer or whomever is well-versed in copyright and trademark issue early on to avoid making costly or unnecessary moves.

**Comment by cookiengineer** [comment]
I completely agree with you there. I've already taken a glimpse at the codebase, and it seems that _a lot_ of HTML codes and URLs are embedded as static strings inside the codebase. At build time there are also running a lot of scripts that do wiki2html conversions where I have no clue how they're being used.

In order to not violate any copyright of the official audacityteam [dot] org website, we probably should start a wiki here with the Getting Started guide etc. I'm not sure whether or not a simple webview would make sense for that manner, so we could move all the HTML contents into a static folder and just ship it locally so that users don't need internet for that. I'm going to open a separate issue for that.

**Comment by EricBright** [comment]
All the while, a rash decision in the early stages of the development of this branch, i.e. taking a wrong turn too early, might complicate future development choices. At this stage, I think tackling the low-hanging fruits might be a bit more practical, than to make major changes in the code and then finding out later that we could/should have done something else.

As a suggestion, untangling and simplifying things first without making huge decisions that might have unforeseen consequences, might be a safer move. The most obvious steps, at this stage, might be merely changing the names and the logos, the things that are clearly visible. The next, and arguably more difficult task would be figuring out how to deal with the hidden parts little by little. This is not to undervalue the importance of a well-chosen name and logo, but to deal with the easier tasks first.

**Comment by JPcode05** [comment]
[newscracker on Hacker News](https://news.ycombinator.com/item?id=27727466) says to call the project _Audacious_. You (Edit: cookieengineer) replied to that comment to announce your fork.

You should also create a website (using its own domain) for the project to be located at, including its wiki and forum.

While GitHub and GitLab allow you to host wikis in the repos themselves, I would rather the Wiki be separate, maybe using MediaWiki (most familiar, I recommend), [DokuWiki](https://www.dokuwiki.org/dokuwiki) or whatever.

**Comment by abrolag** [comment]
As I mentioned in another issue, how about:
AudioCity
Sohuld be recognisable but safe.

**Comment by suetanvil** [comment]
Audacity -> Odd Ass City -> Strange Donkey City -> Strange Donkey

No way it'll be confused with Audacity.

Also: Audacious is already the name of [this very nice](https://audacious-media-player.org/) media player.

**Comment by sbutcher** [comment]
Veracity would be a nice name. Confers accuracy/truth, while sounding a bit like audacity.

**Comment by cookiengineer** [comment]
I've deleted the name suggestions that are off topic here.

Please stay on topic, the issue for collecting name suggestions is #5 and I've reopened it.

**Comment by trymeouteh** [comment]
Audacia?
AudacityX?

**Comment by kjcole** [comment]
Chutzpah
