### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by hanskokx** [tenacityteam/tenacity-legacy#307]
Thanks for doing this.  It was sorely needed.

Could you please create a Chocolatey package for easier installations and updates?  The instructions can be found here:

https://docs.chocolatey.org/en-us/create/create-packages

**Comment by n0toose** [comment]
This will definitely be considered once we start putting out releases.

**Comment by hanskokx** [comment]
Thanks!

**Comment by ghost** [comment]
This is a duplicate of #53

**Comment by fossdd** [comment]
Yes, as @Odyssey346 said, it's a duplicate.

@hanskokx Please search if the same issue exist before opening a new issue. However it's still a good idea, but we should keep the discussion there on #53.
