### ISSUE TITLE
Gray bars do not adjust to the theme colors

### ISSUE THREAD

**Issue by ZeroDot1** [tenacityteam/tenacity-legacy#311]
After I compiled the last version with all current changes, gray bars were displayed in the gui during recording (see screenshot).
The whole independent of the theme.
![Bildschirmfoto vom 2021-07-19 13-36-24](https://user-images.githubusercontent.com/28985171/126154761-3f9f2355-6873-466a-ba38-7ad9fa053c3f.png)

Custom Theme File...
![ImageCache](https://user-images.githubusercontent.com/28985171/126155183-9bf0aa8e-fbff-4988-a655-7b0662abb926.png)

**Comment by n0toose** [comment]
Hi, this is a new feature that I directly merged from upstream Audacity. It gives you the ability to do things, such as move the audio clips in a more fluid manner. Is the problem here the fact that it doesn't fit in with your theme? I can see and understand that it looks very out of place.

**Comment by ZeroDot1** [comment]
Exactly, the problem is that this new feature does not fit the dark themes, all dark themes are affected also those included in Tenacity see screenshot.
![Bildschirmfoto vom 2021-07-19 16-26-49](https://user-images.githubusercontent.com/28985171/126176607-09e1f1d0-8dfa-4fb2-b500-657d0d9bdae4.png)

**Comment by ZeroDot1** [comment]
By the way, I recommend creating and integrating themes that customize the look so that it looks e.g. like Adobe Audition. This would make it easier for many people to switch to Tenacity.

**Comment by n0toose** [comment]
> Exactly, the problem is that this new feature does not fit the dark themes, all dark themes are affected also those included in Tenacity see screenshot.

Yup, currently trying to see if/how I can fix that.

**Comment by ZeroDot1** [comment]
> Yup, currently trying to see if/how I can fix that.

Thank you, I am using Tenacity with Arch Linux, if I find any more problems I will report it.

Good luck.

**Comment by n0toose** [comment]
Issue is obviously related to 5672a179dadfa08e617d04002aa033756c26a908.

**Comment by n0toose** [comment]
This manipulates the border color when the user clicks/drags the affordance: https://github.com/tenacityteam/tenacity/blob/e9c575cbc1ea338667c8e5d8568ed384c6ee8e48/src/TrackArtist.cpp#L276

**Comment by n0toose** [comment]
These lines are responsible for the colors, they should be expanded with theme-appropriate alternatives:

https://github.com/tenacityteam/tenacity/blob/e9c575cbc1ea338667c8e5d8568ed384c6ee8e48/src/AllThemeResources.h#L374-L378

**Comment by n0toose** [comment]
Wow, I'm actually onto something here!

![2021-07-19_16-25](https://user-images.githubusercontent.com/30193966/126194034-b01c271e-629d-4649-bfd5-bf8649ac41a4.png)

**Comment by ZeroDot1** [comment]
Hi @panos the problem is solved via: https://github.com/tenacityteam/tenacity/pull/315 
![Bildschirmfoto vom 2021-07-19 22-57-11](https://user-images.githubusercontent.com/28985171/126227004-bdf6d545-e6a4-48a1-8523-e21f768c8cab.png)

**Comment by n0toose** [comment]
Yup, apart from a hiatus, that's also why I took myself off from this issue.

**Comment by akleja** [comment]
I just noticed another problem linked to this issue. The edit cursor isn't drawn in the area of the "Wave track affordances". Audacity resolved it by drawing the edit cursor over the entire track area, which is how it's usually done in most audio editors.

**Comment by akleja** [comment]
Also for the main issue with the bars, the additional colors must be implemented in all themes. I'm quite far along on the light theme and will put out a PR in a few days, maybe sooner, but I haven't touched the high contrast one yet.
In the classic theme I guess it makes sense to just add the missing colors and touch nothing else.

**Comment by akleja** [comment]
Now that the new themes are in place this issue is resolved
