### ISSUE TITLE
Tenacity crashes on shift-clicking and draging vertically in the affordances bar.

### ISSUE THREAD

**Issue by NotAProton** [tenacityteam/tenacity-legacy#324]
- [x] I have read the specified guidelines for issues

Upstream bug with details: [audacity/issues/1329](https://github.com/audacity/audacity/issues/1329)

Can confirm on [latest commit](https://github.com/tenacityteam/tenacity/commit/c447382f442e86e4d59fc3511e852790738422f0), Windows 10 Build 21H1

**Comment by akleja** [comment]
There seems to be a fix upstream https://github.com/audacity/audacity/pull/1344/commits/78af3df1539693947e3b53aa00fd521c74e7059a

**Comment by Paul-Licameli** [comment]
You’re welcome.

**Comment by NotAProton** [comment]
Fixed

https://github.com/tenacityteam/tenacity/commit/dbdd2a39ef2b59447ec25abbe431a9d746b2c3ef
