### ISSUE TITLE
AudacityApp.cpp uses different project file names

### ISSUE THREAD

**Issue by ajayyy** [tenacityteam/tenacity-legacy#333]
https://github.com/tenacityteam/tenacity/blob/2f316d5bc4e2c50dcd2a1c2360721030462e1d33/src/AudacityApp.cpp#L2275-L2295

Should the references there be changed to `Tenacity.Project` like other places, or would this affect previously created project files?

Either these need to be changed, or the other changes need to be reverted.

**Comment by emabrey** [comment]
I wasn't sure if this would affect project import, that is why I left it alone. It needs to be tested locally to really know what will happen.

**Comment by nbsp** [comment]
On Linux, exporting projects from Audacity and importing to Tenacity works just fine with `Tenacity.Project`.

I can open a PR for that if you want.
