### ISSUE TITLE
The configuration file has the wrong name. #Linux

### ISSUE THREAD

**Issue by ZeroDot1** [tenacityteam/tenacity-legacy#340]
The configuration file has the wrong name see the screenshot.

![Bildschirmfoto vom 2021-07-22 17-38-14](https://user-images.githubusercontent.com/28985171/126667484-27e2b238-d4bc-4847-9eb5-f49ce6a9a301.png)

**Comment by nbsp** [comment]
Please follow the bug report template when filing an issue.

**Comment by ZeroDot1** [comment]
Hi @SFR-git I don't know what the problem is with my report, I made a screenshot that shows the problem.

**Comment by Semisol** [comment]
Please follow the bug report template. https://github.com/tenacityteam/tenacity/issues/new?assignees=&labels=&template=bug_report.md

You need to fill it with the fields intact, and not just a very simple explanation.
