### ISSUE TITLE
Does Muse Group's walk back change the impetus for the fork?

### ISSUE THREAD

**Issue by rcrath** [tenacityteam/tenacity-legacy#35]
[Muse Group walked things back today](https://cdm.link/2021/07/audacity-makers-clarify-data-usage-and-theres-not-reason-to-dump-the-editor-yet/). CDM is convinced it is ok.  What do you think?

**Comment by HadetTheUndying** [comment]
Isn't this the second or third Walk back attempt? I think it would be better for the community as a whole to continue work on the fork as it's clear the maintainers/project leaders do not have the same interests as teh users.

**Comment by JPcode05** [comment]
Tenacity is also the name of a [Python library](https://tenacity.readthedocs.io/en/latest/).

**Comment by vchernin** [comment]
More than likely they will continue on the path they are on. They’re not going to stop, and there’s no need to put up with their malicious behaviour. Let the people control the project, not some corporation.

**Comment by Be-ing** [comment]
No.

**Comment by caughtquick** [comment]
> Isn't this the second or third Walk back attempt? I think it would be better for the community as a whole to continue work on the fork as it's clear the maintainers/project leaders do not have the same interests as teh users.

This is the 2nd time that they have walked back, the first step being telemetry, and even that they haven't walked back really at all this time, more of a this is why we did it, without really even justifying it. It's more than time the project is forked.

**Comment by EndlessEden** [comment]
They have already changed the license, and updated their privacy policy, and publicly stated they are going to include "Difference"(which according to their own license, can include proprietary code from MuSE).

https://github.com/audacity/audacity/discussions/1225
https://github.com/audacity/audacity/discussions/932
Nothing has changed. They are untrustworthy, and it brings muse's other products into a more concerning light. If they are willing to do this to Audacity, what have they already done and gotten away with on their products?

We are already seeing a dismissive nature to their handling of issues with the software (https://github.com/audacity/audacity/issues/1228) - Muse is handling this like selling moldy stale bread in a shop, by applying butter and honey to it to make it look edible, then quickly selling and pushing customers out the door.

**Comment by n0toose** [comment]
The perspectives presented here more or less represent most of us and I don't think there's much else to add right now. I pinned this issue for posterity.
