### ISSUE TITLE
Use scdoc for manpage generation

### ISSUE THREAD

**Issue by nbsp** [tenacityteam/tenacity-legacy#358]
- [x] I have read the specified guidelines for issues

**Is your feature request related to a problem? Please describe.**
The [manpage](https://github.com/tenacityteam/tenacity/blob/master/help/tenacity.1) seems to only exist as a processed file, and its source is not available. This makes it a bit unwieldy to use or edit, and you can't really read anything when viewing it raw.

**Describe the solution you'd like**
There are many different manpage generators out there, but my personal favourite is [scdoc](https://sr.ht/~sircmpwn/scdoc/), a fast, readable, and manpage-oriented documentation generator. For example, [SwayWM](https://raw.githubusercontent.com/swaywm/sway/master/sway/sway.1.scd) uses scdoc for its manpages.

`scdoc(5)` contains information about the syntax. It's designed to be similar to Markdown, but different, because Markdown is built for HTML.

As far as the installation process goes, the only thing that needs to be added is `scdoc < tenacity.1.scd` (and of course the scdoc dependency).

**Comment by nbsp** [comment]
I have sent a [patch](https://lists.sr.ht/~tenacity/tenacity-dev/patches/23958) which removes `tenacity.1` and adds `tenacity.1.scd`. Feel free to reply to the patch through email by [clicking this link](mailto:~tenacity/tenacity-dev@lists.sr.ht?cc=Sol%20Fisher%20Romanoff%20%3Csol%40solfisher.com%3E&in-reply-to=%3C20210723203329.19233-1-sol%40solfisher.com%3E&subject=Re%3A%20%5BPATCH%20tenacity%5D%20Use%20scdoc%20for%20man%20page%20generation).

**Comment by fossdd** [comment]
Agree, with scdoc

**Comment by nbsp** [comment]
Closed in 31fbfeec5245c8371ae1179978d5408b5b2f7e51

**Comment by nbsp** [comment]
The Ubuntu build looks for the processed manpage, and fails because it can't find it. I don't see why you'd need to use the manpage in CI? We should either remove it from the build or add `scdoc < tenacity.1.scd > tenacity.1`, neither of which I know how to do.

**Comment by ghost** [comment]
Can you fix the manual while you're at it?
Options should have two variants eg, "-v --version" ... not just "-version" with a single dash.
Trivial error I know but...
The original (man audacity) was wrong too.

**Comment by nbsp** [comment]
> Can you fix the manual while you're at it?
> Options should have two variants eg, "-v --version" ... not just "-version" with a single dash.
> Trivial error I know but...
> The original (man audacity) was wrong too.

I deliberately haven't touched the manual itself, fixing it would warrant a separate commit. Feel free to fix it and send a PR.
