### ISSUE TITLE
Tenacity's configuration folder is called audacity.cfg

### ISSUE THREAD

**Issue by petersampsonaudacity** [tenacityteam/tenacity-legacy#362]
- [x] I have read the specified guidelines for issues

**Describe the bug**
Tenacity's configuration folder is called audacity.cfg.  

It does however reside in a renamed folder "Tenacity"

**To Reproduce**
1. Run Tenacity 3.0.4
2. Launch Windows Explorer
3. Navigate to C:\Users\<_your-username_>\AppData\Roaming\Tenacity
4. Observe the configuration file is called "audacity.cfg

**Expected behavior**
I expect the configuration file to be called "tenacity.cfg" 

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/126863652-2bec1a97-3f7a-4470-b0ca-c3b6dc5f653b.png)

**Additional information (please complete the following information):**
 - OS: tested on W10 - but assume all OS
 - Version Tenacity 3.0.4

**Additional context**
It is good that the settings folder is renamed to Tenacity as that avoids Tenacity interfering with a user's Audacity settings and vice versa (this is what I was testing when I discovered this bug).

**Comment by fossdd** [comment]
These files contains `audacity.cfg`:

```
[admin@main tenacity]$ grep -airn audacity.cfg
src/ProjectSettings.cpp:76:      // an entry for the default sample rate in audacity.cfg, Audacity can open
src/AudacityApp.cpp:1200:        wxFileName configFileName(FileNames::DataDir(), wxT("audacity.cfg"));
src/widgets/FileConfig.h:50:   // Set and Get values of the version major/minor/micro keys in audacity.cfg when Audacity first opens
src/widgets/FileConfig.h:93:   // values of the version major/minor/micro keys in audacity.cfg
src/commands/CommandManager.cpp:1611:// of these is changed, then if /GUI/Shortcuts/FullDefaults is not set in audacity.cfg,
src/commands/CommandManager.cpp:1612:// because the defaults appear as user assigned shortcuts in audacity.cfg,
src/toolbars/ToolManager.cpp:746:   // note that vMajor, vMinor, and vMicro will all be zero if either it's a new audacity.cfg file
src/toolbars/ToolManager.cpp:748:   // InitPreferences()). So for new audacity.cfg
src/toolbars/ToolManager.cpp:857:         // the space for the extra button is stored in audacity.cfg, and so you get an extra space
src/effects/TruncSilence.cpp:144:   // This used to be changeable via the audacity.cfg/registry.  Doubtful that was
```

I've replaced all and sent an patch in: https://lists.sr.ht/~tenacity/tenacity-dev/patches/23970

**Comment by petersampsonaudacity** [comment]
Testing on W10 with tenacity-win-3.0.4-alpha+047b6be-amd64

I confirm that this is fixed - thanks :-)
