### ISSUE TITLE
Tenacity prevents Audacity from launching (and vice versa)

### ISSUE THREAD

**Issue by petersampsonaudacity** [tenacityteam/tenacity-legacy#364]
- [x ] I have read the specified guidelines for issues

**Describe the bug**

**To Reproduce**
1. Launch Tenacity 3.0.4 alpha
2. attempt to launch Audacity 3.0.2
3. Observe: Error Message "Audacity is already running ..."

**Expected behavior**
Tenacity and Audacity should be totally independent apps with both capable of being run simultaneously.

**Screenshots**
![image](https://user-images.githubusercontent.com/50205984/126864537-923c33f8-50bb-4a4f-ba37-94b71be0bbca.png)

**Additional information (please complete the following information):**
 - OS: Windows 10 - but assume all OS
 - Version Tenacity 3.0.4 alpha

**Additional context**
If you do this the other way around launching Audacity first the Tenacity shows the message "Tenacity is already running ..."

**Comment by Sciss** [comment]
Probably here: https://github.com/tenacityteam/tenacity/blob/79d7db6aa7db584f91478a2a92137b6ee53c813f/src/AudacityApp.cpp#L1630 - and change the name of the lock file to use `tenacity` instead of `audacity`

**Comment by rubyFeedback** [comment]
May also have to rename the file. :)

(Weird CamelCase style name they used there by the way...)

**Comment by nbsp** [comment]
What's the status of this? The config directories [have been changed](https://github.com/tenacityteam/tenacity/issues/378), as has the [desktop entry name](https://lists.sr.ht/~tenacity/tenacity-dev/patches/23969), and I can run both applications together [just fine](https://i.imgur.com/u6vr0BW.png).

**Comment by n0toose** [comment]
> I can run both applications together [just fine](https://i.imgur.com/u6vr0BW.png).

Yup, we fixed this.
