### ISSUE TITLE
Ubuntu CI build broken - missing tenacity.1

### ISSUE THREAD

**Issue by Sciss** [tenacityteam/tenacity-legacy#367]
- [X] I have read the specified guidelines for issues

**Describe the bug**

Seems the deletion in https://github.com/tenacityteam/tenacity/commit/31fbfeec5245c8371ae1179978d5408b5b2f7e51 is causing build problems: https://github.com/tenacityteam/tenacity/pull/366/checks?check_run_id=3150535166 (#366)

**Additional information (please complete the following information):**
 - GitHub CI Ubuntu job

**Comment by fossdd** [comment]
Yes, it is already being fixing with https://github.com/tenacityteam/tenacity/pull/365
