### ISSUE TITLE
Logo - offering to help.

### ISSUE THREAD

**Issue by rolandixor** [tenacityteam/tenacity-legacy#37]
Hi, I'm a designer go would be glad to help, and contribute a logo to the project, free of cost, once a name has been decided.

My website: https://rolandixor.pro

**Comment by sodahead** [comment]
No need kind stranger, for I have already made the logo.

![sneedacity](https://user-images.githubusercontent.com/64686518/124522762-08db8280-ddfd-11eb-8bb7-6f8c09e65d6d.jpg)

**Comment by rolandixor** [comment]
Serious question, is this for real? I was hoping a fork would modernize Audacity's look, which is severely needed.

**Comment by emanuelserpa** [comment]
> Serious question, is this for real? I was hoping a fork would modernize Audacity's look, which is severely needed.

No.

**Comment by Sciss** [comment]
>  is this for real

No, there is currently a wave of troll kiddos trying to throw mud, pepe frogs, n words etc. around. Just ignore them for now, I think it's in the process of taking out the trash. Thanks for offering your help.

![Screenshot from 2021-07-06 01-31-18](https://user-images.githubusercontent.com/131300/124524094-e98f2600-ddf9-11eb-865e-7512b590346b.png)

**Comment by JPcode05** [comment]
> Serious question, is this for real? I was hoping a fork would modernize Audacity's look, which is severely needed.

Maybe in a later version. It takes time to update the look, which includes switching from wxWidgets to Qt and from C/C++ to Rust.

**Comment by JPcode05** [comment]
> **[_Quote of deleted comment removed by moderator_]**
>
That is still a trademark infringement as it is based on the Audacity logo, which is also trademarked by Muse Group.

**Comment by PF94** [comment]
> 
> 
> **[_Quote of deleted comment removed by moderator_]**
> That is still a trademark infringement as it is based on the Audacity logo, which is also trademarked by Muse Group.

also it's some simpsons joke.

**Comment by emabrey** [comment]
> 
> 
> > Serious question, is this for real? I was hoping a fork would modernize Audacity's look, which is severely needed.
> 
> No.

It is not real. Sorry for any confusion, we are working on clearing up SPAM and other trademark violating images etc. as they come in.

**Comment by EricBright** [comment]
Please kindly direct your name suggestions to #33 and your logo re-design suggestions, if any, to #12.

Thank you! :)

P.s. I think this issue can be closed.

**Comment by EricBright** [comment]
Closed as duplicate of #12.

**Comment by rolandixor** [comment]
> > Serious question, is this for real? I was hoping a fork would modernize Audacity's look, which is severely needed.
> 
> Maybe in a later version. It takes time to update the look, which includes switching from wxWidgets to Qt and from C/C++ to Rust.

Has any of this been decided, officially? Or are you just speculating? (with the switch to Qt+Rust?) the latter especially seems like a leap of faith lol.

**Comment by rolandixor** [comment]
> > is this for real
> 
> No, there is currently a wave of troll kiddos trying to throw mud, pepe frogs, n words etc. around. Just ignore them for now, I think it's in the process of taking out the trash. Thanks for offering your help.
> 
> ![Screenshot from 2021-07-06 01-31-18](https://user-images.githubusercontent.com/131300/124524094-e98f2600-ddf9-11eb-865e-7512b590346b.png)

Thanks. I figured it must be part of that.
Glad I missed the n-word crap. The frogs are bad enough.
