### ISSUE TITLE
Add commit style to CONTRIBUTING.md

### ISSUE THREAD

**Issue by AnotherFoxGuy** [tenacityteam/tenacity-legacy#375]
I think it would be a good idea to define and add a unified commit style for the git commit messages, since atm everyone uses his own style 

Examples: 
https://github.com/RigsOfRods/rigs-of-rods/wiki/Commit-style
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by fossdd** [comment]
Not sure if this is really needed. If everyone uses it's own style, that it's so imo.

**Comment by nbsp** [comment]
We already have one. Right now we have this:

> Make concise and accurate commit messages. A commit message should be limited to 50 characters and its description limited to 72 characters per line, and the message should be able to complete this sentence:
> > This commit will...

In my opinion, this is good enough. Although it doesn't cover the use of emoji, one can take a look at the commit history and see how things are being done (that's a great idea regardless).

One guide I personally follow is Drew DeVault's [*Tips for a disciplined git workflow*](https://drewdevault.com/2019/02/25/Using-git-with-discipline.html). It explains the 50/72 character limit, the "one fix per commit" rule, and the use of `git rebase` to "never make a mistake".

**Comment by emabrey** [comment]
I try to follow this: https://chris.beams.io/posts/git-commit/

**Comment by AnotherFoxGuy** [comment]
I personally use [gitmoji](https://gitmoji.dev/) for my commit messages
