### ISSUE TITLE
Zlib or Conan error, Windows 10

### ISSUE THREAD

**Issue by HopperMCS** [tenacityteam/tenacity-legacy#39]
Just tried compiling on Windows 10 with the recommended build tools, versions, etc that are in the build guide. A friend wanted me to compile this for him and I got this error while configuring a VS project in cmake-gui:

```
ERROR: zlib/1.2.11: Cannot load recipe.
Error loading conanfile at 'C:\Users\gagem\.conan\data\zlib\1.2.11\_\_\export\conanfile.py': Unable to load conanfile in C:\Users\gagem\.conan\data\zlib\1.2.11\_\_\export\conanfile.py
  File "C:\Users\gagem\.conan\data\zlib\1.2.11\_\_\export\conanfile.py", line 47
    tools.get(**self.conan_data["sources"][self.version], destination=self._source_subfolder, strip_root=True)
                                                        ^
SyntaxError: invalid syntax


CMake Error at cmake-proxies/cmake-modules/conan.cmake:631 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:233 (conan_cmake_install)
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:251 (_conan_install)
  CMakeLists.txt:509 (resolve_conan_dependencies)


Configuring incomplete, errors occurred!
See also "C:/Users/gagem/Documents/audacity-build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/gagem/Documents/audacity-build/CMakeFiles/CMakeError.log".
```

**Comment by Ristellise** [comment]
For conan, I believe you need python 3.8 or a relatively recent python installation. I didn't have any issues while trying to build it other than a stray `#endif` preventing compilation which I PRd a while back.

**Comment by ghost** [comment]
No, it is sufficient to install Python 3.5 for conan to work, as it is written in the official conan documentation.

**Comment by amrithmmh** [comment]
@GageFrancisHopper please make sure the python used is python 3 and not python 2.
it's better to use it in a virtualenv with python3

**Comment by Kid0h** [comment]
I have Python 3.8.1 and I'm still having issues.

**Comment by anpin** [comment]
I've fixed my issues with conan by adding cmake bin folder to PATH

**Comment by AnotherFoxGuy** [comment]
You can also download an installer for Conan instead of using pip: https://conan.io/downloads.html

**Comment by Be-ing** [comment]
Conan was removed in #228
