### ISSUE TITLE
Publish on FossHub and permission request

### ISSUE THREAD

**Issue by FossHub** [tenacityteam/tenacity-legacy#395]
Hello,

Following the feedback we received from our users, we would like to ask for your permission to publish Tenacity on FossHub Audio-Editors category: https://www.fosshub.com/Audio-Editors.html

We have been the official Audacity mirror for the last seven years. The previous Audacity team maintained the release process. We are more than happy to provide the credentials to any official Tenacity maintainer. Otherwise, we will take care, assuming that we have Tenacity permission.

Thank you!
FossHub team

**Comment by Semisol** [comment]
I would first like to confirm that this account is owned by fosshub.com.
If possible, can an email be sent to `semisol at tenacityaudio dot org` from an e-mail address from the FossHub, proving the ownership of this GH account?
If there is another way that the account ownership can be proven if you can't send an e-mail, that would be appreciated.

**Comment by FossHub** [comment]
Hello,

Email sent, thank you!

**Comment by Semisol** [comment]
Thanks for verifying. I think we will take it, but I'll forward it to the team to be sure. Have a nice day.

**Comment by Semisol** [comment]
I think we will accept, but we would like to not publish until our first stable release. Thanks for reaching out 👋
Also, is there any place I can submit feature requests? I would like to see a feature for requiring signatures for uploads, as we plan on using them.
If any other admins have different thoughts, please lmk.

**Comment by FossHub** [comment]
Hello,

You can submit a feature request, but you need to be a project member (or via our email address). A project can have one or multiple users. As for the signature for uploads? We show the file signature of each file on the project page. Just click on the "Signature" link, and it will reveal the MD5/SHA1/SHA256 of that specific file.

https://www.fosshub.com/Audacity.html

You can also provide the PGP signature along with the file signature. Here's a project that does this: 
https://www.fosshub.com/qBittorrent.html

Having the file signatures in two separate locations will provide better security, just in case one location is being compromised. This assumption is based on the fact that the original provider of the file has not been compromised.

We can be wrong, but if you have a better idea, we are open to suggestions for security. Thank you!

**Comment by Semisol** [comment]
@FossHub Thanks for the response! We will be uploading PGP signatures and will try to publish hashes & the pubkey somewhere else too to avoid a single point of failure.

**Comment by FossHub** [comment]
Just in case my message was not clear enough. We show the file signatures automatically. The only ones (obviously) that you need to upload are the PGP's. If you can publish them on your official website or somewhere else, that would be great. This way, the users can compare them, and they need to see the same result each time.

Certainly not to brag, but one of the advantages of publishing files on FossHub is that (since 2018) we also implemented several automated security measures. We cannot disclose the entire process ([some info was made public](https://blog.fosshub.com/how-safe-is-fosshub/)) but the benefit for the project is that you can prevent specific attacks. We've alerted a few project owners when their websites were hacked, and thanks to the new security measures, no malware was delivered.

**Comment by Semisol** [comment]
I'll look into that link. Thanks!

**Comment by Semisol** [comment]
I have sent some things to the e-mail you verified with.

**Comment by Semisol** [comment]
Accounts have been created, no release is available yet + the page is unlisted.
