### ISSUE TITLE
Sync-lock improvements

### ISSUE THREAD

**Issue by akleja** [tenacityteam/tenacity-legacy#401]
- [x] I have read the specified guidelines for issues

**Is your feature request related to a problem? Please describe.**
When editing with sync-lock enabled, it would be good to have a quick way of bypass it for minor edits, see https://github.com/tenacityteam/tenacity/discussions/388

**Describe the solution you'd like**
* Hold a modifier key to temporary override sync-lock
* Improve the visual representation of the synced tracks. Perhaps a patterned background of diagonal lines instead of the symbols

**Comment by petersampsonaudacity** [comment]
Earlier Audacity used chains (arranged diagonally) instead of the clocks - I, personally, much preferred the chains.

**Comment by akleja** [comment]
I think I remember those! I've made the bitmaps tile without spacing, so bringing back the chains would be possible.
