### ISSUE TITLE
Suggestion/Feature Request to support lv2 plugins on Windows

### ISSUE THREAD

**Issue by Reaper10** [tenacityteam/tenacity-legacy#411]
This is lv2 plugins on windows

- [ X] I have read the specified guidelines for issues

**Is your feature request related to a problem? Please describe.**

This is a way to add support for lv2 plugins on windows.

Steps to to add support for lv2 plugins on windows.
1. Nyquist plug and cabined with Ladspa into one api. 
2. Then take the new cabined api and cabined  DSSI into one api. 
3.  add cv support
4. support for Lv2 extension

**Describe alternatives you've considered**

[you could use lmms way of doing ](https://github.com/LMMS/lmms/projects/10#card-19782392)

**Additional information on the other APIs:**
[LADSPA](http://www.ladspa.org/)
 [DSSI](http://dssi.sourceforge.net/)

**Additional context**
Why this would be good? It would add a lot more more plug-ins window could. Tenacity could built them in windows as native plugins.

**Comment by Be-ing** [comment]
We don't need to ship them with Tenacity. They are available from [PawPaw](https://github.com/DISTRHO/PawPaw/releases).

**Comment by petersampsonaudacity** [comment]
Audacity's website staes on this page: https://www.audacityteam.org/download/plug-ins/

>LV2 Plug-ins
>
>Audacity has built-in support for LV2 plug-ins, which are an extensible successor of LADSPA effects. 
>LV2 plug-ins are mostly built for Linux, but Audacity supports LV2 on all operating systems. 
>To install LV2 plug-ins, place them in the system LV2 location then use the Plug-ins Manager to enable the new 
>plug-ins as in the plug-in installation instructions.

And the Effects preferences has a checkbox for enabling LV2 (default ="on")
![image](https://user-images.githubusercontent.com/50205984/127863650-63cf79f7-5efa-4b85-a6ac-ae2794929a2a.png)

**Comment by Semisol** [comment]
Since Tenacity is an Audacity fork, we still have LV2:
![image](https://user-images.githubusercontent.com/45574030/127866814-c908db1c-007a-4d64-9436-51e431594506.png)

**Comment by Reaper10** [comment]
That may be true but but there there's vl2 plugins built in on window

**Comment by Reaper10** [comment]
I'd love to see [Infamous Plugins](http://ssj71.github.io/infamousPlugins/) built in.

**Comment by Semisol** [comment]
I don't think we will be packaging any plugins with Tenacity.

**Comment by Reaper10** [comment]
> I don't think we will be packaging any plugins with Tenacity.

just an idea
