### ISSUE TITLE
Copious memory leaks during record and playback

### ISSUE THREAD

**Issue by Paul-Licameli** [tenacityteam/tenacity-legacy#416]
- [ ] I have read the specified guidelines for issues

**Describe the bug**
Pull request #412 introduced what could be a serious memory leak during recording and playback.

You would have known it soon enough in testing.

I did not test Tenacity.  I knew it from inspection of the source code.

Update:  Actually, it won't leak memory during recording -- unless you do overdub.  But it will happen during playback.

**To Reproduce**
Record or generate some sound.
Select it, and play it back in a loop (Shift + Space).
Open macOS Activity Monitor, or Windows Task Manager, or similar utility.
Observe memory consumption of Audacity.  Write down that number.
Go to bed.
Wake up.
Compare with current readout, if the program is still running.

**Expected behavior**
I haven't actually done this experiment.  But I predict an unhappy surprise.

**Screenshots**
None

**Additional information (please complete the following information):**
 - OS: All
 - Version: Since 047729727a841a53bb13c2791912ae154593115d

**Additional context**
None

**Comment by Semisol** [comment]
I have edited the issue to fill in some fields, please check the "I have read the guidelines box" yourselves after reading the comment at the top of the template. Thanks!
For reference:
```
<!--
IMPORTANT! READ

Any spam issues will be deleted.
Issues are not a place to go ask support questions.

Please post **confirmed** bugs when possible.

Please mark the checkbox below (Use "x" to fill the checkboxes, example: [x])
-->
```

**Comment by Paul-Licameli** [comment]
You’re welcome.  Abundantly welcome.

**Comment by RoaddogLabs** [comment]
We’ve noticed no appreciable impact with a typical use case.  When we encounter an audio processing app (or embedded hardware) with a considerable leak it eventually it crashes or slows so much it’s not usable.  In professional use we haven’t yet found this to be the case even in systems with 8GB RAM.

As end users what should we be looking for in terms of performance that may not be apparent in the normal use case of the program?

**Comment by caughtquick** [comment]
> You’re welcome.  Abundantly welcome.

What would be nice would be actually following the issue template, rather than making mocking statements.

**Comment by emabrey** [comment]
> 
> 
>     * [ ]  I have read the specified guidelines for issues
> 
> 
> **Describe the bug**
> Pull request #412 introduced what could be a serious memory leak during recording and playback.
> 
> You would have known it soon enough in testing.
> 
> I did not test Tenacity. I knew it from inspection of the source code.
> 
> **To Reproduce**
> None
> 
> **Expected behavior**
> None
> 
> **Screenshots**
> None
> 
> **Additional information (please complete the following information):**
> 
>     * OS: All
> 
>     * Version: Since [0477297](https://github.com/tenacityteam/tenacity/commit/047729727a841a53bb13c2791912ae154593115d)
> 
> 
> **Additional context**
> None

I did test for memory leaks. I didn't see any. I'll run it through valgrind and/or MSVC Performance Profiler/Debug.

**Comment by Paul-Licameli** [comment]
> > You’re welcome.  Abundantly welcome.
> 
> What would be nice would be actually following the issue template, rather than making mocking statements.

Very well, I'll amend my report and be "nice."  You're welcome again.

**Comment by Paul-Licameli** [comment]
> 
> I did test for memory leaks. I didn't see any. I'll run it through valgrind and/or MSVC Performance Profiler/Debug.

My friend, you are relying too much on the tools and too little on your own capacity to reason.

**Comment by emabrey** [comment]
> 
> 
> > I did test for memory leaks. I didn't see any. I'll run it through valgrind and/or MSVC Performance Profiler/Debug.
> 
> My friend, you are relying too much on the tools and too little on your own capacity to reason.

It was just an oversight where I incorrectly read `delete[] x` as recursively de-allocating as oppossed to only de-allocating the top-level. I pulled out the tools because I had misread things once, so it's best to take out subjectivity.

**Comment by Paul-Licameli** [comment]
> > > I did test for memory leaks. I didn't see any. I'll run it through valgrind and/or MSVC Performance Profiler/Debug.
> > 
> > 
> > My friend, you are relying too much on the tools and too little on your own capacity to reason.
> 
> It was just an oversight where I incorrectly read `delete[] x` as recursively de-allocating as oppossed to only de-allocating the top-level. I pulled out the tools because I had misread things once, so it's best to take out subjectivity.

C++ will not recursively delete things that you have allocated with "naked" new.

But C++ DOES compose destructors for you in useful ways.  When a class has base classes or members of types that have nontrivial destructors, then the class has a generated destructor that does the recursive cleanup automatically.  If you make an explicit destructor, you only write the extra cleanup actions special to the class, which execute before other cleanups.

Good modern C++ uses this to advantage.  Use "smart" pointers that have nontrivial destructors which take care of deletions.  Compose your classes with smart pointer members.  Manage instances of your class with smart pointer variables that point to them -- or just put the instances in local, stack-allocated variables when you can.

Remember these things and it is very easy to write leak-free C++, contrary to much rumor.
