### ISSUE TITLE
Audacity featured on Virtual Legality

### ISSUE THREAD

**Issue by IanTrudel** [tenacityteam/tenacity-legacy#42]
> Virtual Legality has become (a bit) known for our deep dives into terms of service, data policies, and the like, so it was no surprise when a number of folks reached out to ask about a privacy policy change covering open source audio capture application "Audacity".  

https://www.youtube.com/watch?v=noQJNLsS3zw

**Comment by l0go** [comment]
I don't see why this is worth an issue.

**Comment by EricBright** [comment]
Can be closed.

**Comment by emabrey** [comment]
We need to get a discussion tab setup. Once we do this kind of content is appreciated, but it isn't really issue material. Thank you for the relevant information however, and please feel free to contribute in other ways.
