### ISSUE TITLE
Track move when you delete a track

### ISSUE THREAD

**Issue by ghost** [tenacityteam/tenacity-legacy#428]
**Describe the solution you'd like**
![untitled](https://user-images.githubusercontent.com/67544305/127876447-a48648a1-7993-4679-a57b-5ac48bccd1c9.GIF)

**Additional context**
When you delete the part of the track it well more a space

**Comment by nbsp** [comment]
Please follow the template for opening issues.

**Comment by Semisol** [comment]
Also, I could not understand what you want 100%, so it isn't too editable to fit the template.
