### ISSUE TITLE
use of deprecated std::uncaught_exception

### ISSUE THREAD

**Issue by Be-ing** [tenacityteam/tenacity-legacy#432]
This warning repeatedly spams the log when building Tenacity:

```
../src/import/../AudacityException.h: In lambda function:
../src/import/../AudacityException.h:214:20: warning: ‘bool std::uncaught_exception()’ is deprecated [-Wdeprecated-declarations]
  214 |          if (!std::uncaught_exception()) {
      |                    ^~~~~~~~~~~~~~~~~~
```

**Comment by Paul-Licameli** [comment]
Aww, don’t close it.

It’s just a one character fix.

Upstream thanks you for this alert.

https://en.cppreference.com/w/cpp/error/uncaught_exception

**Comment by Semisol** [comment]
We fixed it..?
![image](https://user-images.githubusercontent.com/45574030/129494338-0e226255-ad26-4ddb-852c-9877f3a9073a.png)

**Comment by Paul-Licameli** [comment]
> We fixed it..?
> ![image](https://user-images.githubusercontent.com/45574030/129494338-0e226255-ad26-4ddb-852c-9877f3a9073a.png)

So you did.  My mistake.

**Comment by Semisol** [comment]
> So you did. My mistake.

Yeah, it helps to check the close message & if the issue was mentioned somewhere which GH shows (linked pull requests).
