### ISSUE TITLE
Make u/bascurtiz’s Audition Dark theme the main theme for Tenacity

### ISSUE THREAD

**Issue by RagglenLove** [tenacityteam/tenacity-legacy#442]
**Is your feature request related to a problem? Please describe.**

![127778318-62e2dbd5-3569-4d1a-b698-ec9556a7b292](https://user-images.githubusercontent.com/45503845/128645560-ff411655-1521-4432-a530-b6a800efa2ca.png)

The default theme of Tenacity is straining for the eyes.

**Describe the solution you'd like**

![9xd9i52dz0f71](https://user-images.githubusercontent.com/45503845/128645807-8c969804-e329-4387-8c0f-594e8e709dfa.jpg)

Make [u/bascurtiz](https://www.reddit.com/user/bascurtiz/)’s Audition Dark theme for Audacity the main theme for Tenacity. Redditor u/bascurtiz's theme is easier on the eyes.

**Describe alternatives you've considered**

**Additional context**

Here's the link to the u/bascurtiz's reddit post: https://www.reddit.com/r/audacity/comments/owq5zl/audition_dark_theme_for_audacity/

And here's the download link: https://drive.google.com/file/d/14eBPLcTrvbMStoxY286oPg1WLef3zm9e/view?usp=sharing

**Comment by Semisol** [comment]
Related to: #178, selecting themes based on OS setting

I appreciate you want to suggest a theme. We will look into how we can do this, but the theme author will need to license the theme under GPL-2 for this to work.

small thing: We might not make this the default theme, we don't know.

**Comment by akleja** [comment]
@RagglenLove You know we already have a dark theme integrated right?
![](https://raw.githubusercontent.com/tenacityteam/assets/master/screenshots/tenacity-screenshot-dark-3840x2160.png)

**Comment by rubyFeedback** [comment]
I do not think it should be the default; taste is different. IMO it may be better to simply come with some themes bundled, say perhaps 5 or 6 different, and let the users choose on their own in a simple way. So perhaps just needs more documentation and a theme switcher (I never actually even bothered to look ... it's just not really concerning me when I want to modify audio content, then a theme is secondary to that objective).

**Comment by akleja** [comment]
What we could do fairly easily is make the theme switch based on system theme. And also improve the code for matching the colors to the system theme, which is really lacking currently.

The whole theme engine needs an overhaul as well. What I see as ideal is to base everything on a base color and a contrast value, and the rest is calculated from there. Then it would be easy to adjust to taste.

Expanding upon the feature of loading custom bitmap based themes is not something I see as the best path forward.

**Comment by RagglenLove** [comment]
> @RagglenLove You know we already have a dark theme integrated right?
> ![](https://raw.githubusercontent.com/tenacityteam/assets/master/screenshots/tenacity-screenshot-dark-3840x2160.png)

No, I didn't know this, actually I don't have Tenacity installed on my system because I don't know how to compile software from source, so most of what I know of Tenacity comes from screenshots and testimonials from other users.

Where can I get the ImageCache.png of this theme so I can check it out on my Audacity install here? Thanks.

> What we could do fairly easily is make the theme switch based on system theme. And also improve the code for matching the colors to the system theme, which is really lacking currently.

Back in 2012, when I was using Ubuntu 12.04, I seem to recall Audacity was able to theme itself to the system theme back then, so when I used a dark mode theme, Audacity would be in the same color theme. I’m not sure what changed from back and and now though.

**Comment by vchernin** [comment]
> @RagglenLove You know we already have a dark theme integrated right?
> ![](https://raw.githubusercontent.com/tenacityteam/assets/master/screenshots/tenacity-screenshot-dark-3840x2160.png)

That screenshot was taken on Linux, which has many tools for customizing themes. That screenshot was using Tenacity’s current dark mode in addition to the “HighContrastInverse” system theme available on Fedora. Those instructions simply don’t apply to windows or macos.

I think an improved Tenacity dark mode by default is definitely warranted for all operating systems.

For reference this is what Tenacity looks like with its dark mode and the Adwaita system theme (a Linux vanilla “standard” of sorts):
![](https://user-images.githubusercontent.com/38842733/128233938-d6df641a-e3a0-463b-8273-4a72f22e7401.png)

For more context: https://github.com/tenacityteam/assets/pull/4

**Comment by akleja** [comment]
Yeah we'll have to do something about those drop down controls as soon soon as possible

**Comment by n0toose** [comment]
@RagglenLove See https://github.com/tenacityteam/tenacity/issues/393 if you want to try out the latest build of Tenacity.

**Comment by n0toose** [comment]
I seriously think it's a ***very*** bad idea to just make Tenacity an Audition copycat. Adobe obviously spends millions on getting GUI and color schemes right, so it may a good idea to take inspiration from them. For instance, making the control buttons monochrome seems like a decent idea to me. However, we can come up with things on our own as well.

**Comment by n0toose** [comment]
Closing this until we have an update from u/bascurtiz.

**Comment by bascurtiz** [comment]
@RagglenLove @panos @akleja @vchernin @rubyFeedback @Semisol 
Uh, I never received a message, cause u guys refering to /u/bascurtiz instead of @bascurtiz lol.
But feel free to play around with the theme if you like.

Meanwhile I'm busy at the neighbors: https://github.com/SartoxOnlyGNU/audacium/issues/47

**Comment by fitojb** [comment]
I’d favor a default-dark UI. Other professional creator software, like (the already mentioned) Adobe Suite, Affinity, the GIMP, Microsoft VSCode and Expression Studio, etc., uses dark schemes by default.

**Comment by akleja** [comment]
Before considering having the dark theme as default we'll have to do something about the drop downs that are drawn by the system.
We'll have to either make custom widgets for those or move the functionality out of the toolbars.
The snapping settings could be in a button with a popup menu.
The selection toolbar display settings could be included in the context menu, and the sample rate should probably go in prefs>device settings.
I'm working on the device toolbar, but haven't started on the others.

**Comment by RagglenLove** [comment]
> @RagglenLove See #393 if you want to try out the latest build of Tenacity.

@panos: I don't know how to compile software from source, unfortunately.

> @RagglenLove @panos @akleja @vchernin @rubyFeedback @Semisol
> Uh, I never received a message, cause u guys refering to /u/bascurtiz instead of @bascurtiz lol.
> But feel free to play around with the theme if you like.
> 
> Meanwhile I'm busy at the neighbors: SartoxOnlyGNU/audacium#47

@bascurtiz: My bad, I didn't know you had a github account.

> Closing this until we have an update from u/bascurtiz.

@panos: Please open this issue up again since @bascurtiz has given us an update. Thank you.
