### ISSUE TITLE
Dialog button icons broken on Linux build

### ISSUE THREAD

**Issue by juozaspo** [tenacityteam/tenacity-legacy#446]
- [x] I have read the specified guidelines for issues

**Describe the bug**
Dialog button icons appears to be broken on tenacity built from source on Ubuntu Linux 20.04 LTS running with Xfce 4.14. Terminal shows warnings about some png icon files that failed to load (Invalid IHDR data)

**To Reproduce**
1. Build tenacity from source according to Linux build instructions while on Ubuntu 20.04 LTS
2. Run in portable mode (create `Portable Settings` folder in executable directory, run executable) while using Xfce 4.14 desktop, with xubuntu (elementary xfce) icon theme as current icon theme
3. Observe broken icons shown on dialog buttons
4. See a warning about png files that cannot be loaded shown in terminal (Invalid IHDR data)

**Expected behavior**
Dialog icons appears correctly, no warnings in terminal

**Screenshots**
![Welcome to Tenacity! 2021-08-09 10:07:42](https://user-images.githubusercontent.com/6626242/128671482-bb735e1d-ee0d-49dc-9897-b118c9ef4e6a.png)
![Preferences: Devices 2021-08-09 10:08:18](https://user-images.githubusercontent.com/6626242/128671496-3a563ac0-5a05-44bc-8f77-a1586623c65d.png)

**Additional information (please complete the following information):**
 - OS: Ubuntu Linux 20.04 LTS, 64 bit
 - Version 3.0.3 (1fb034ce3aa26e323b0f58a8344a0542e30d794b)

**Additional context**
python 3.8.10
conan 1.38.0
cmake 3.16.3
libgtk2.0-dev 2.24.32-4ubuntu4
libasound2-dev 1.2.2-2.1ubuntu2.4
libavformat-dev 7:4.2.4-1ubuntu0.1
libjack-jackd2-dev 1.9.12~dfsg-2ubuntu2
uuid-dev 2.34-0.1ubuntu9.1
gcc 9.3.0
ffmpeg 4.2.4
Build+Run log (15000+ lines): [tenacity.txt](https://github.com/tenacityteam/tenacity/files/6952814/tenacity.txt)

**Comment by akleja** [comment]
This seems to be a GTK issue due to missing icon cache that's probably a result of a system update
A possible solution:
https://petermolnar.net/article/solution-for-gtk-warning-error-loading-theme-icon/index.html

**Comment by juozaspo** [comment]
Tried this method (`for i in /usr/share/icons/*; do sudo gtk-update-icon-cache $i; done`), still broken. No icons for dialog buttons, running this command reports missing theme index files for some entries, running `sudo gtk-update-icon-cache elementary-xfce-darker` while in `/usr/shari/icons` dir returns no errors

**Comment by Be-ing** [comment]
Is this still an issue building with upstream wxWidgets 3.1.5 since #228 was merged?

**Comment by juozaspo** [comment]
No longer broken as of latest commit (13914c5125da4eab6f8ca68bddd5fdab71e30683), was able to compile properly with custom build of wxWidgets and forked PortSMF, also not installing libsbsms-dev, as the version including in Ubuntu might be broken, with my build workflow described in comments of #499. Dialog buttons render correctly.

**Comment by Be-ing** [comment]
Thanks for following up.
