### ISSUE TITLE
Replace Audacity branding in `mac` directory.

### ISSUE THREAD

**Issue by n0toose** [tenacityteam/tenacity-legacy#450]
### Discussed in https://github.com/tenacityteam/tenacity/discussions/441

<div type='discussions-op-text'>

<sup>Originally posted by **kirkmarkarian** August  8, 2021</sup>
Just that - I've still got the Audacity headphones for a launch icon.</div>

**Comment by petersampsonaudacity** [comment]
Tested on macOS 11.5.2 Big Sur with latest master build.

See the macOS DMG installer
<img width="1226" alt="Screenshot 2021-08-21 at 13 48 54" src="https://user-images.githubusercontent.com/50205984/130322393-311e034b-8c35-4e31-93b0-4a9869b1396f.png">

And even worse the Tenacity app icon on Mac is Audacity's icon
<img width="550" alt="Screenshot 2021-08-21 at 13 50 11" src="https://user-images.githubusercontent.com/50205984/130322412-0c56f07c-1909-45cb-811f-de41864b8b77.png">

**Comment by nbsp** [comment]
Closed in #537
