### ISSUE TITLE
Moderation of Contributions

### ISSUE THREAD

**Issue by emabrey** [tenacityteam/tenacity-legacy#46]
This setting is available at `.Settings/Moderation Settings/Temporary Interaction Limits` within the repository settings. We can try enabling it and seeing if it cuts down on the SPAM issues while I try to see if we can create a filter list for issues to cut down on the nonsense ones that are blank or just literally the template or just the offensive name the trolls currently favor (you know the one).

**Comment by ajayyy** [comment]
By the way, they said that they already tried this. The accounts are old, but just unused

**Comment by emabrey** [comment]
Ah, I'll update the issue to be more broad then. Brainstorming is welcome.

**Comment by emabrey** [comment]
Closing because people have been assigned to moderation, so we can look into this later if the additional moderators doesn't solve the issue. See #48.
