### ISSUE TITLE
Light Theme: Track Menu: The Menu blacks out when user clicks on the space below the track. 

### ISSUE THREAD

**Issue by TimothyPeterson** [tenacityteam/tenacity-legacy#467]
### Guidelines

- [X] I have read the guidelines.

### Describe the bug.

Go to Edit / Preferences / Interface / Theme / Light
Import a sound file
Click on the space below the track
The track menu items become black
The track menu items reappear on rollover
OR
Go to Edit / Preferences / Interface / Theme / Light
Click the record button
The track menu items become black
The track menu items reappear on rollover
![Track-Menu-Issue-LightTheme](https://user-images.githubusercontent.com/25409066/129078763-11892320-fa71-431c-a185-a762abfc60df.jpg)

### Expected behavior

Track menu items remain visible during all other interface usage.

### OS

Windows 10

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by n0toose** [comment]
Hey, thank you for going through the trouble of registering on GitHub and opening this issue, we just want to let you know that we appreciate your effort and that we're looking into it.

**Comment by akleja** [comment]
Oh I know about this, I'll try to get a fix out as soon as possible.
In the meantime it might help to uncheck "Blend system theme" in the interface prefs.

**Comment by TimothyPeterson** [comment]
Really exciting to see it develop!

**Comment by TimothyPeterson** [comment]
Thanks, that works!

**Comment by nbsp** [comment]
Resolved in #469
