### ISSUE TITLE
Get rid of GitHub Actions

### ISSUE THREAD

**Issue by n0toose** [tenacityteam/tenacity-legacy#477]
### Guidelines

- [X] I have read the guidelines.

### Is your feature request related to a problem? Please describe.

As a project, we are not strictly bound to GitHub, but we also accept patches on [SourceHut](https://git.sr.ht/~tenacity/tenacity). However, we've been mostly forced to use GitHub and its UI, which is very often counterintuitive for our needs, because it allows us to test against Windows and macOS environments.

We decided that our primary platform of choice would be SourceHut, but we're still being limited to GitHub because of its multifaceted tendency to force you to stay on their platform.

### Describe the solution you'd like

We should figure out which alternative to use. It should ideally be free.

### Describe alternatives you've considered

- SourceHut (builds.sr.ht) explicitly does not support proprietary platforms officially, but we can't just force everyone to move off them. That would be a deal breaker for the vast majority of our supporters, prospective users and current users. However, we should use it for obscure desktop platforms like FreeBSD and we should keep our Arch Linux CI.

### Additional context

To make things worse, we've resorted to temporarily using GitHub Actions for our nightly builds. See https://github.com/tenacityteam/tenacity/issues/393.

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by nbsp** [comment]
I wouldn't be opposed to self hosting macOS and Windows builds. We have the budget for that.

**Comment by n0toose** [comment]
> I wouldn't be opposed to self hosting macOS and Windows builds. We have the budget for that.

On a VPS or a machine of our own? I've seen huge security fails with self-hosted CI's and I'm worried about how we could possibly ensure that our builds will be clean and not tampered. Maybe we have to work on reproducibility a bit more.

**Comment by Be-ing** [comment]
Here are options for CI services for Gitea, from https://gitea.com/gitea/awesome-gitea#user-content-devops :
 * agola: Linux only
 * appveyor: no concurrent jobs for free. Paid plans are expensive for only 2 concurrent jobs.
 * AWS Cloud Integration(webhook-to-s3): gross, wouldn't be any better than using GitHub even if it met our technical needs
 * buildbot-gitea: works with Windows, don't think it works on macOS
 * buildkite-connector: agent works with Windows and macOS, however requires using their proprietary SaaS service to orchestrate self-hosted agents
 * Concourse: works with Windows and macOS. Unclear of the state of [Gitea support](https://github.com/concourse/concourse/issues/4681).
 * drone: works with Windows, don't think it works on macOS
 * Jenkins: works on Windows and macOS.
 * Metroline: Linux only
 * mvoCI: Linux only
 * woodpecker: Not sure about Windows? No macOS it seems.

GitLab CI also works on Windows and macOS. So it seems our options are:

  * Jenkins
  * Concourse?
  * buildkite: semi-proprietary SaaS :-1: 
  * GitLab CI: open core freemium :-1: 

Mixxx used to use Jenkins and it was way clunkier to use than GitHub Actions. Though I see Jenkins now has [Pipeline files](https://www.jenkins.io/doc/book/pipeline/getting-started/) that can be managed in the Git repository like any other CI service, so it may be worth considering more seriously.

Concourse seems like relatively immature software. I would be more comfortable going with something established like Jenkins, even if it is clunky.

**Comment by nbsp** [comment]
Codeberg is also working on CI, if I remember correctly.

Another point that's very important is the fact that currently, only builds.sr.ht works on email patches. This makes the mailing list effectively unusable for anything more than a documentation change, which is no better than removing it outright.
This isn't sourcehut's issue, I don't think: we should look for a CI service that integrates well with git on email.

**Comment by Be-ing** [comment]
> Codeberg is also working on CI, if I remember correctly.

Codeberg is just a Gitea host so everything in my comment above except for GitLab applies to Codeberg.

> we should look for a CI service that integrates well with git on email.

I do not know if such a software exists. If it does, I doubt it works with Windows or macOS.

**Comment by owenwastaken** [comment]
what about gitlab?

**Comment by Semisol** [comment]
> what about gitlab?

we already have GH and sourcehut, not a third one
also see https://github.com/tenacityteam/tenacity/issues/477#issuecomment-898413404

**Comment by Be-ing** [comment]
> I wouldn't be opposed to self hosting macOS and Windows builds. We have the budget for that.

Yeah, I think we could do self host CI with Jenkins. There are several conditions that need to be met though:
  * The machines need to be on a stable Internet connection. 
  * Whoever hosts the machines needs to be available to troubleshoot them and/or give others remote access to do so.
  * The operating systems and toolchains of the runners need to be kept up to date.

**Comment by nbsp** [comment]
On Fri Aug 13, 2021 at 5:08 PM IDT, Be wrote:
> * Whoever hosts the machines needs to be available to troubleshoot them
> and/or give others remote access to do so.

From a security standpoint, none of us can really be trusted. I'll try
contacting Fosshost and DigitalOcean to see if they can help us in any
way.

**Comment by Be-ing** [comment]
Fossshost [applications are currently suspended](https://fosshost.org/news/applications-temporarily-suspended). DigitalOcean doesn't run Windows or macOS.

**Comment by ghost** [comment]
Since github is the only alternative that actually gives the builds you need, with the security we all need (this project has a target painted on it) and the transparency users need (this project has a bumpy past), why not keep using it? For example, I know of a handful of projects which are primarily hosted (and by this I mean, that's the only place where issues/patches/etc occur) elsewhere (eg gitlab) but also mirror to here and build here.

I feel like this thread is trying to solve a problem but it's not actually been stated what the problem is. I get why you mightn't want the project to 'live' here, but why not build here? (edit for clarity: this isn't an argument, it's a genuine question)

**Comment by nbsp** [comment]
> I feel like this thread is trying to solve a problem but it's not
> actually been stated what the problem is. I get why you mightn't want
> the project to 'live' here, but why not build here?

The problem with GitHub Actions is that they're tied to GitHub. 
CI for contributions for Windows and macOS only works on PRs, rendering
the mailing list basically unusable except for small documentation
changes. By continuing to use GitHub CI, we are locked in.

**Comment by ghost** [comment]
Sorry I'm still not seeing it. Are you saying that the problem is that GH CI jobs wouldn't be automatically triggered if the commit was made elsewhere and mirrored here?

**Comment by nbsp** [comment]
The problem isn't with commits to master (or other branches), it's with
people sending in patches and PRs. patches are only tested against
builds.sr.ht, while PRs get both it and GitHub Actions tests.

That's because builds.sr.ht isn't tied directly to the rest of
sourcehut: you can use it wherever you want. GitHub Actions, on the
other hand, only works on GitHub.com.

**Comment by ghost** [comment]
Thanks for taking the time to explain it, now I get it :)

Would it be bad to be trapped on GH, for a very limited subset of purposes? That way, you could relax requirements on the other purposes.... Or are you keen to find a single solution for all purposes?

**Comment by Be-ing** [comment]
If we could get the build results of GitHub Actions automatically reported for branches elsewhere, that could work.

**Comment by n0toose** [comment]
> If we could get the build results of GitHub Actions automatically reported for branches elsewhere, that could work.

We could have a bot push proposed patches to GitHub branches, but that could possibly leave room for abuse.

**Comment by TrechNex** [comment]
I advise you to wait on creating a fully-free toolchain until your project is fully established and you have produced a binary release or two.

In these early stages you are going to see a high rate of churn with people rotating in and out of your project, and that's normal because Tenacity is new and exciting. However, if you rely on people donating infrastructure, you could find yourself in a bad situation quickly if any of that is withdrawn, or the person donating it to you loses interest and becomes uncontactable.

You also don't necessarily know how much funding you can consistently rely on each month to cover hosting costs, or who will be maintaining you self-hosted infrastructure 6, 12, or 18 months from now.

Your safest bet is to stick with GitHub Actions for now, because it is the lowest cost (in time & money) option. Your end users are unlikely to care which tools you used to deliver their solution, and it gives you more time to research your options and determine how to sustainably maintain your tools over the longer term.

**Comment by n0toose** [comment]
Reason why I set this to high priority is because "how are we going to compile all images, sign them, and then officially release them?". This *will* come back later and bite us one way or another.

Deciding that something isn't "high priority" without being fully aware as to why, say I, consider it high priority can be shortsighted sometimes and it feels like you're overriding your own judgement while dismissing mine. Let's just talk to each other, please.

**Comment by ghost** [comment]
>  This _will_ come back later and bite us one way or another.

Not to be rude but it's biting RIGHT NOW. As much as I appreciate your company, I'm not here for the laughs, people. I'm trying to find out how the **** I'm going to edit audio. I'm trying to figure out what to tell my friends to do about it when I tell them they can't use their old editor any more.....

I don't know either way. if getting rid of github actions is the way forward for that, but the whole consideration of the build process I'd agree is pretty high priority.

**Comment by n0toose** [comment]
Currently on a break, but we currently actually depend on GitHub Actions for builds, which you can find here: https://github.com/tenacityteam/tenacity/issues/393

@xcasxcursex

**Comment by Be-ing** [comment]
> Deciding that something isn't "high priority"

Let's get rid of the "high priority" label. It is a useless cause of arguments. Everyone has different priorities. I think the only priority distinction that matters is "release blocker" or "not release blocker".

**Comment by n0toose** [comment]
Yeah, you're absolutely right, deleting the high priority and going to use in-progress as a stand-in. Would fit in this situation here as well, because that's something we're actively deliberating.

**Comment by n0toose** [comment]
Good idea to close this.
