### ISSUE TITLE
Include Flatpak manifest in source code

### ISSUE THREAD

**Issue by TheEvilSkeleton** [tenacityteam/tenacity-legacy#493]
### Guidelines

- [X] I have read the guidelines.

### Is your feature request related to a problem? Please describe.

As discussed in #tenacity-dev on Libera Chat, we agreed on adding a manifest in the source code in JSON format.

### Describe the solution you'd like

Include a JSON Flatpak manifest.

### Describe alternatives you've considered

N/A

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by xTerma** [comment]
> ### Guidelines
> เปิดโหมดป้องกัน
> สวัสดีคุณ
> อยู่ด้วยกันนานๆนะ
> - [X] I have read the guidelines.
> 
> 
> 
> ### Is your feature request related to a problem? Please describe.
> 
> 
> 
> As discussed in #tenacity-dev on Libera Chat, we agreed on adding a manifest in the source code in JSON format.
> 
> 
> 
> ### Describe the solution you'd like
> 
> 
> 
> Include a JSON Flatpak manifest.
> แตะ
> ปิดลิ้งคำเชิญ
> 
> ### Describe alternatives you've considered
> 
> 
> 
> N/A
> 
> 
> 
> ### Additional context
> 
> 
> 
> _No response_
> 
> 
> 
> ### This issue is not a duplicate
> 
> 
> 
> - [X] I have confirmed this issue isn't a duplicate.
