### ISSUE TITLE
Recording volume slider stays locked until 'Record' is clicked

### ISSUE THREAD

**Issue by TimothyPeterson** [tenacityteam/tenacity-legacy#517]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

MSVC 19.29.30040.00

### Describe the bug.

Recording volume slider stays locked until 'Record' is clicked. 
It happens even when the meter is actively showing input volume. 
It doesn't matter if a track has been created or not.

![RecordingVolumeSlider](https://user-images.githubusercontent.com/25409066/130299124-88535674-c005-4545-a625-c9c4f2a77e3f.jpg)

### Expected behavior

For the input meter and input volume slider to work in unison.

### OS

Windows 10

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by akleja** [comment]
PortMixer isn't supported after the changes to the build system. This makes the volume sliders not do anything.
To resolve this issue there are a few alternatives.
* The sliders could be removed. Then it is up to the user to set the signals on their audio device.
* The sliders could be converted to software gain sliders. The disadvantage is that reducing the input levels this way wouldn't prevent clipping, and it would affect sound quality both during recording and playback. Having just a software slider for output could be an alternative.
* Restore compatibility with PortMixer.

I'm not sure which solution would be the best.

**Comment by n0toose** [comment]
I think this is a release blocker.

**Comment by Be-ing** [comment]
> The sliders could be removed. Then it is up to the user to set the signals on their audio device.

I think this is the best option. Of course it needs to be accompanied by documentation explaining it.

> The sliders could be converted to software gain sliders. The disadvantage is that reducing the input levels this way wouldn't prevent clipping, and it would affect sound quality both during recording and playback. Having just a software slider for output could be an alternative.

This is likely to be misused much more than used appropriately.

> Restore compatibility with PortMixer.

I think this is a bad idea unless someone volunteers to upstream Audacity's patches to PortAudio that are required for their fork of PortMixer to work, which they don't seem to be doing.

**Comment by akleja** [comment]
I agree with @Be-ing Be on this, but I'd be interested in hearing more opinions since this is a quite big change.

**Comment by nbsp** [comment]
While we're here, I also think the device selection dropdowns should be handled OS-side.

**Comment by akleja** [comment]
There's an ongoing discussion / redesign attempt regarding the device dropdowns in https://github.com/tenacityteam/tenacity/issues/435
