### ISSUE TITLE
The device drop-downs have become cropped

### ISSUE THREAD

**Issue by TimothyPeterson** [tenacityteam/tenacity-legacy#518]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

MSVC 19.29.30040.00

### Describe the bug.

The device drop-downs have become cropped as shown in the image. I know it's not a huge issue with everything else you wonderful people are working on, but trying to send all I can find.
![The-device-drop-downs-have-become-cropped](https://user-images.githubusercontent.com/25409066/130299582-7d2ca07e-d927-453a-9c7c-639ba7b0771b.jpg)

### Expected behavior

The device drop-downs clearly display full or near full device inputs

### OS

Windows 10

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by akleja** [comment]
I'm working on it in #435

**Comment by MSH4u** [comment]
Kello

**Comment by Phamhung177** [comment]
👍

**Comment by TimothyPeterson** [comment]
So sorry I missed that. "#435" Apologies.

**Comment by n0toose** [comment]
Closing as a duplicate.

**Comment by n0toose** [comment]
Also, no problem @TimothyPeterson! Thanks for helping us out. :D
