### ISSUE TITLE
Windows build is broken by missing `vamp-hostsdk.dll`

### ISSUE THREAD

**Issue by emabrey** [tenacityteam/tenacity-legacy#526]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

Audacity-2.4.1-1824-ge36e909

### Describe the bug.

1. Configure using `cmake -B build`
2. Build using `cmake --build build`
3. Execute `./build/bin/Debug/Tenacity.exe`
4. Observe DLL missing dialog for `vamp-hostsdk.dll`

### Expected behavior

Tenacity should start up without the DLL missing error when built with default options.

### OS

Windows 10 Education 21H1 (Build 19043.1165)

### Additional context

![image](https://user-images.githubusercontent.com/3370875/130332259-4a374067-c465-4436-823c-52c562c7ab82.png)

The missing release DLL is present within `vcpkg\packages\vamp-sdk_x64-windows`, but it is not being copied to the output folder on Debug builds. It actually seems that it should be relying on the debug version of the DLL anyways.

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by Be-ing** [comment]
Is this issue isolated only to this one DLL? Does it work when building with `-D VAMP=OFF`?

**Comment by Be-ing** [comment]
Does CMAKE_BUILD_TYPE=RelWithDebInfo work?

**Comment by emabrey** [comment]
It was because the way that the `cmake-modules/FindVampHostSDK.cmake` module was doing things was incorrect.

**Comment by hanskokx** [comment]
I am experiencing this issue as well. Just pulled the latest build.

![image](https://user-images.githubusercontent.com/1911919/132080136-57f3d51c-69ac-4724-9fc4-0c5f9c4fd04e.png)
![image](https://user-images.githubusercontent.com/1911919/132080142-ed82a211-c4e0-4405-aeda-53860d7d5903.png)

**Comment by Be-ing** [comment]
This issue is being worked on in #577.

**Comment by hanskokx** [comment]
Thanks!
