### ISSUE TITLE
Windows: References and links to Audacity in the Tenacity Windows installation EXE

### ISSUE THREAD

**Issue by petersampsonaudacity** [tenacityteam/tenacity-legacy#530]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

Tenacity_Windows_64bit_1154630604_ 

### Describe the bug.

1. launch the installation EXE for 64-bit Audacity on Windows
2. Examine the third installation dialog window
![image](https://user-images.githubusercontent.com/50205984/130351866-eb6f31f4-8694-4dce-8723-6fc62fd7da91.png)
3. Observe: references to Audacity and links to Audacity sites (Wiki, Forum and Website)

I tested with  @FugiMuffi 's build https://github.com/tenacityteam/tenacity/actions/runs/1154630604
as that has the fox for the Audacity logos used in the Tenacity installation EXE on Windows.
See Issue  Audacity logo used in Windows installation dialogs #502 

### Expected behavior

No references or links to Audacity.

### OS

Windows 10

### Additional context

Originally reported as part of:  Audacity logo used in Windows installation dialogs #502 

But now logged as this separate bug.

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by fugidev** [comment]
Thank you for moving this to a separate issue. Tenacity doesn't have a Wiki and/or Forum yet, so we can't just swap the name and URLs 1:1 - but I agree that this should be addressed asap, we can't release before that.

IMO it would be best to put Tenacity's website there for now, where users can find links to our repo, mailing list etc. Once we have set up a Wiki, that should be included as well.

**Comment by n0toose** [comment]
Relevant comment that should help us fix this: https://github.com/tenacityteam/tenacity/issues/123#issuecomment-903182370

**Comment by lmarz** [comment]
This issue has been resolved by d73e9eb1cdc5b936a4b1bec6b0c56785a75e02b9. There are no more references to Audacity in the Installer
