### ISSUE TITLE
MacOS builds consistently fail

### ISSUE THREAD

**Issue by caughtquick** [tenacityteam/tenacity-legacy#548]
### Guidelines

- [X] I have read the guidelines.

### Describe the bug.

1. Go to any recent PR
2. Click on the checks category 
3. See macOS build failing

### Expected behavior

None of the changes do anything that should cause the failing build however they do. It appears to be caused by a CPack error.

### OS

MacOS GitHub Actions

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by nbsp** [comment]
Possible duplicate of #542?

**Comment by caughtquick** [comment]
> Possible duplicate of #542?

Isn't that for local builds?

**Comment by Be-ing** [comment]
Fixed by https://github.com/tenacityteam/tenacity/pull/545/commits/7450432f9a480e01db79d8c9c904b165825a997c
