### ISSUE TITLE
Create a space for holding general discussions about the project other than GitHub Issues

### ISSUE THREAD

**Issue by thanhminhmr** [tenacityteam/tenacity-legacy#55]
As the title said, please enable the Discussion feature, it is more suitable for discussion.
This will enable people to ask questions without creating a new issue.

[Github offical link](https://docs.github.com/en/discussions)

**Comment by n0toose** [comment]
Yeah, you're right, this will be indeed very useful. I forwarded this to Cookie.

**Comment by nbsp** [comment]
Seems unnecessary to me: there are existing channels for more fluid discussion such as Matrix and IRC. Also, it would be best not to depend on GitHub (#51).

**Comment by n0toose** [comment]
> Seems unnecessary to me: there are existing channels for more fluid discussion such as Matrix and IRC. Also, it would be best not to depend on GitHub (#51).

Yeah, sorry, you're very much correct. Ideally, we would have a [Discourse](https://www.discourse.org/) instance running.

Dealing with GitHub issues for the moment as a temporary measure is better than making a more permanent measure. We have to wait until the name is chosen before we establish the official channels.

**Comment by nbsp** [comment]
> Ideally, we would have a [Discourse](https://www.discourse.org/) instance running.

Or, if we decide to use sourcehut, there could be a `<projectname>-discuss` mailing list, which is functionally identical to Discourse or Discussions, except without needing an account.

**Comment by n0toose** [comment]
Worth noting that over at [Haiku](https://haiku-os.org), which I also contribute to, we use [Freelists](https://freelists.org).

**Comment by Sciss** [comment]
I'm also older generation that used mailing lists - but I think many people are more comfortable with a web forum like Discourse. I think you can still set it up to receive mails like a mailing list - a big advantage is that it's easier to discover and navigate if you are not subscribed (sure, there is ML archives - but have you ever tried to quickly figure out what is going?). So while I personally like e-mail, I can see the advantages of using a web based forum.

**Comment by n0toose** [comment]
That's correct. (By the way, Haiku also has a [Discourse](https://discuss.haiku-os.org) forum. They're both good for different reasons.)

**Comment by nbsp** [comment]
I haven't used Discourse with email integration in the past, but if it supports all of the primary features through email, and does it in plain text, then it's fine by me. Email should be a first-class citizen.

**Comment by suetanvil** [comment]
I'd like to suggest enabling the Discussion feature right now as a stopgap, then looking into a more permanent solution later on.

FWIW, I'm concerned about proprietary and/or ephemeral services for this because they can disappear at the whim of their corporate owners.  A searchable public archive is **incredibly** valuable. I routinely find solutions to CMake problems in decade-old mailing list threads.

**Comment by nbsp** [comment]
I doubt there is a way to migrate the discussions outside of GitHub when we do ditch the feature, but yes, using that for a bit is better than getting the Issues tab spammed with irrelevant requests.

**Comment by mxmilkiib** [comment]
#audacity existed for years on freenode and transferred over to Libera.Chat, anyone is welcome to come /join, pretty much everyone there is pro fork afaiu, various folk and #lad devs/distro folk including @falktx hang there, though I understand this project will need it's own space eventually

**Comment by awslabspl** [comment]
> As the title said, please enable the Discussion feature, it is more suitable for discussion.
> This will enable people to ask questions without creating a new issue.
> 
> [Github offical link](https://docs.github.com/en/discussions)

Love the idea.

**Comment by caughtquick** [comment]
With the creation of #tenacity over on libera.chat and a mailing list on sourcehut I’m closing this issue.
