### ISSUE TITLE
tenacity: error while loading shared libraries: libwx_gtk3u_xrc-3.1.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yonderbread** [tenacityteam/tenacity-legacy#554]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

1b2c903

### Describe the bug.

1. Clone and compile wxwidgets branch, then install it.
2. Clone and compile tenacity.
3. Get error message when attempting to launch tenacity from the command line: 
```
tenacity: error while loading shared libraries: libwx_gtk3u_xrc-3.1.so.5: cannot open shared object file: No such file or directory
```
4. Try to install `wxgtk3` and other related wxwidgets libraries from AUR. Still get errors.

### Expected behavior

Libraries would be installed correctly and tenacity should find them.

### OS

Arch (running 5.13.12-xanmod1-1 kernel)

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by Be-ing** [comment]
> Clone and compile wxwidgets branch, then install it.

What wxWidgets branch? Are you using the wxgtk3-dev-light AUR package as [documented](https://github.com/tenacityteam/tenacity/blob/master/BUILDING.md#arch)?

**Comment by Be-ing** [comment]
Does it work if you run `tenacity` from the build directory without installing?

**Comment by yonderbread** [comment]
> > Clone and compile wxwidgets branch, then install it.
> 
> What wxWidgets branch? Are you using the wxgtk3-dev-light AUR package as [documented](https://github.com/tenacityteam/tenacity/blob/master/BUILDING.md#arch)?

Hi there, I tried that one as well.

**Comment by yonderbread** [comment]
> Does it work if you run `tenacity` from the build directory without installing?

Will give that a go

**Comment by n0toose** [comment]
Hi, just checking, did that work out well for you?

**Comment by juozaspo** [comment]
Did you install wxWidgets to default location (`/usr/local`)? Anyway if you have `ldconfig` program you should run it after installing the libraries to update `/etc/ld.so.cache` if tenacity wouldn't work with just with only installing them. If you use non-standard location add the directory to ldconfig settings file (`/etc/ld.so.conf`) before doing that. It might solve problems where library is present but the program still wouldn't find that.

**Comment by yonderbread** [comment]
It started working again but I have no idea why.

**Comment by Be-ing** [comment]
I suppose the AUR package got fixed?
