### ISSUE TITLE
Change CFBundleIdentifier to differentiate from upstream

### ISSUE THREAD

**Issue by core-code** [tenacityteam/tenacity-legacy#57]
the CFBundleIdentifier should be changed so that this fork can be distinguished from the 'original'

the current bundle-identifier `org.audacityteam.audacity` is used in these files

> cmake-proxies/cmake-modules 
> cmake-proxies/cmake-modules/MacOSXBundleInfo.plist.in 
> mac/scripts/build_dist.sh 
> mac/signing.txt 
> scripts/build/macOS/DMGSign.cmake 
> src/AudacityApp.cpp

**Comment by n0toose** [comment]
This will be taken care of after we decide on a name.
