### ISSUE TITLE
No localization when running tenacity from outside of it's executable dir located within it's build files

### ISSUE THREAD

**Issue by juozaspo** [tenacityteam/tenacity-legacy#587]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

b9ad2747fb9a23b91a4b6f7ff2d3b4f8a910d6c7

### Describe the bug.

When running tenacity from outside of it's executable directory that's located within it's build directory (e.g. running `<build_dir>/bin/Debug/tenacity`, or `build/bin/Debug/tenacity` as described in `BUILDING.md` file) it does not detect any locale files and nly english locale is shown in the settings dialog.

### Expected behavior

Locales being detected correctly when running from any location, not just from executable dir found within the build dir.

### OS

Ubuntu Linux 20.04 LTS

### Additional context

Locales are working correctly only when running from within executable dir (`build/bin/Debug`), as shown below:
```
$ cd build/bin/Debug
$ ./tenacity
```
Not working when running `build/bin/Debug/tenacity` and similar commands

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by emabrey** [comment]
I bet this is why we keep getting intermittent reports of locale loading issues.

**Comment by leio** [comment]
This is the same thing as https://github.com/tenacityteam/tenacity/issues/575 and fully expected to be like this in a gettext world. You are expected to install it and run it from there instead; most good IDEs take care of it for you like that. Any kind of "solutions" are likely to affect the installed version as well, which they shouldn't, but this can be discussed in the other ticket further if needed
