### ISSUE TITLE
macOS menu bar says "Audacity"

### ISSUE THREAD

**Issue by Be-ing** [tenacityteam/tenacity-legacy#618]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

master branch

### Describe the bug.

<img width="1232" alt="Screen Shot 2021-09-13 at 12 56 52 PM" src="https://user-images.githubusercontent.com/9455094/133133285-8a8c3e5f-1b14-4118-b0eb-0b9b8c6fcd8e.png">

### Expected behavior

Menu bar says "Tenacity"

### OS

macOS 11.5.2

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by Benitoite** [comment]
https://github.com/tenacityteam/tenacity/blob/01f22e8acb65b978181055cb6009093f5f6a3da4/cmake-proxies/cmake-modules/MacOSXBundleInfo.plist.in#L219
There are some keys in the Info.plist that need updating. That might break application access to previous bundle system containers, which to me is not a big deal, but others might loose their favorite prefs or something and have to dig them out manually if they are so inclined.

**Comment by n0toose** [comment]
Welp, nightly builds are nightly builds. Let's just warn people and it should be okay.

**Comment by n0toose** [comment]
We should replace other "Audacity" references in that file as well.
