### ISSUE TITLE
Linux CMake build fails with GIT_DESCRIBE list index: 1 out of range (-1, 0)

### ISSUE THREAD

**Issue by mmmaisel** [tenacityteam/tenacity-legacy#640]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

7230f6a39

### Describe the bug.

1. Checkout Tenacity on Linux machine
2. Create a build directory
3. Run `cmake ..` in the build directory
4. CMake fails. See Additional context for the log.

This also happens on the builds.sr.ht CI builds, e.g. on pull request #186.

### Expected behavior

The build works.

### OS

Arch Linux from 23.September 2021

### Additional context

```
$ cmake ..
CMake Error at CMakeLists.txt:89 (list):
  list index: 1 out of range (-1, 0)


CMake Error at CMakeLists.txt:90 (list):
  list index: 2 out of range (-1, 0)


-- Searching for dependencies from system, not using vcpkg.
-- Detected that we are using a single config generator without a build type defined...
-- To fix this we are using default value for CMAKE_BUILD_TYPE
-- The ASM_NASM compiler identification is unknown
-- Didn't find assembler
-- Inter-procedural optimization is supported
-- No compiler caching enabled. Install sccache or ccache to enable compiler caching.
-- Build automatically optimized to use processor count: 10
-- Build Info:
--      Host System Name: Linux
--      Host System Version: 5.14.6-arch1-1
--      Host System Processor: x86_64
--      Host System Arch: 64-bit
-- 
--      Target System Name: Linux
--      Target System Version: 5.14.6-arch1-1
--      Target System Processor: x86_64
--      Target System Arch: 64-bit
-- 
--      Compiler: /usr/bin/c++
--      Compiler Version: 11.1.0
--      Compiler Standard: 17
--      Compiler Standard Required: ON
--      Compiler Extensions: 
-- 
-- 
--      Current Commit: alpha-483-g7230f6a
-- 
-- MIDI support enabled.
-- ID3 tag support for MP3s enabled.
-- MP3 decoding support enabled.
-- MP2 encoding support enabled.
-- OGG container format support enabled.
-- Vorbis codec support enabled.
-- FLAC codec support enabled.
-- Could NOT find sbsms (missing: sbsms_LIBRARY sbsms_INCLUDE_DIR) 
-- SBSMS timestretching support disabled. Requires libsbsms.
-- SoundTouch timestretching support enabled.
-- Searching for FFMPEG components
-- /usr/lib/libavcodec.so
-- avcodec
--   - libavcodec 58.134.100 found.
-- /usr/lib/libavformat.so
-- avformat
--   - libavformat 58.76.100 found.
-- /usr/lib/libavdevice.so
-- avdevice
--   - libavdevice 58.13.100 found.
-- /usr/lib/libavutil.so
-- avutil
--   - libavutil 56.70.100 found.
-- /usr/lib/libavfilter.so
-- avfilter
--   - libavfilter 7.110.100 found.
-- /usr/lib/libswscale.so
-- swscale
--   - libswscale 5.9.100 found.
-- /usr/lib/libpostproc.so
-- postproc
--   - libpostproc 55.9.100 found.
-- /usr/lib/libswresample.so
-- swresample
--   - libswresample 3.9.100 found.
-- FFMPEG codecs support enabled.
-- VAMP plugin hosting enabled. Requires VAMP host SDK.
-- LV2 plugin hosting enabled.
-- Found wxWidgets: -pthread;;;-lwx_gtk3u_adv-3.0;-lwx_baseu-3.0;-lwx_gtk3u_core-3.0;-lwx_gtk3u_html-3.0;-lwx_gtk3u_qa-3.0;-lwx_baseu_xml-3.0;-lwx_baseu_net-3.0 (found suitable version "3.0.5", minimum required is "3.0") 
-- Found wxWidgets: -pthread;;;-lwx_gtk3u_xrc-3.0;-lwx_gtk3u_webview-3.0;-lwx_gtk3u_html-3.0;-lwx_gtk3u_qa-3.0;-lwx_gtk3u_adv-3.0;-lwx_gtk3u_core-3.0;-lwx_baseu_xml-3.0;-lwx_baseu_net-3.0;-lwx_baseu-3.0 (found version "3.0.5") 
-- ========== Configuring manual ==========
-- ========== Configuring images ==========
-- ========== Configuring lib-string-utils ==========
-- ========== Configuring lib-strings ==========
-- ========== Configuring lib-utility ==========
-- ========== Configuring locale ==========
-- ========== Configuring Tenacity ==========
-- Using precompiled headers
-- ========== Configuring mod-script-pipe ==========
-- ========== Configuring mod-null ==========
-- ========== Configuring mod-nyq-bench ==========
-- ========== Configuring nyquist ==========
-- ========== Configuring plug-ins ==========
-- ========== Configuring minsrc ==========
-- Configuring incomplete, errors occurred!
```

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by n0toose** [comment]
Your pull request looks very good, by the way, thank you for your efforts and for trusting us like that.

Paging @Be-ing, @emabrey and @solfisher for this.

**Comment by juozaspo** [comment]
I can't reproduce on my linux machine. What distribution are you running, what version?
From the log I don't see that git were detected, there should be a line similar to `-- Found Git: /path/to/git (found version "x.x.x")`. Relevant code:
https://github.com/tenacityteam/tenacity/blob/e776c2f7e41cad437edf6385fa42377fe4e21030/CMakeLists.txt#L49-L51
If you have git installed, what is the version? Does `git describe --tags --abbrev=7` return `Audacity-3.0.2-815-g7230f6a` (on latest master) or something else? Also what is the version of cmake? That might help too.
If git is not detected the GIT_DESCRIBE should be set to "unknown" as shown below.
https://github.com/tenacityteam/tenacity/blob/e776c2f7e41cad437edf6385fa42377fe4e21030/CMakeLists.txt#L68

**Comment by mmmaisel** [comment]
As mentioned in the bug report, I use an up-to-date Arch Linux. Since the bug also happens on the Arch Linux CI, I don't think it is a problem caused by my local setup.

Here is the output of the requested commands for further debugging:
```
$ git --version
git version 2.33.0

$ git describe --tags --abbrev=7
alpha-483-g7230f6a

$ cmake --version
cmake version 3.21.3
```

**Comment by AnotherFoxGuy** [comment]
The issue seems to be this tag: https://github.com/AnotherFoxGuy/tenacity/releases/tag/alpha

**Comment by juozaspo** [comment]
As your git describe command returns something it is probably not what the rules in `CMakeLists.txt` expect, so cmake fails because of that. The rules expect format like `x.y.z` in place of `alpha` and fails because what it sees is not what it expects. In correctly formatted version string dots should be replaced with semicolons and then parsed on subsequent code. There should be rules handling missing numeric version but I'm unable to find that and because of that cmake fails when working with in such cases.
You may also try `git describe --tags --abbrev=7 --debug` and `git tag --list` for any further debugging.

**Comment by mmmaisel** [comment]
I can confirm that this is caused by the "alpha" tag. If I delete it locally, the build works until the tag is added again by the next git pull.

When I append `--match "Audacity-*"` to the git describe command, tags that do not begin with "Audacity-" and thus can not be parsed by the CMake script are filtered out and it works when the "alpha" tag is present.

Is this a valid fix or would it cause more problems later?

**Comment by juozaspo** [comment]
I'm not sure about `--match` in command line, but it still might work, other developers might know better if it's a right solution or not. I myself don't see a problem.
