### ISSUE TITLE
Tenacity doesn't launch

### ISSUE THREAD

**Issue by Magolor44** [tenacityteam/tenacity-legacy#653]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

r13812-gdce03bae1-1

### Describe the bug.

Tried launching Tenacity through GUI and terminal on Arch LInux and got the following error message when trying to launch from terminal: tenacity: error while loading shared libraries: libwx_baseu-3.1.so.4: cannot open shared object file: No such file or directory

### Expected behavior

I expected to launch Tenacity

### OS

Arch Linux

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by Be-ing** [comment]
If you installed Tenacity from an unofficial package this is probably a bug in the package. If you built Tenacity from source yourself then please reopen this.

**Comment by Magolor44** [comment]
Ah sorry I was unaware that the version in the chaotic AUR was unofficial.

**Comment by n0toose** [comment]
We got in touch with the maintainers and it should work now, @Magolor44.

**Comment by Magolor44** [comment]
Thank you:)
