### ISSUE TITLE
Flatpak build failure

### ISSUE THREAD

**Issue by Semisol** [tenacityteam/tenacity-legacy#669]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

db3f6ae

### Describe the bug.

```
Fetching git repo c4dm/vamp-plugin-sdk.git, ref refs/tags/vamp-plugin-sdk-v2.10
fatal: could not read Username for 'gitlab.com': No such device or address
Failed to download sources: module soundtouch: Child process exited with code 128
Error: Build failed: Error: The process '/usr/bin/xvfb-run' failed with exit code 1
```
The flatpak build fails with the above error.

### Expected behavior

The build does not fail.

### Additional context

https://github.com/tenacityteam/tenacity/runs/3891150698

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by TheEvilSkeleton** [comment]
This was fixed by https://github.com/tenacityteam/tenacity/commit/697c0e764ccb19c1e2f3073ae08ecdac7aa710e4.
