### ISSUE TITLE
Allow for project donations

### ISSUE THREAD

**Issue by duncan-bayne** [tenacityteam/tenacity-legacy#67]
I've used Audacity for over a decade, and have recently started teaching my eldest child how to use it to record, edit, and mix music.  The recent hostile takeover of Audacity disgusts me, but I'm delighted to have discovered this fork :)

I'd love to financially support this fork with a donation, if there were a means to do so provided - perhaps [SubscribeStar](https://www.subscribestar.com/)?

**Comment by nbsp** [comment]
Perhaps a more FOSS project centered service would be more fitting, such as [Liberapay](https://liberapay.com) or a selfhosted solution like [fosspay](https://git.sr.ht/~sircmpwn/fosspay).

**Comment by panos** [comment]
I use LiberaPay for myself. Relevant to #28.

**Comment by cookiengineer** [comment]
I've seen some webrelated projects move over to Open Collective, and they seem to be quite transparent about fees and who (which contributor) received what about of money.

Example (webpack project): https://opencollective.com/webpack

Open Collective also has a non-profit organization that can pay you in the US, so taxes and everything are legit. In the EU, however, you still need to file taxes yourself from what I've heard (as self-employed).

**Comment by Sciss** [comment]
OpenCollective was also mentioned for SuperCollider, which is likewise looking for a potential dev funding model: https://scsynth.org/t/crowd-funding-supercollider-development/3860

**Comment by gitressa** [comment]
[Open Collective](https://opencollective.com/) looks great, see for example the [Vue.js](https://opencollective.com/vuejs) project, currently with 643 supporters.

Also, the maintainers could individually accept Bitcoin or Litecoin donations, by including a personal address in their profile.

**Comment by peepo5** [comment]
Host an XMR address and Librepay;
Monero provides a privacy-focused donation for a privacy-focused fork.

**Comment by cookiengineer** [comment]
@peepopoggers Doesn't help if we exchange one botnet for another one. I'm against Monero, especially if we care about reputation of the project.

**Comment by Semisol** [comment]
> @peepopoggers Doesn't help if we exchange one botnet for another one. I'm against Monero, especially if we care about reputation of the project.

Why specifically?

**Comment by bitdivine** [comment]
Me too.  I am equally happy contributing in cash or crypto.  I use audacity only very rarely, so I am not likely to be contributing much code, but it has been an awesome tool when I have used it.  It seems that the people supporting this may have to put up with some serious ill will (which makes me wonder why this software is sooo valuable to some groups, including criminals) so the least I can do is buy you a whisky when you need it.

My inbox gets swamped easily.  Apologies in advance if I don't see your post showing how to contribute.  I will try to check back here in a day or so.

**Comment by n0toose** [comment]
> Me too. I am equally happy contributing in cash or crypto. I use audacity only very rarely, so I am not likely to be contributing much code, but it has been an awesome tool when I have used it. It seems that the people supporting this may have to put up with some serious ill will (which makes me wonder why this software is sooo valuable to some groups) so the least I can do is buy you a whisky when you need it.

We appreciate your support a lot. I guess we could link our personal donation accounts (separate from Tenacity stuff) later on using a LiberaPay team, please allow me to coordinate this properly. We'll probably consider opening an account for Tenacity itself later down the line, as soon as we figure out who's going to manage funds and how.

**Comment by n0toose** [comment]
Whatever we do, please be fully aware that there is a considerable chance that the project may still not get off the ground.

I don't think this should be centered around us being paid, we would rather do something first.

**Comment by ghost** [comment]
Huh, I searched first and couldn't find it, hence #154. Weird. Thanks for pointing me to this issue!

**Comment by RoaddogLabs** [comment]
The FOSS donation sites are fine for those coming to the repo.  When you ship most of your users will not know of these options and are not likely to use them.  For the mainstream users it’s going to need be something like Zelle or Venmo or whatever other mainstream payment systems come online.

**Comment by emabrey** [comment]
I have setup an Open Source Collective based donation option. You can donate using the Github Sponsors feature and the money will be placed into the control of the Fiscal Host, which is the Open Source Collective. All expenditures will be public and require approval, that way donators know that their donations are being used appropriately.

The Open Source Collective for Tenacity is located [here](https://opencollective.com/tenacity).
Donations can be submitted there directly, or alternatively, you can [use the GitHub sponsors feature](https://github.com/sponsors/tenacityteam).

Some of our developers are also independently offering donation options that DO NOT go to the project, but rather directly to the individual, myself included. I want to clarify that if you donate via our individual profile pages ([mine](https://github.com/sponsors/emabrey), for example) that DOES NOT GO TO THE PROJECT. There is nothing untoward about offering individual donation options, of course, but I do not want there to be any confusion.
