### ISSUE TITLE
Discussion Panel

### ISSUE THREAD

**Issue by prysmanta** [tenacityteam/tenacity-legacy#68]
**Is your feature request related to a problem? Please describe.**
The issues tab is often plagued with topics like a new logo, or a new interface. It would be nice to have a dedicated discussion tab for topics like this.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/65317109/124587128-dc217c80-de89-11eb-9260-038a35a08a79.png)
Enable discussion tab in the repository settings tab.

**Comment by nbsp** [comment]
Duplicate of #55, feel free to close

**Comment by EricBright** [comment]
Closed as a duplicate of #55.
