### ISSUE TITLE
export surround wav 

### ISSUE THREAD

**Issue by tjingboem** [tenacityteam/tenacity-legacy#683]
### Guidelines

- [X] I have read the guidelines.

### Is your feature request related to a problem? Please describe.

good morning. I just switched from Audacity to Tenacity, and i like what i see. (Linux Mint)
As i am working with surround sound, i noticed that i am unable, when saving, to assign different tracks to different channels.
This was possible with Audacity and i do miss this feature.

### Describe the solution you'd like

copy and paste this from Audacity and make it optional in Preferences

### Describe alternatives you've considered

none

### Additional context

![Screenshot from 2021-12-19 13-37-08](https://user-images.githubusercontent.com/6670911/146678633-aa879683-691b-441d-9fe2-8c0f487e4c2d.png)
i can export as a mono or stereo file- no other options

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by fo1981** [comment]
I got this shit why y'all sitting around the holidays

**Comment by tjingboem** [comment]
thank you very much!

**Comment by n0toose** [comment]
> I got this shit why y'all sitting around the holidays

You're more than free to send a pull request to fix this and help around a little bit, we'll make sure it'll be properly reviewed as soon as possible.

**Comment by tjingboem** [comment]
This issue is solved, i made a mistake.

I was not aware of the option, in Preferences,  to choose between 'Mix down to Stereo and Mono' and 'Use Advanced Mixing options':
![Screenshot from 2021-12-28 12-31-19](https://user-images.githubusercontent.com/6670911/147562582-da47b63f-76f4-453d-ba21-054aa1073d3e.png)

The options:

![Screenshot from 2021-12-28 12-31-33](https://user-images.githubusercontent.com/6670911/147562591-62534d35-f356-4257-be10-88f78866f3be.png)

Once i choose the right option to export to surround WAV, all works (is tested) as it did with Audacity:
![Screenshot from 2021-12-28 12-34-04](https://user-images.githubusercontent.com/6670911/147562673-1dbe10f5-c27f-4331-b81c-6445cc00e58a.png)

I'll close the issue, thanks fo1981 for the offer to help!
