### ISSUE TITLE
PKGBUILD use pacman to install AUR dependency (wxgtk3-dev-light)

### ISSUE THREAD

**Issue by JasonJasu** [tenacityteam/tenacity-legacy#687]
### Guidelines

- [X] I have read the guidelines.

### Describe the bug.

So i tried installing tenacity from the AUR, when i tried **_makepkg -si_**, an error shows up. it says 

`pacman failed to install missing dependencies.` (image below)

and from what i suspect, the package tries to install _wxgtk3-dev-light_ (which is an aur package), through pacman.

a temporary solution would be **installing wxgtk3-dev-light manually** through the AUR.

### Expected behavior

It should've installed its dependencies automatically, but it doesn't.

### OS

Arch Linux

### Additional context

![image](https://user-images.githubusercontent.com/48150396/147413714-32b813ef-e964-4895-9529-b5665b75f40f.png)

![image](https://user-images.githubusercontent.com/48150396/147443680-61411382-c556-4961-82aa-80b6a8787bba.png)

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by n0toose** [comment]
Please reach out to the maintainers of the AUR package, as we don't officially maintain it or have the power to change things in it (apart from one contributor).

**Comment by fossdd** [comment]
This is a problem that also me as AUR package maintainer can't handle. `wxgtk3-dev-light` is only available on the AUR.

A workaround is: You could try AUR helpers, like `paru`. They detect them and build them too.

Pretty all AUR packages which depend on other AUR packages solve this like we do.

I hope I could help

**Comment by FabioLolix** [comment]
> 
> Expected behavior
> 
> It should've installed its dependencies automatically, but it doesn't.

pacman don't deal with AUR pkgbuilds and never will, this issue can closed as `can't fix`

https://wiki.archlinux.org/title/Arch_User_Repository
https://wiki.archlinux.org/title/Arch_User_Repository#Installing_and_upgrading_packages

**Comment by n0toose** [comment]
True.
