### ISSUE TITLE
Mirror conan packages

### ISSUE THREAD

**Issue by AnotherFoxGuy** [tenacityteam/tenacity-legacy#69]
This fork currently still uses the Conan packages hosted at https://artifactory.audacityteam.org
For independence, it would be better to mirror these packages to a separate host

These are the available hosting options for hosting Conan pakages:
- Free subscription of Artifactory (2GB Storage and 10GB Transfer/month)
- Cloudsmith with the OSS plan (50GB Storage and 200GB Transfer/month)
- Selfhosted JFrog Artifactory Community Edition (No real limit)

**Comment by AnotherFoxGuy** [comment]
This repo should also be forked I think: https://github.com/audacity/conan-recipes

**Comment by Be-ing** [comment]
Larger question: do we want to stick with Conan? AFAIK there is not a pressing reason to switch, but it's worth discussing I think.

**Comment by falkTX** [comment]
Since upstream is keeping it, yes?
It would mean builds more closely match upstrem, which helps in more wide testing.

**Comment by Be-ing** [comment]
Trying to debug issues with Conan in #176, I get the impression that Conan is really overcomplicated. Or at least, the way Audacity is using it is really overcomplicated. Maybe both are true. I am thinking it might be less work to switch to vcpkg than continue trying to get sccache working on Windows with Conan. vcpkg is really simple to use. It just requires passing one variable to CMake (`-DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake`) and using `find_package` in CMakeLists.txt as usual.

**Comment by Be-ing** [comment]
For hosting prebuilt dependencies, vcpkg is flexible. `vcpkg export` creates a ZIP archive that can be hosted on any server, no special server software is required.

**Comment by falkTX** [comment]
We will keep what upstream uses for the time being.

**Comment by AnotherFoxGuy** [comment]
I've created a discussion for the package manager: https://github.com/tenacityteam/tenacity/discussions/177

**Comment by emabrey** [comment]
I've cloned the conan-recipes repo: https://github.com/tenacityteam/conan-recipes/

**Comment by AnotherFoxGuy** [comment]
Should I create a Cloudsmith repo and upload our packages there? 
I already started packaging some packages from the cmake-proxies directory (see https://github.com/tenacityteam/conan-recipes/pull/1) and would like someplace to host them
