### ISSUE TITLE
DCO CI checks are broken

### ISSUE THREAD

**Issue by n0toose** [tenacityteam/tenacity-legacy#693]
DCO CI checks fail because the VPS the application was hosted on has been taken down.

**Comment by Semisol** [comment]
Yeah uh.. it's my fault
I don't think I can currently host it, sorry :|

**Comment by Be-ing** [comment]
So... should we turn off the check?

**Comment by Semisol** [comment]
It can be replaced with [this](https://github.com/apps/dco), but I'm currently burnt out so I want to stay away from the project currently. It won't check noreplies, which are problematic as they do not have emails redirected, so a manual check is required for those.

**Comment by n0toose** [comment]
Someone [fixed this](https://github.com/tenacityteam/tenacity/pull/694/checks?check_run_id=4954956676), closing issue.
