### ISSUE TITLE
Fork wxWidgets package

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [tenacityteam/tenacity-legacy#70]
The build at the moment still depends on this package and I think it should also be cloned into the current organization: https://github.com/audacity/wxWidgets

**Comment by BenBE** [comment]
As most of the custom patches in that repository have been upstreamed I'd suggest directly going to wxWidgets' upstream instead.

**Comment by Be-ing** [comment]
Related: https://github.com/audacity/audacity/pull/946

**Comment by emabrey** [comment]
I have forked the project into the tenacityteam org. https://github.com/tenacityteam/wxWidgets

**Comment by n0toose** [comment]
It may be a better idea to use the upstream version. See #95.

Closing this issue, because we do have a fork and the question is whether we should actually use it.
