### ISSUE TITLE
cmake/vcpkg: libwinpthread failed to downlaod

### ISSUE THREAD

**Issue by voltagex** [tenacityteam/tenacity-legacy#727]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

9b4b96d989615aeddaf141b93f82afb8c1eecf7b

### Describe the bug.

Attempt to load the project in VS2022. Initialisation fails.
[vcpkg-bootstrap.log](https://github.com/tenacityteam/tenacity/files/9010802/vcpkg-bootstrap.log)
[vcpkg-manifest-install.log](https://github.com/tenacityteam/tenacity/files/9010804/vcpkg-manifest-install.log)

```
https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404
```

The latest/only version of that in the msys2 repo is https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.6001.98dad1fe-3-any.pkg.tar.zst

### Expected behavior

Prerequisites download successfully, able to begin the build

### OS

Windows 10

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by voltagex** [comment]
Searching shows there's a hardcoded version in a couple of files for some reason:

```
vcpkg/scripts/cmake/vcpkg_acquire_msys.cmake
534:        URL "https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst"

vcpkg/scripts/cmake/vcpkg_find_fortran.cmake
54:                        "https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst"
92:                        "https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst"
```

**Comment by voltagex** [comment]
Ah, sorry - this probably should be opened on your fork of vcpkg, can this be moved easily?

**Comment by Be-ing** [comment]
I'll update the vcpkg submodule.

**Comment by Be-ing** [comment]
#728

**Comment by Be-ing** [comment]
Wtf GitHub, pressing `Tab` then `Enter` from a comment box should *not* close the issue. Why is this still a problem??

**Comment by Be-ing** [comment]
#728 has been merged. _Now_ this can be closed.
