### ISSUE TITLE
tenacityaudio.org/ download redirect to release page of github

### ISSUE THREAD

**Issue by softyoda** [tenacityteam/tenacity-legacy#735]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

idk

### Describe the bug.

When I click on download on the page https://tenacityaudio.org/ it redirect me to https://github.com/tenacityteam/tenacity/releases 

### Expected behavior

It should redirect me to https://nightly.link/tenacityteam/tenacity/workflows/cmake_build/master

### OS

Windows 10

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by softyoda** [comment]
Also, is there any download for windows 10 pro (I don't have windows server installed on any computer at home)

**Comment by fitojb** [comment]
This project has never officially released stable binaries, hence the lack of a download. Also, Windows Server and Windows Pro are just two different configurations of the same operating system. The link will work just fine in your system.
