### ISSUE TITLE
Make Conan optional

### ISSUE THREAD

**Issue by mmmaisel** [tenacityteam/tenacity-legacy#75]
**Describe the bug**
Conan is not available on most Linux distributions and is not really not necessary to build this since Linux has a working C library management system by itself.

**To Reproduce**
1. create a new empty build directory in the git checkout
2. run `cmake ..` in this directory
3. See error
```
CMake Error at cmake-proxies/cmake-modules/conan.cmake:795 (message):
  Conan executable not found! Please install conan.
Call Stack (most recent call first):
  cmake-proxies/cmake-modules/conan.cmake:841 (conan_check)
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:4 (conan_add_remote)
  CMakeLists.txt:154 (include)
```
**Expected behavior**
It build with the libraries provided by the system without Conan.

**Additional information (please complete the following information):**
 - OS: Arch Linux

**Comment by zeGolem** [comment]
It is a opt-out feature: From BUILDING.md:

> ### Building using system libraries
>
> On Linux it is possible to build Audacity using (almost) only the libraries provided by the package manager. Please, see the list of required libraries [here](linux/required_libraries.md).
>
> ```
> $ mkdir build && cd build
> $ cmake -G "Unix Makefiles" \
>         -Daudacity_use_ffmpeg=loaded \
>         -Daudacity_lib_preference=system \
>         -Daudacity_obey_system_dependencies=On \
>          ../audacity
> ```

**Comment by falkTX** [comment]
Shouldn't this be opt-in for Linux? It would make it easier to self-build.

**Comment by Be-ing** [comment]
I think Conan should be opt-in on all OSes.
