### ISSUE TITLE
[Request] Please read comment before removing thanks! App Name To Be CleanCity

### ISSUE THREAD

**Issue by JadenJSJ** [tenacityteam/tenacity-legacy#76]
**Is your feature request related to a problem?** No

**Describe the solution you'd like**
The app name should probably be **CleanCity**
I mean its clean from all the telemetry & spyware right?

Sorry the name vote post was locked and I really wanted this to be in there :/

**Comment by JPcode05** [comment]
@JadenJSJ CleanCity is not a good name for an audio editor. Sorry, but at least we read the comment.

P.S. Nice profile picture!

**Comment by EricBright** [comment]
Closed as duplicate of #33.
