### ISSUE TITLE
Name suggestion [Sheer]

### ISSUE THREAD

**Issue by Slavko-P** [tenacityteam/tenacity-legacy#77]
Sheer

As in "Oh the **Sheer** audacity!".

Sheer is defined as "easy to see through" ([Webster](https://www.merriam-webster.com/thesaurus/sheer))

I've already suggested this name, but I think that the reply got deleted due to the 4chan raid.

**Comment by anactualhuman** [comment]
oh the sneed audacity

**Comment by NormanOsborn** [comment]
Hi! I'll suggest the name "AudioChuck" again because apparently the person moderating yesterday thought it was a joke. It's in memory of my friend who used Audacity all the time, but he passed last year due to COVID. Using this name would be a great way to remember him!

**Comment by awslabspl** [comment]
> he passed last year due to COVID

Sorry to hear this.

**Comment by ghost** [comment]
I agree with AudioChuck as a name. Maybe with a woodchuck mascot with headphones or something. Seems cool.

Alternatively, FbehavioCity might be neat. It doesn't mean anything, I came up with it randomly, it just sounds cool. 🙂

**Comment by EricBright** [comment]
Closed as duplicate of #33.
