### ISSUE TITLE
Regarding the 4chan raids

### ISSUE THREAD

**Issue by ghost** [tenacityteam/tenacity-legacy#78]
There has been A lot of FUD and misinformation going around, and it's giving the folks who legitimately voted on sneedacity a bad reputation 

First off, my friend made the original thread and we discussed it. We had NO malicious intent regarding this "raid" or "trolling", we simply wanted to poke fun at a funny option. Everyone would've been fine, had the raid been known earlier and acknowledged, cookiengineer would've chosen the second best option and moved on. Instead, this entire situation turned into a flame war and is giving many a bad reputation. Now there is FUD spreading around too on hacknews and other sites. 

So People found it funny, and everyone voted as normal. No harm was intended. And **importantly, nobody was called or emailed in this situation**, especially since there is no proof whatsoever (and claims to back up this). To those that did derailed the original purpose of what my friend did, shame on you. Sneedacity WAS an option, does it even make sense? Why was it there to begin with? People chose it, but since the word "4chan" was involved and fox news gave many the controversial impression of the site, this turned into a bigger matter. 

The calls likely didn't happen nonetheless. A tweet was made that cookiengineer (I'll call them Cookie for now) received 600 calls or such and his family got contacted, yet there is no proof that any of this happened, and it sounds EXTREMELY illegitimate. First off, 600 calls is absolutely insane, there weren't doubtably that many people participated in the thread alone when the tweet was made. Nobody on /g/ ever mentioned phoning or any information regarding them. **UNTIL** there is proof disclaiming this debate for the now deleted tweet, I can't believe many people would act, since after lots of digging around, nobody could find his phone number. Yes, /g/ has annoying shitstains but that is due to the flame war nature of the event, this was never intended anyway. 

Then, people started claiming sneed meant "special needs", which is just absolutely delusional. Sneed was a simpsons joke, so if that's the case, feel free to cancel them. This assumption is from urban dictionary and it has more dislikes than likes, since it's wrong and never used. If this was the case, then I could say that "kids" means "kitten with aids." 

Less related, but someone assumed 4chan was involved in the KiwiFarms death of an snes dev. This is NOT true, and majority of the posts on the thread on /g/ (now archived, someone find a link) stated sentences like "Fuck KF" and similar. 4chan hates kiwifarms and wants nothing to do with it. Even 8chan(kun now) was fed up with the shit and is why kiwifarms was born. 

Finally, Cookie said he wanted to ban any trolls from contributing kind of "people with anime pics." yet sneedacity has contributed more actual code to the repository then this one from people with anime pfps. Doesn't this seem a bit wrong? 

Anyway, I'm feed up with this stuff. It was a small simple joke, and Cookie took it to an extreme and it went over his head. Now he's blaming mostly the wrong people, both GH, twitter, and 4chan is wrong. This is nonesense. Post send. Sneed I say no more.

**Comment by awslabspl** [comment]
So, to clarify ( correct me if Im mistaken: this was a joke, but people took it seriously. Correct?

**Comment by ghost** [comment]
> So, to clarify ( please correct me if Im mistaken ) : this was a joke, but people took it seriously. Correct?

Yep, this was taken too far. The thread wasn't made to cause harm. It was a very funny name and almost felt intentional.

**Comment by pyr-kaboosh** [comment]
![image](https://user-images.githubusercontent.com/80962489/124635031-4553c080-de87-11eb-80a4-fecf95e0c7cd.png)

This actual definition of Sneed^. 
It means nothing.

**Comment by zaafonin** [comment]
In my opinion, there was no need to remove the original poll, moderation would be enough. A week-long vote would be more than enough for genuine FOSS enthusiasts to vote (no matter their preferred name) and for obvious trolls to get bored.

But yes, it's a shame Sneedacity as a name is now kind of contaminated by harmful activity. It started as a lighthearted joke I personally had nothing against, and I wish it could stay so.

**Comment by EricBright** [comment]
Closed as duplicate of #48.

**Comment by ghost** [comment]
@EricBright That thread is locked and not the same as the other thread. I don't see why this asked for a lock, my goal was different from that one.

**Comment by mnn** [comment]
I don't know about what happened with the vote (and not really that much care, reading few comments about it and then seeing maintainers' position on censorship already put me off from trying this fork). I'll just say my two cents about

> Closed as duplicate of #48.

Why is this closed as a duplicated of a [non-existing issue](https://github.com/tenacityteam/tenacity/issues/48)? If a user/dev with the same problem wants to check, only to arrive at a closed issue pointing at non-existing issue, that won't give positive impression at all.

<img width="436" alt="2021-07-07_13-29" src="https://user-images.githubusercontent.com/1975567/124752119-bb0f6900-df27-11eb-87f3-5cee47758fb5.png">
