### ISSUE TITLE
Name Suggestions

### ISSUE THREAD

**Issue by peepo5** [tenacityteam/tenacity-legacy#79]
* Moredacity
* Ordacity
* Freedacity
* Undacity
* Forkacity (tongue twister)
* Earfork
* Audiofork
* Soundbranch
* Audiobranch
* Libredacity
* Opendacity
* Reglify
* Forkdacity
* Monstrosity
* Monstrasity

Comment's Ideas:

* Redacity
* LINA - Lina is not Audacity
* Sequacity

BTW (I opened a new issue just because I had a million ideas for names so moderators look through the comments for suggestion ideas and main thread was locked)

**Comment by alexhollinghead** [comment]
Someone suggested Audacy previously, which I really liked

**Comment by awslabspl** [comment]
Im AGAINST first and second one.........

The reason being translation; Im from Poland and both can be spoken as `Morda` which can be translated as `ugly face`

**Comment by rbeer** [comment]
This ~is~ could be a very similar case to what https://vscodium.com/ is doing. They choose a name close to the original VSCode. That makes sense, since VSCodium is essentially the same as VSCode, just without the Telemetry bits.

Diverging only little from the original name communicates that fact of having only diverged little from the original codebase.

**Comment by caughtquick** [comment]
> This is a very similar case to what https://vscodium.com/ is doing. They choose a name close to the original VSCode. That makes sense, since VSCodium is essentially the same as VSCode, just without the Telemetry bits.
> 
> 
> 
> Diverging only little from the original name communicates that fact of having only diverged from the original codebase.

I don't think the point of this fork is just for telemetry removal but also modernizing the ui etc

**Comment by sowa705** [comment]
> I don't think the point of this fork is just for telemetry removal but also modernizing the ui etc

Im not sure if its possible considering muse couldn't do it with proper dev team, its years of effort that people might not want to do for a project associated with 4chan trolls

**Comment by rbeer** [comment]
> > This is a very similar case to what https://vscodium.com/ is doing. They choose a name close to the original VSCode. That makes sense, since VSCodium is essentially the same as VSCode, just without the Telemetry bits.
> > Diverging only little from the original name communicates that fact of having only diverged from the original codebase.
> 
> I don't think the point of this fork is just for telemetry removal but also modernizing the ui etc

In any case, that's nothing for me to decide. Just pointing out that if the maintainers decided to take the VSCodium approach, anything with e.g. `.*d?acity` would be objectively better suited than let's say SoundMonkey.

**Comment by TheCreeper** [comment]
Perhaps Redacity? As in a remix or derivative work of Audacity or Audacity reborn.

**Comment by TheCreeper** [comment]
Perhaps Redacity? As in a remix or derivative work of Audacity or Audacity reborn.

**Comment by coderjones** [comment]
LINA - LINA Is Not Audacity

**Comment by peepo5** [comment]
> > This is a very similar case to what https://vscodium.com/ is doing. They choose a name close to the original VSCode. That makes sense, since VSCodium is essentially the same as VSCode, just without the Telemetry bits.
> > Diverging only little from the original name communicates that fact of having only diverged from the original codebase.
> 
> I don't think the point of this fork is just for telemetry removal but also modernizing the ui etc

maybe, we have to see the plans of the governers. I still think it would be smart to name something related to audacity as openoffice->libreoffice did. It will attract audacity users but over time will become its own niche.

**Comment by peepo5** [comment]
> LINA - LINA Is Not Audacity

I really like this one :+1:, but I wonder if LINA conveys it is audacity enough. I would only recommend a name like this if the authors want to make alot of bigger changes, and not just privacy ones.

**Comment by meldra** [comment]
Sequacity - means "Flowing smoothly from one part to the next" but also sounds like a blend of 'sequel' and 'audacity'

**Comment by EricBright** [comment]
Closed as duplicate of #33.

**Comment by peepo5** [comment]
@EricBright Can you open the thread again? Also can you please reference this thread in that one.

**Comment by Sciss** [comment]
@peepopoggers simply add your suggestion to the original issue. It doesn't help to open new issues for new name ideas.
