### ISSUE TITLE
Logo Idea (Temporary)

### ISSUE THREAD

**Issue by peepo5** [tenacityteam/tenacity-legacy#82]
![image](https://user-images.githubusercontent.com/72892531/124641990-33721d80-de87-11eb-84c3-c993699aad1c.png)
![image](https://user-images.githubusercontent.com/72892531/124642026-3f5ddf80-de87-11eb-9c25-e6f0a1376e25.png)

I need some opinions, does this look :hankey: or alright for now?
I will attach files if it is usable.

**Comment by EricBright** [comment]
Closed as duplicate of #12.

**Comment by peepo5** [comment]
sryyy
