### ISSUE TITLE
Request and offers for hosting a project site

### ISSUE THREAD

**Issue by User-green** [tenacityteam/tenacity-legacy#84]
I think, if this project whant to be 100% independent, we need our own site.

For now I can provide temporar (year or so) hosting on `*.tslp.tk` domain, but I will need serious help to set it up.

In far perspective, I think, site should be hosted on VPS of some kind to witch only maintainers will have acsess to.

**Comment by peepo5** [comment]
ewww no that domain is trash.

I would go with a .org or .dev domain, and I don't think the developers are that broke lmao.

**Comment by peepo5** [comment]
or a new one: .audio domain!

**Comment by User-green** [comment]
> ewww no that domain is trash.

Yep, it is. However, we dont need better while we have no project name. IMO.

> I would go with a .org or .dev domain, and I don't think the developers are that broke lmao.

Yep. However, this will be good testground for now.

**Comment by Semisol** [comment]
They can get it sorted out. I don't think they need a domain.

**Comment by digitalrhizome** [comment]
I already forked this to our GitLab, and at least i will maintain a GitLab page and happily donate my company's resorces to hosting whatever space is required to get up and running and free of odious Muse b.s

**Comment by User-green** [comment]
> They can get it sorted out. I don't think they need a domain.

I am not about domain, but about host. I have running 24/7 server, bound to this domain. 
It isnt too powerfull, but not too weak.

**Comment by peepo5** [comment]
I don't think they want your hosting or domain.

**Comment by peepo5** [comment]
If you want to support the developers, donate when they open a method of payment.

**Comment by anactualhuman** [comment]
> If you want to support the developers, donate when they open a method of payment.

yes everybody, lets go get cookiengineer his month's rent for the zero work that he's put into this project
![glowsobright](https://user-images.githubusercontent.com/64220507/124649991-1b070080-de91-11eb-912a-8cf098cec45c.jpg)

**Comment by User-green** [comment]
> If you want to support the developers, donate when they open a method of payment.

I have no money. And will not in two or so years.

**Comment by peepo5** [comment]
then support by reporting issues and spreading awareness :) and giving ideas, but they wont use third party domains or hosting unless they say otherwise

**Comment by User-green** [comment]
> then support by reporting issues and spreading awareness :) and giving ideas, but they wont use third party domains or hosting unless they say otherwise

Well. Thats why I open this. Lets CE decide.

**Comment by l0go** [comment]
Cookie does web development, he can probably work on that.

**Comment by Be-ing** [comment]
I suggest a simple static website and a Discourse forum. Discourse provides free hosting for community projects, or it could be self-hosted if that's preferred.

**Comment by fossdd** [comment]
> I suggest a simple static website and a Discourse forum. Discourse provides free hosting for community projects, or it could be self-hosted if that's preferred.

Discourse is a extra forum. I wouldn't create a new space where users can interact and which has to be moderated. We already have GitHub Issues, Pull Requests, Discussions and the IRC. A additional one is imo too much.

If you see the project's about: https://github.com/tenacityteam/tenacity. You already see a domain `tenacityaudio.org`.

Currently there is just an placeholder but maybe can that forward developed.

EDIT: They added a basic information to the page.

**Comment by unbeatable-101** [comment]
[IPFS](https://ipfs.io) would be one option for distributing the source code/binaries

**Comment by User-green** [comment]
Thios seem to be done without my help.
