### ISSUE TITLE
64-bit Audacity Fork

### ISSUE THREAD

**Issue by Bamajon1974** [tenacityteam/tenacity-legacy#86]
Are there plans on releasing 64-bit binaries for this Audacity fork?

**Comment by adrianheine** [comment]
At least debian has 64bit builds of audacity, so I don't think there's any issue?

**Comment by peepo5** [comment]
Be patient :flushed:

**Comment by davidak** [comment]
Here is an Audacity fork that adds support for building 64-bit Windows binaries.

They summarised what is needed to achive it here: https://github.com/henricj/audacity/issues/5

**Comment by gregsskyles** [comment]
Audacity builds fine now (after the Cmake port) in 64-bit mode; the 
issue is more around testing and making sure there isn't some major new 
bug lurking out there.

**Comment by henricj** [comment]
The main difference between a Linux and Windows build is that on Windows x64, "long" is only 32-bits.  Even pre-CMake, it was pretty easy to just add an x64 build through Visual Studio (albeit with a barrage of new compiler warnings).  A long time ago, I went through and fixed many of those compiler warning regarding integer truncation and the like.  Some of those changes fixed real problems; many were harmless (apart from their impact on the ghastly compiler warning signal-to-noise problem).  The main codebase is (was?) in good shape with regard to Windows x64.  See the log messages containing "Resolve Windows" on the default [x64 branch](https://github.com/henricj/audacity/commits/x64).  The obvious problem being that imported library issues should be resolved upstream.

Come to think of it, unless the main Audacity port has done something about HighDPI on Windows in the last year, there are also some DPI handling changes in my fork that might be of interest.  At least, it makes it usable above the 125% setting (even at 250%).

**Comment by Bamajon1974** [comment]
henricj I found that you have an Audacity 64 bit port. Have you updated to the latest version yet? The last version on your site was 2.4.2 I believe. 
Seems like now is a good time to port software to 64-bit since MS isn't releasing a 32-bit Win 11 OS (just supporting 32-bit programs it seems like).

**Comment by falkTX** [comment]
Windows arm64 builds are going to become important quite soon too.

**Comment by ajayyy** [comment]
The GitHub action already seems to build Windows x64 binaries, I'll close this for now. For ARM builds, there is a PR open in upstream that we can wait for.
