### ISSUE TITLE
Request to update LICENSE.txt and add GPL acknowledgement

### ISSUE THREAD

**Issue by GriffintheFolf** [tenacityteam/tenacity-legacy#91]
Specifically, the name Audacity should be replaced with Tenacity, i.e.
`Note: Audacity is distributed under the terms of the GNU GPL Version 2.`

In addition, to ensure full compliance of the GPL, I think an acknowledgement of the original Audacity sources is in order, e.x.
`Tenacity is based upon Audacity, Copyright (c) 1999-2021 The Audacity Team`

_Disclaimer: I'm not a lawyer_

**Comment by cshaa** [comment]
_[Also not a lawyer]_

Editing the LICENSE file usually is a touchy bussiness, however the note in the beginning does not seem to be either a copyright notice, nor a part of the license iteslf. The copyright notice comes on [line 18](https://github.com/tenacityteam/tenacity/blob/master/LICENSE.txt#L18) and it says:
```
Copyright (C) 1989, 1991 Free Software Foundation, Inc.
```
Furthermore, [unlike MIT](https://opensource.stackexchange.com/a/4440/8884), the GPL license doesn't explicitly require that you include the author's copyright notice **verbatim**.  It states:
```
  1. You may copy and distribute verbatim copies of the Program's
source code as you receive it, in any medium, provided that you
conspicuously and appropriately publish on each copy an appropriate
copyright notice and disclaimer of warranty; keep intact all the
notices that refer to this License and to the absence of any warranty;
and give any other recipients of the Program a copy of this License
along with the Program.
```
I would think that the line you proposed does indeed look like _“an appropriate copyright notice”_.

A small detail I noticed: on [their webpage](https://www.audacityteam.org/), the team has the following copyright notice:
```
Copyright © 2021 by Audacity - All rights reserved
```
They list themselves as _“Audacity”_, not _“Audacity Team”_. I think it would be nice to respect that. So, I propose this as the new beginning of LICENSE:
```
Tenacity is based upon Audacity, Copyright (c) 1999-2021 by Audacity

Note: Tenacity is distributed under the terms of the GNU GPL Version 2.
This includes everything in the source code distribution
except code in the lib-src directory.  Code in the lib-src
...
(the rest of the file unchanged)
```

However, it would be best to get an actual lawyer before doing this :)
