### ISSUE TITLE
Just a quick question about censorship and freedom

### ISSUE THREAD

**Issue by purplesyringa** [tenacityteam/tenacity-legacy#93]
Hey, first, it'd be cool if you enabled discussions on this project. Second, I want to find out whether you care about software freedom and freedom or speech or not. Someone has deleted my issue here (tenacity#89) without comments. The issue was at something like +8/-7 which means it is controversial and reaching a common ground is required to avoid a major break or a fork between those supporting and opposing my request.

Please kindly:

- State the reason for removal of the issue.
- Answer, true or false, are you going to let the community decide the fate of the project in contradictory cases?
- Answer, true or false, will Tenacity remain free software not only de jure but also in faith?
- Answer, true or false, whether developers criticizing the decisions made by Tenacity Team will be banned and their question removed.

The situation as it is now reminds me of what happened with rms-open-letter, when people who questioned the behavior of the maintainers were banned and all issues were deleted. I want to know whether we're now opposing sides or friends.

I will consider the removal of this issue as 'false' answer to the last three questions.

If those who read this issue do not support baseless censorship, you may be interested in another fork: https://github.com/SartoxOnlyGNU/audacium. If you or the maintainers of this project have anything to tell me without getting censored before anyone can read you, you can [comment here](https://github.com/imachug/talk/issues/3) or send me a mail to imachug [at] gmail [dot] com. Thanks for reading.

**Comment by rubyFeedback** [comment]
Did you link in from audacity? But this here is tenacity right? Did you perhaps mix up the repositories?

Admittedly I am also beginning to be confused - too many forks. I'm waiting until the dust settles to see which fork will be active.

**Comment by purplesyringa** [comment]
> Did you link in from audacity? But this here is tenacity right? Did you perhaps mix up the repositories?

No, that is just stupid github. When I type `#89`, it thinks I'm referring to `audacity#89` not `tenacity#89` because the latter does not exist (because it was deleted). I was censored on this repository.

**Comment by falkTX** [comment]
Moderation is not censorship. This is not a government.

**Comment by purplesyringa** [comment]
Not every censorship is done by a government. Baseless removal of a polite request without a comment *is* called censorship.

**Comment by adrianheine** [comment]
This is the workplace of the people working on tenacity, as invited by @cookiengineer. Those people can limit access to and clean up their workplace as they fit. You may feel about that whichever way you want and voice your opinion about it somewhere. That doesn't give you any right over their workplace, and it doesn't make anything they do censorship.

**Comment by emabrey** [comment]
I would be happy to answer why it was removed, but as I did not remove it, I can't. The contributor whom deleted it will have to respond.

**Comment by purplesyringa** [comment]
> This is the workplace of the people working on tenacity, as invited by @cookiengineer. Those people can limit access to and clean up their workplace as they fit. You may feel about that whichever way you want and voice your opinion about it somewhere. That doesn't give you any right over their workplace, and it doesn't make anything they do censorship.

The problem with GitHub is that the issue tracker used to be where people voiced their concerns. These days there are discussions (which are quite badly organized tbh) which are still disabled on this repo, so there's literally no way for me to raise a question where people would notice me.

> I would be happy to answer why it was removed, but as I did not remove it, I can't. The contributor whom deleted it will have to respond.

Thank you. Unfortunately GitHub did not tell me who removed it, so I think I will have to wait, hopefully without getting censored this time.

**Comment by alicemargatroid** [comment]
> Moderation is not censorship. This is not a government.

First amendment applies to a government.
Censorship, in general, applies to any suppression or prohibition of any parts of books, films, news, etc. that are considered obscene, politically unacceptable, or a threat to security.

**Comment by alicemargatroid** [comment]
> This is the workplace of the people working on tenacity, as invited by @cookiengineer. Those people can limit access to and clean up their workplace as they fit. You may feel about that whichever way you want and voice your opinion about it somewhere. That doesn't give you any right over their workplace, and it doesn't make anything they do censorship.

Untrue. They are able to do so because they have power here.
That doesn't mean it isn't censorship, which is the suppression or prohibition of any parts of books, films, news, etc. that are considered obscene, politically unacceptable, or a threat to security.

**Comment by Emobe** [comment]
> This is the workplace of the people working on tenacity, as invited by @cookiengineer. Those people can limit access to and clean up their workplace as they fit. You may feel about that whichever way you want and voice your opinion about it somewhere. That doesn't give you any right over their workplace, and it doesn't make anything they do censorship.

that doesn't mean that there can't be an explanation as to why they deleted it. It's not a "workplace". Private things such as a workplace don't belong in public places if you wish to have "limits".

**Comment by emabrey** [comment]
I have enabled discussions.

**Comment by dontfwiththestream** [comment]
there are other audacity forks that don't have the censorship and drama of this team, and some of those forks have more activity than this one. Ego and drama has made this fork a non starter

**Comment by Sciss** [comment]
> there are other audacity forks that don't have the censorship and drama of this team

Then why are you still here? This is the question most team members will be asking themselves at this point. Why don't you enjoy that you have a fork that better suits your worldview elsewhere? It's the beauty of open source. You can have your own fork!

**Comment by dontfwiththestream** [comment]
Because the community at large needs to be aware that there are forks that have made more progress already with less drama. That way they don't waste time developing on a fork that is dead in the water due to egotistical developers. There are forks where opinions of others are welcome, and not met with censorship as the tenacity team is known for.

**Comment by falkTX** [comment]
You are the one creating the drama though

**Comment by dontfwiththestream** [comment]
I made the tenacity team censor like crazy? i opened this issue?

**Comment by port19x** [comment]
The questions asked are very important and should be answered.
Just look at vim vs neovim. Both are healthy and good software projects, but neovim is much more community driven while vim is basically the sole work of its lead maintainer.
On the note of the github repo being a workplace you can clean at will: Sure, you can do many things, but most people use issues to voice their concerns.
Also, telling people to just F off if they don't like sth is dismissive and rude. 
You have to articulate your values, which this Issue gives you the opportunity to

**Comment by ghost** [comment]
> I would be happy to answer why it was removed, but as I did not remove it, I can't. The contributor whom deleted it will have to respond.

improper use of whom, should be who, proper usage is as follows:

The contributor who deleted it...

The contributor whom the issue was deleted by...

**Comment by RoaddogLabs** [comment]
> Because the community at large needs to be aware that there are forks that have made more progress already with less drama. That way they don't waste time developing on a fork that is dead in the water due to egotistical developers. There are forks where opinions of others are welcome, and not met with censorship as the tenacity team is known for.

Contribute or not.  Your choice.  One good thing about FLOSS is one can pick and choose where to participate.  No one repo or dist owner owes you _anything_.  It’s pretty obvious many of the contrarian posters haven’t contributed to serious projects. This behavior wouldn’t be tolerated.  Try this on any large scale project and you’d be bounced PDQ.   If you don’t like how the maintainers run the project don’t contribute.  It’s that easy.

**Comment by Kill-Animals** [comment]
@falkTX 
@cookiengineer needlessly poked a wasp nest, and was completely inept on how to handle online communities, and has no sense for optics. Calling yourself a dictator of an open source project, while having absolutely no technical expertise, and spending his time weirdly lying about receiving harassing phone calls... He obviously is the reason why there is drama here. He is a meglomaniac incapable of receiving any sort of criticism or negative feedback.

**Comment by emabrey** [comment]
> 
> 
> > I would be happy to answer why it was removed, but as I did not remove it, I can't. The contributor whom deleted it will have to respond.
> 
> improper use of whom, should be who, proper usage is as follows:
> 
> The contributor who deleted it...
> 
> The contributor whom the issue was deleted by...

Yes. I understand when and where to use "whom". It has to with whether you are referring to a direct or indirect object. I used "whom" because it sounded better to me. This isn't a dissertation or a peer-review process for my issue comments. You have been disruptive several times now, so I apologize if this comes across as shockingly forthright.

**Comment by purplesyringa** [comment]
@caughtquick You're closing this without a comment again? What's wrong with you guys, you have quite a few maintainers and less than 150 issues, is it that difficult to answer a question? Hey everyone, Tenacity Team doesn't care about freedom, go somewhere else.

**Comment by caughtquick** [comment]
> @caughtquick You're closing this without a comment again? What's wrong with you guys, you have quite a few maintainers and less than 150 issues, is it that difficult to answer a question? Hey everyone, Tenacity Team doesn't care about freedom, go somewhere else.

First of all the original maintainer who deleted your comment has left the project. Second of all what other "censorship" have we partakes in? Discussions are open and free for everyone to participate (they were previously closed for being consistently off topic). Please actually state what the problem is and what changes do you recommend rather than screaming censorship.

**Comment by purplesyringa** [comment]
> Please actually state what the problem is and what changes do you recommend rather than screaming censorship.

It is stated in this issue. As the maintainers are constantly leaving and coming back, I can no longer figure out which maintainers are pro- or anti-GPL, etc.

- Will Tenacity be licensed under GPL? (GPLv2, GPLv3, GPLv3-or-later, either of those)
- Will Tenacity have a CLA or a DCO or something?
- Will Tenacity have a CoC?
- Are you going to let the community decide the fate of the project in contradictory cases?
- Will Tenacity remain free software not only de jure but also in faith?
- Will developers criticizing the decisions made by Tenacity Team be banned and their questions removed?

**Comment by Semisol** [comment]
1. I do not know the reason of removal as I wasn't who removed it, and don't know what it is related to.
2. Yes, we will whenever possible, but in the name situation you can read #121 and the responses there about the name selection.
3. Yes.
4. I don't exactly understand what you mean, but I won't block people/delete questions unless there was a strictly required reason to do so.

And, the actions of past maintainers do not represent the Tenacity team.
Also know that I do not represent all maintainers.

**Comment by Semisol** [comment]
And for your new questions
1. We will keep the GPL license, at least for now.
2. I think the community is anti-CLA so probably not that.
3. Not sure.

Please know that I am only giving my thoughts and the current team is not stable/subject to change.

**Comment by purplesyringa** [comment]
That is reassuring, thanks.

> We will keep the GPL license, at least for now.

The 'at least for now' part is asking for trouble, so I hope you won't do that, but I appreciate your honesty.

> Also know that I do not represent all maintainers. Please know that I am only giving my thoughts and the current team is not stable/subject to change.

That is not quite reassuring, but I hope the answers will remain approximately the same when the team is more or less stabilized. I would prefer to keep this issue open or on the backlog until that happens, but you may close it if keeping the issue tracker clean is more convenient for you.

**Comment by Semisol** [comment]
> That is reassuring, thanks.
> 
> > We will keep the GPL license, at least for now.
> 
> The 'at least for now' part is asking for trouble, so I hope you won't do that, but I appreciate your honesty.
> 
> > Also know that I do not represent all maintainers. Please know that I am only giving my thoughts and the current team is not stable/subject to change.
> 
> That is not quite reassuring, but I hope the answers will remain approximately the same when the team is more or less stabilized. I would prefer to keep this issue open or on the backlog until that happens, but you may close it if keeping the issue tracker clean is more convenient for you.

At least for now means if another team takes over. But I won't change it and switching to non-GPL probably will require a CLA which I answered above.
I am trying to keep the team the same as possible (except adding others), so if it happens you will get an announcement.

**Comment by Semisol** [comment]
Anyways hope I was able to help you out, I'll probably keep this here until most changes are here.

**Comment by caughtquick** [comment]
> > Please actually state what the problem is and what changes do you recommend rather than screaming censorship.
> 
> 
> 
> It is stated in this issue. As the maintainers are constantly leaving and coming back, I can no longer figure out which maintainers are pro- or anti-GPL, etc.
> 
> 
> 
> - Will Tenacity be licensed under GPL? (GPLv2, GPLv3, GPLv3-or-later, either of those)
> 
> - Will Tenacity have a CLA or a DCO or something?
> 
> - Will Tenacity have a CoC?
> 
> - Are you going to let the community decide the fate of the project in contradictory cases?
> 
> - Will Tenacity remain free software not only de jure but also in faith?
> 
> - Will developers criticizing the decisions made by Tenacity Team be banned and their questions removed?

1. Tenacity will stay on the license that is used by audacity. If they switch to GPLv3 we will rebase onto it too. 

2. There are no plans of a CLA whatsoever. 

3. Yes, we plan to keep a Code of Conduct in place.

4. This is an extremely loaded question. We personally will make a decision when the time comes. 

5. Yes, we have no plans to take an audacity like route to the project, we want this project to remain open to everyone and freely accessible.

6. Another loaded question. We will not shut down **constructive** criticism and welcome it. However we will not allow spam and **unconstructive** criticism. We will also avoid deleting and instead locking and archiving.

**Comment by Sciss** [comment]
Regarding the license. I think part of the reason for Tenacity is the unclear direction that Audacity is heading now with respect to keeping it fully open source. I don't think it is feasible nor desirable to repeat their move to try to obtain CLA like statements from all original authors, in order to move to a non-GPL compatible license and/or dual license in the future. So I would say, everyone can rest assured that the codebase will have to remain at least GPL v2, although I would not exclude the possibility that the team arrives in the future at a conclusion to move to GPL v3 or AGPL.

**Comment by caughtquick** [comment]
> Regarding the license. I think part of the reason for Tenacity is the unclear direction that Audacity is heading now with respect to keeping it fully open source. I don't think it is feasible nor desirable to repeat their move to try to obtain CLA like statements from all original authors, in order to move to a non-GPL compatible license and/or dual license in the future. So I would say, everyone can rest assured that the codebase will  have to remain at least GPL v2, although I would not exclude the possibility that the team arrives in the future at a conclusion to move to GPL v3 or AGPL.

Should Audacity move towards another **open source** license like GPLv3, AGPL, or LGPL we will adopt that. However should Audacity go closed source we will continue supporting the project in its current state. @imachug I hope this answers all your questions.

**Comment by purplesyringa** [comment]
> Should Audacity move towards another **open source** license like GPLv3, AGPL, or LGPL we will adopt that.

It's a pity. You understood nothing. Open source != free software, which the concern was about.

**Comment by caughtquick** [comment]
> > Should Audacity move towards another **open source** license like GPLv3, AGPL, or LGPL we will adopt that.
> 
> 
> 
> It's a pity. You understood nothing. Open source != free software, which the concern was about.

How so?

**Comment by Sciss** [comment]
Let's please not discuss the terminology of open source vs free software. What I was saying; since there is _no_ CLA in place now and unlikely in the future, the project effectively will (can) not move to a more permissive license.

**Comment by purplesyringa** [comment]
*Sorry for offtopic but does anyone have any idea why I can add reactions to most comments except Sciss's?*

**Comment by Semisol** [comment]
> _Sorry for offtopic but does anyone have any idea why I can add reactions to most comments except Sciss's?_

weird, will mark this and your comment as offtopic, contact me on libera.chat (Semisol on IRC) if you want

**Comment by caughtquick** [comment]
> *Sorry for offtopic but does anyone have any idea why I can add reactions to most comments except Sciss's?*

Nothing done from the organization members so it's something to do with GitHub.

**Comment by Songtech-0912** [comment]
I believe this issue has gotton off-topic, let's discuss this in Github discussions or via a private chat location instead. Let me do a TL;DR for everyone:

* Licensing is a heated topic, but it's pretty clear license changes will NOT happen.
* There is also no form of censorship going on because Tenacity is explicitly a **fork* of audacity made to **remove "censorship"**, which *does* have "censorship" issues in the forms of its CTA and new ownership.

With that in mind, can we close this issue?

**Comment by Semisol** [comment]
yes please

**Comment by ghost** [comment]
The irony is that @imachug censoring the zeronet repository on github, and he was actively called zeronet's license to be licensed under a restrictive license.

**Comment by purplesyringa** [comment]
Lmao you've been stalking me for about two years already, don't you think it's time to stop? Back then I wasn't even completely aware of free software, I'm a completely different person freedom wise now. (but that 'more restrictive license' was GPL IIRC so that's still not a valid argument, and no I censored no one because a) I didn't even have write access to that repo, b) I haven't asked the maintainer to delete anything except your spam and nonsense). To Tenacity maintainers: please remove this offtopic or something, to you: I can answer whatever problems you have via email or https://github.com/imachug/talk/issues/new)

**Comment by ghost** [comment]
Oh, remove this offtopic when someone comes and demonstrates that @imachug is the one who censors and bullies people? Than remove it fast? When your comments get removed you immediately cry censorship, **hypocrite**.

**Comment by Semisol** [comment]
@p2p-publisher @imachug please move your discussion somewhere else if possible, but i am keeping the comments
