### ISSUE TITLE
Will there be an official statement about the chosen name?

### ISSUE THREAD

**Issue by cshaa** [tenacityteam/tenacity-legacy#94]
Since issue #​33 got deleted, will there be any explanation by the Tenacity Team about why the name “Tenacity” was chosen? I know this is a minor issue, and also a sensitive one, so I understand if you don't want to comment on this anymore. However, I must admit I got too emotionally invested in the discussion, I loved both “Brazen” and “AudioBakery” so I'd be happy to hear from you why you didn't like them :)
&lt;/bikeshedding>

**Comment by falkTX** [comment]
From what I understood, they were basically doxxed and this github project spammed hard, it was not possible to have a discussion here.

**Comment by peepopoggers** [comment]
#33

**Comment by j0lol** [comment]
we ended up doing a more private name poll due to the troubles with a "public" poll

**Comment by alicemargatroid** [comment]
Ah, so rather than the poll actually being open, honest, and worth something, it was closed off.
So what's the difference between this and MUSE again?

**Comment by peepo5** [comment]
How did this happen exactly? Didnt someone post it there as a joke and it got out of control? What actually happened on 4chan though?

Focusing on the new name (not sure if it is permanent), I think it was better than the other good alternative, audacium. I think this name is more easy to remember and simple. Nice! :+1:

**Comment by peepo5** [comment]
@alicemargatroid
It is because they were spammed by a 4chan raid, your eyes skipped the conversation in this thread - use them :eyes: :mag:

**Comment by alicemargatroid** [comment]
@peepopoggers I was _here during the 4chan raid_.
I just disagree with the reaction _to it_.

**Comment by cshaa** [comment]
@peepopoggers People from 4chan started spamming the hell of this project, doxing the moderators and otherwise acting hatefully and immature. This is what you get for wanting to build a community, apparently.

But please, keep this discussion about the chosen name, not about 4chan.

**Comment by caughtquick** [comment]
> @peepopoggers I was _here during the 4chan raid_.
> 
> I just disagree with the reaction _to it_.

Personally we felt that the risk of getting doxxed was higher than the value of allowing the name to be selected by everyone. The name was picked in private by a diverse group of ~15 people. Now that a decision has been made work can actually be made on the project.

**Comment by alicemargatroid** [comment]
@caughtquick I don't see the logic; doxxing already occurred.
Yet your decision removed agency from people wishing to contribute.

Why are you allowing hecklers to have a veto?

**Comment by j0lol** [comment]
> Ah, so rather than the poll actually being open, honest, and worth something, it was closed off.
> So what's the difference between this and MUSE again?

a naming poll was tried multiple times

**Comment by ApoorvaKashyap** [comment]
> > Ah, so rather than the poll actually being open, honest, and worth something, it was closed off.
> > So what's the difference between this and MUSE again?
> 
> a naming poll was tried multiple times

GitHub Issues is not equipped to conduct a viable poll.

**Comment by j0lol** [comment]
@ApoorvaKashyap do you have a better solution? any online, public poll can be flooded

**Comment by cshaa** [comment]
@j0lol @caughtquick Thank you for the quick response! I'm glad that the team decided on a name they like and we can move on! Looking forward to see Tenacity in action!

@alicemargatroid That's the beauty of open source – you can easily start your own fork and it's *only yours* to decide about. This for belongs to the Tenacity Team and *they* have the ultimate right to decide about it.

**Comment by caughtquick** [comment]
> @caughtquick I don't see the logic; doxxing already occurred.
> 
> Yet your decision removed agency from people wishing to contribute.
> 
> 
> 
> Why are you allowing hecklers to have a veto?

A public poll was frankly impossible during the state that the project was in at that time, we would have loved it make it public, but every attempt to do so failed due to trolls, discussion in polls, etc. Again I would like to reiterate that I would have loved to have to poll public but it simply wasn't a feasible solution and had already been tried not once, but twice. Also what name was "vetoed" by hecklers?

**Comment by alicemargatroid** [comment]
@j0lol Cool, and? We don't stop having elections when things go down.
We don't decide not to let people vote because the polling place can get flooded.

This logic is silly.

**Comment by alicemargatroid** [comment]
> > @caughtquick I don't see the logic; doxxing already occurred.
> > Yet your decision removed agency from people wishing to contribute.
> > Why are you allowing hecklers to have a veto?
> 
> A public poll was frankly impossible during the state that the project was in at that time, we would have loved it make it public, but every attempt to do so failed due to trolls, discussion in polls, etc. Again I would like to reiterate that I would have loved to have to poll public but it simply wasn't a feasible solution and had already been tried not once, but twice. Also what name was "vetoed" by hecklers?

It _was_ a feasible solution; I was here.
You didn't do any of the very basic things needed to make this succeed, and then threw up your hands.

I don't accept "we tried nothing and we're all out of ideas" as meaningful.

**Comment by j0lol** [comment]
i am sure in the future we would like to conduct polls in a safer way for project contributors, suggestions are welcome!

**Comment by caughtquick** [comment]
> @j0lol Cool, and? We don't stop having elections when things go down.
> 
> We don't decide not to let people vote because the polling place can get flooded.
> 
> 
> 
> This logic is silly.

I actually want to know what you proposed as an alternative to a private poll with many members of the community?

**Comment by alicemargatroid** [comment]
> @j0lol @caughtquick Thank you for the quick response! I'm glad that the team decided on a name they like and we can move on! Looking forward to see Tenacity in action!
> 
> @alicemargatroid That's the beauty of open source – you can easily start your own fork and it's _only yours_ to decide about. This for belongs to the Tenacity Team and _they_ have the ultimate right to decide about it.

Then ban and block me for daring to say "what you are doing isn't in the spirit of OS".

**Comment by alicemargatroid** [comment]
> > @j0lol Cool, and? We don't stop having elections when things go down.
> > We don't decide not to let people vote because the polling place can get flooded.
> > This logic is silly.
> 
> I actually want to know what you proposed as an alternative to a private poll with many members of the community?

Easy. Use a polling source that is easier to control, that has been battle tested against 4channers.
How about strawpoll, so you can limit votes based on captcha and IP?

**Comment by alicemargatroid** [comment]
> i am sure in the future we would like to conduct polls in a safer way for project contributors, suggestions are welcome!

Yeah, it totally makes sense to, when making a breaking fork over policies such as what MUSE did, to declare "We'll have freedom! ....eventually".

**Comment by ApoorvaKashyap** [comment]
> > > @j0lol Cool, and? We don't stop having elections when things go down.
> > > We don't decide not to let people vote because the polling place can get flooded.
> > > This logic is silly.
> > 
> > 
> > I actually want to know what you proposed as an alternative to a private poll with many members of the community?
> 
> Easy. Use a polling source that is easier to control, that has been battle tested against 4channers.
> How about strawpoll, so you can limit votes based on captcha and IP?

Google Forms is also a good tool because you can limit the response based on the email ids.

**Comment by peepo5** [comment]
@alicemargatroid make your own fork and name it whatever you want :)
This is not some vote-based development, it was just an ideas board that became unmanagable after lots of spam and harm to moderators. The name seems to be final as of now, so just chill, work with it and help develop this into a good project. This fork might go down the toilet, and so what, there are lots of other forks just like it (but i believe in this one) so dont worry :)

**Comment by alicemargatroid** [comment]
@peepopoggers Not a compelling argument

**Comment by cshaa** [comment]
Lock this?

**Comment by peepo5** [comment]
yes

**Comment by alicemargatroid** [comment]
> > > > @j0lol Cool, and? We don't stop having elections when things go down.
> > > > We don't decide not to let people vote because the polling place can get flooded.
> > > > This logic is silly.
> > > 
> > > 
> > > I actually want to know what you proposed as an alternative to a private poll with many members of the community?
> > 
> > 
> > Easy. Use a polling source that is easier to control, that has been battle tested against 4channers.
> > How about strawpoll, so you can limit votes based on captcha and IP?
> 
> Google Forms is also a good tool because you can limit the response based on the email ids.

Plenty of solutions possible. None of them tried.
"We've tried nothing and we're all out of ideas".

**Comment by caughtquick** [comment]
> > > > > @j0lol Cool, and? We don't stop having elections when things go down.
> 
> > > > > We don't decide not to let people vote because the polling place can get flooded.
> 
> > > > > This logic is silly.
> 
> > > > 
> 
> > > > 
> 
> > > > I actually want to know what you proposed as an alternative to a private poll with many members of the community?
> 
> > > 
> 
> > > 
> 
> > > Easy. Use a polling source that is easier to control, that has been battle tested against 4channers.
> 
> > > How about strawpoll, so you can limit votes based on captcha and IP?
> 
> > 
> 
> > Google Forms is also a good tool because you can limit the response based on the email ids.
> 
> 
> 
> Plenty of solutions possible. None of them tried.
> 
> "We've tried nothing and we're all out of ideas".

Again we weren't trying to go into an all our war with 4chan spammers, we also wanted the issue dealt with so we can move onto more pressing topics. You are mistakenly equating FOSS to a community FFA for all decisions, that's e beauty of FOSS. If you don't like the way we are handling it you are free to fork the repo and allow the community to vote, you can even take the patches from us, it's GPL after all 😀

**Comment by Caeglathatur** [comment]
No open source project, as far as I know, is governed by letting the entire Internet vote on things.

**Comment by emabrey** [comment]
@alicemargatroid
> Why are you allowing hecklers to have a veto?

You can't have a meaningful public vote where moderators pick and choose which votes are allowed as much as we had to in order to prevent non-contributing zero-history users from 4chan from hijacking the future of this open-source software without any intention of actually contributing. We tried multiple times anyways, and we failed. The trolls got what they wanted: to be an annoying distraction. Despite what I believe you have assumed about the motives of a lot of the suggestions, there are plenty of people with impure motives who had no intention of improving the software (they even admitted as much in their raid threads).


@m93a 
> ... will there be any explanation by the Tenacity Team about why the name “Tenacity” was chosen? 

The various options were ordered 1 to 8, with tenacity being the 7th option. I was going to provide the exact names, but there is still some small chance that the tenacity name won't work out potentially, so in the interest of not needing to figure this out again, I'm keeping that information close to the vest for now so that names can't be squatted. We do have a process in place for using the original vote for naming if that were to happen, since it was ranked-choice.
 
It was voted on using a ranked-choice system and the ballots were as follows (where each number corresponds to the names numbered 1 to 8):
 
7 3 6
7 5 4
7 6 4
8 4 6
4 7 1
7 6 4
7 8 3
7 6 8
7 8 6
6 1 7
6 5 7
7 6 4
6 4 2
6 7 4
6 5 7
6 3 8
8 7 4

Utilizing the rules that were agreed upon by all voters before the vote, the winner was 7 (Tenacity).

**Comment by Sciss** [comment]
The original attempt was to have an open process, but it got suddenly overrun by mob rule. That doesn't mean the process was in vain, I think those candidate names came out of the process. But when there is no system in place to prevent a loud minority that is otherwise not invested in the project at all gets to derail the process, it's best to abort that process. Free speech is not that who shouts loudest gets their say.

In the end, it's just a name. And perhaps there are other forks that use other names. Does our life depend on it? Probably not.

**Comment by davidak** [comment]
>No open source project, as far as I know, is governed by letting the entire Internet vote on things.

@Caeglathatur funfact: there actually was this experiment that tried exactly that https://github.com/Chaosthebot/Chaos

**Comment by n0toose** [comment]
Hi, I issued a clarification about the process we followed on #121. It should not be considered as an official means of decision-making (yet, we are waiting on additional feedback) and I am not representing the entire project (nor do I want to), but I hope that this can clarify some things about what we did and why.

**Comment by EchedelleLR** [comment]
> @ApoorvaKashyap do you have a better solution? any online, public poll can be flooded

https://poll.disroot.org/ in which comments are separated from votes and votes are forced to specific options.

However, it allows multiple votes if you change public IP and delete cookies.

In addition, using a password is a solution and providing them individually to access the poll.

**Comment by n0toose** [comment]
> https://poll.disroot.org/ in which comments are separated from votes and votes are forced to specific options.
>
> However, using a password is a solution and providing them individually to access the poll.

We would have probably used this if we knew about it. For more context, we considered Strawpoll (meh) as a way to carry another vote in public again, but the potential for abuse seemed probable.

(P.S. Not affiliated with the project at the moment, just clarifying.)
