### ISSUE TITLE
Stepdown as Maintainer of this Fork

### ISSUE THREAD

**Issue by cookiengineer** [tenacityteam/tenacity-legacy#99]
Disclaimer: I really thought long about this, and I haven't slept in two days due to ongoing harassments of 4chan.

As the first people were literally arriving at my place of living, where they knocked on my doors and windows to scare us, I am hereby officially stepping down as a maintainer of this project.

4chan thinks I cannot code C, so they win.
4chan thinks I'm unfit to lead the project, so they win.
4chan successfully bullied me out in order to have their fucked up sneedacity fork. A fork that was finally created with blood, quite literally.

I give up. I don't care. The safety of my family is worth more than an open source project. They found out my address via a YouTube video where someone was posting my nickname combined with my real legal name (which meanwhile got taken down due to my asking).

The incident happened shortly 23:00 CEST, today; and the police took over this case.

I will discuss this further in our (private as of now) communication channels with other people that helped out here so far, and will let you know of a successor.

Please, if you have the time, report the https://github.com/Sneeds-Feed-and-Seed/sneedacity project to GitHub as a hate speech, violence and harassment insinuating project). Report every single member contributing in this fork, because they were part of the harassment movement against me and my family.

They are cyber terrorists, not cringe cancel kiddos. They physically tried to harm me in real life, and this has gotten out of hand.

4chan people made up stories about me posting here, posting there. Faking sceenshots, calling out even themselves as "cookie faggot" because they cannot verify any source of information they use as "source of truth" for their executive actions. I never posted on 4chan, and I never will. This site is the most disgusting place in the whole world, and I think all the people that are active in /g/ should get put in jail and be ashamed of themselves for making the world a worse place than it already is.

**They are physically harming people, in real life. Be aware of anything you do BEFORE trying to do the right thing.**

This is not cancel culture. This is not anon. This is tyranny, oppression and senseless physical violence. Something the anon movement never stood for in the beginning.

In case people didn't follow what happened, here are the threads with lots of faked shitposts, faked sceenshots, defamations and whatnot:

The relevant 4chan threads about "sneedacity" (which is equivalent for harassing me):

- https://boards.4channel.org/g/thread/82413768
- https://boards.4channel.org/g/thread/82410116
- https://boards.4channel.org/g/thread/82409026
- https://boards.4channel.org/g/thread/82407520
- https://boards.4channel.org/g/thread/82413937
- https://boards.4channel.org/g/thread/82416433
- https://boards.4channel.org/g/thread/82418711
- https://boards.4channel.org/g/thread/82420783

I knew from the start that I wanted to not govern this project, as all the other invited members of this organization already knew. I believe this project can succeed by embracing an open governance model. And I still think that my actions were morally correct and the right thing to do.

Also, I am in contact with GitHub and the German BKA (federal police) as of now, therefore I will not disclose any more information publicly about what happened to anyone. Evidence has been gathered, submitted and will be acted upon. I will not legally let go of this.

When another more fitting project lead has been elected by the team, I will let you know here. I will revoke my own vote on this matter.

Thank you for your understanding, even though it has been a horrible journey for me so far.

~Chris

**Comment by EricBright** [comment]
I appreciate all the work and efforts you have already put into this project. Whatever you decide would certainly be respected a understood by the community. You have already left your positive mark on this project as it is.

To the moderators: please kindly delete any comment under this issue that is not respectful of the author, the community, and is irrelevant to the OP. Thank you for your hard work!

**Comment by Pythone** [comment]
you will be remembered

**Comment by alicemargatroid** [comment]
>Please, if you have the time, report the https://github.com/Sneeds-Feed-and-Seed/sneedacity project to GitHub as a hate speech, violence and harassment insinuating project). Report every single member contributing in this fork, because they were part of the harassment movement against me and my family.

This is categorically untrue and just another form of the same attacks you experienced.
Sneeds-Feed-And-Seed is not a reference to hate speech, and not every member of the form was part of that harassment movement.

Bad look my dude. Don't become the very thing harming you. Don't wish harm on other people who may be innocent.

**Comment by ghost** [comment]
Oh god that sounds horrible.

**Comment by ghost** [comment]
> Please, if you have the time, report the https://github.com/Sneeds-Feed-and-Seed/sneedacity project to GitHub as a hate speech, violence and harassment insinuating project). Report every single member contributing in this fork, because they were part of the harassment movement against me and my family.

None of the Sneedacity contributors have anything to do with this. Calling on people to mass-flag a competing fork is beyond bad faith and is a direct violation of the [Github Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines).

**Comment by ishimotoshinobu** [comment]
>As the first people were literally arriving at my place of living
Any proofs? You've deleted tweets about ppl calling you and misquoted your own words many times?

**Comment by ishimotoshinobu** [comment]
FEED AND SEED
![image](https://user-images.githubusercontent.com/85226636/124678008-a36ebb00-defc-11eb-917e-006d2cf4db7e.png)

**Comment by ishimotoshinobu** [comment]
h-hello?
![image](https://user-images.githubusercontent.com/85226636/124678052-bda89900-defc-11eb-8751-f6cb9c37e482.png)

**Comment by Ckath** [comment]
at least that explains why you kept posting personal info in our friendly sneedacity development threads. its weird though despite your efforts no one even went along with your baiting. it only makes you look worse that you link these threads here.

I guess its all banking on people not actually reading these threads themselves so let me give you a rundown of the past ones:

1. cookie keeps changing his gh status to current thread posts, clearly wanting some attention (scroll up in the thread linked next point)
2. he proofs a couple times in these threads its him by changing the status to what he's typing there https://desuarchive.org/g/thread/82418711/#82420604
3. continues to very clearly (yet poorly) bait people into doxing by posting personal info himself, people call this out pretty much every time (https://desuarchive.org/g/thread/82420783/#82421238)
4. threads slowly settle back into sneed development

besides it being a gh post and not a hn post, pretty much called it as well you'd pull this final and ultimate victim card
![image](https://user-images.githubusercontent.com/15038414/124677790-b2c81700-deb0-11eb-95b8-629d919e46e4.png)

kindly stop digging yourself a deeper hole you're already in

**Comment by emabrey** [comment]
@alicemargatroid
>     3\. Nearly _no one_ from /g/ did anything to harm this project

You are lying. Please stop arguing with him. What exactly do you hope to accomplish by your posts directed at @cookiengineer?

@kakolisgay
You personally have a sneedacity repository so you aren't at all likely to be an inoccent third-party like you seem to be hoping people will assume.


I locked the thread because @cookiengineer is stepping down and people from 4chan arguing with him to try to increase the amount of harm they can cause is not related to software dev at all.

**Comment by emabrey** [comment]
I'm leaving up @alicemargatroid's post because it isn't clearly against any rules and I'm not absolutely sure they are arguing in bad faith. However, I want to point out that I believe they are in fact arguing in bad faith.

**Comment by emabrey** [comment]
I want to clarify that earlier the /g/ board users were discussing and planning out how to get @cookiengineer banned from GitHub. It isn't unreasonable to look at the post from @alicemargatroid as an implementation of that harassment plan. That is why I believe they are acting in bad faith. I have blocked four users from this thread, two for 3 days for abusive 4chan spam and the other two for 7 days for participating in harassment, including alicemargatroid . This information is provided to be transparent to other users, and I want to underline the fact that simply being a 4chan user is not enough to get you banned here, but participating in a harassment campaign against a fellow developer is. I have seen the online harassment personally, so I am willing to vouch that harassment IS occurring, despite what any concern trolling 4chan users may post. I have left up alicemargatroid's post, though I removed their duplicate issue attempting to imply that cookiengineer is being kicked out (he is not in _any_ way being forced out by members of the Tenacity community).

**Comment by cookiengineer** [comment]
@alicemargatroid

You can also simply to stop the trolling facade now.

1. It was attempted murder with an illegal butterfly knife.

2. Read access to 4chan is not write access. You, as an enlightened 4chan user yourself (I've seen your screenshots) should know that.

3. There's no way the Staatsanwaltschaft Mannheim will let go of this. I'm not providing evidence because you didn't provide it either. You use your Devtools as source of truth and destroy the lifes of other people AND ATTEMPT TO KILL THEM. If you are defending this behaviour, you are an accomplice.

4. I'm not posting pictures, because I'm certainly not going to compromise the ongoing investigation of the BKA Heidelberg because some kiddos want so-called "proof" which they will turn around and twist around until it fits their sociopathic logical needs.

5. Read the 4chan threads, they collectively decided it's a "fun way" to scare me at my place. That's all the "4chan level of so called proof" you need.

**@GitHub admin who is reading this:

Sorry for my language, but this is an official matter now and I'm out of any nerves to deal with these criminals. If you block my account for writing the word "asshole", so be it. I don't care at this point.

Please contact me on my mobile phone number before you do, and I will give you the official contacts at the BKA Heidelberg (Germany, so CEST) that are part of the ongoing Straftat investigation in this matter.**

Damn sociopathic 4chan criminals, I still don't believe the level of balls they have. They think they can do anything.

edit: clarifications so there's no possible cynical misinterpretations of my words.

edit 2: clarifications so defamation attempts can be minimized.

**Comment by cookiengineer** [comment]
@ishimotoshinobu 

I also did not delete any of my Tweets. And I certainly do not work for the CIA as multiple 4chan users seem to have implied by using the word "glown***a" multiple times. Note that ishimotoshinobu is also part of the 4chan raid (see their threads and screenshots as evidence).

Your conspiracy theories are wrong. Get over it, assholes.
